### ISSUE TITLE
TCon casting table crash

### ISSUE THREAD

**Issue by xSparky911x** [CyclopsMC/IntegratedTunnels#10]
Forge 2202
Integrated Tunnels 1.0.3
Integrated Dynamics 0.6.6

I had set up a simple Importer from a Tinkers smeltry casting table (with ingot cast) to a Crystal Chest. As soon as I added the card the game crashed. 

http://pastebin.com/QzRpnKdz

**Comment by rubensworks** [comment]
@xSparky911x It looks like TCon is emitting a `SidedInvWrapper` with either a `null` inventory or side, which causes the game to crash.
Could you report it to their issue tracker as well? There's not much I can do to fix this from my end.

**Comment by xSparky911x** [comment]
K will do although when hooking up Ender Conduit to the same side of the same casting table rather than the Integrated Tunnels pipe all seems fine.

**Comment by rubensworks** [comment]
Has been fixed on TCon's end.
