### ISSUE TITLE
Slow at putting bees in Apiaries

### ISSUE THREAD

**Issue by WilxGaming** [CyclopsMC/IntegratedTunnels#108]
snail: Performance issue

#### Short description:
An Importer on the bottom of an Apiary. 
Interface on the back of the Apiary with a priority of 10. 
Interface on a chest with a priority of 0.

#### Expected behavior:
Normally transfers happen instantly.  

#### Actual behavior:
It took several seconds (a noticeable delay) to put the bees in the apiary.
Without setting the priority the chest would be the path of least resistance and get the bees.

#### Steps to reproduce the problem:
Tried with several apiaries all side by side in the same chunk. The chests were at different y distances on the logic cable. Logic cables were separate for each apiary.
____
#### Versions:

I am using newer versions now, but testing was done with: 

IntegratedDynamics-1.12.2-0.10.1.jar
IntegratedTunnels-1.12.2-1.4.1.jar
CyclopsCore-1.12.2-0.11.1.jar
Minecraft: 1.12 
forge-14.23.1.2587

No log file was created

**Comment by rubensworks** [comment]
@WilxGaming Thanks! Will look into it.

Note to self: possibly an issue in the item transfer caching mechanism.

**Comment by rubensworks** [comment]
@WilxGaming Can't reproduce this here, transfer works just fine. Are you sure the tick rate of any of the parts haven't been lowered?
Can you share a screenshot of your setup? (A video demonstrating the issue would even be better if possible)

I assume you meant an exporter on the bottom of the apiary, the importer obviously won't do anything.

**Comment by WilxGaming** [comment]
@rubensworks 
> I assume you meant an exporter on the bottom of the apiary, the importer obviously won't do anything.

No. I have an Importer on the bottom of the apiary. When the queen splits into a princess and drones, the importer pulls them out, then tries to put the princess and any drones it can back in. Combs or drones that don't fit go into the chest.

**Comment by rubensworks** [comment]
> It took several seconds (a noticeable delay) to put the bees in the apiary.

Ok, but what are _the bees_ in this case? The ones from the apiary? Or the ones from the chest?

How can I reproduce this easily?

**Comment by WilxGaming** [comment]
@rubensworks 
> The ones from the apiary? Or the ones from the chest?

From the apiary output slots, into the apiary input slots.

Put a queen in the apiary, or a princess and drone to make a queen, and wait for it to finish it's lifespan. Then watch to see how long it takes to remove and replace them. You need to be looking in the apiary when it happens.

Cultivated is one of the bees with the shortest lifespan, 4:35 min.

**Comment by rubensworks** [comment]
@WilxGaming Yeah, waiting 4:35 min is way too long for me. Is there a quicker way for me to reproduce this? (Haven't played with bees before, so don't really know much about it)

**Comment by WilxGaming** [comment]
@rubensworks 
Cheating in a Nova frame and placing it in the the apiary reduces the lifespan to 0, but it still not instantaneous.

**Comment by WilxGaming** [comment]
@rubensworks  Using an EU2 Transfer node is much faster, but they don't have a priority system. So it's an integrated tunnel thing, not just an apiary thing.

**Comment by rubensworks** [comment]
Apparently that Nova frame is not part of Vanilla Forestry. Until I either have a quicker and more convenient way or have a lot of time, I'll put this on hold.

@WilxGaming In the meantime, are you sure the delay is not just half a second (which is normal)? Are you also experiencing this delay with the same setup on regular chests? (It _is_ possible to configure this delay (`inventoryUnchangedTickTimeout`), which is by default 10 ticks, but may be higher in your pack for performance reasons)
