### ISSUE TITLE
Make channel settings less confusing

### ISSUE THREAD

**Issue by ZeekDaGeek** [CyclopsMC/IntegratedTunnels#109]
#### Issue type:

- :bug: Bug

____
#### Short description:
"Item Importers" and similar have an "Energy Channel" while "Item Interfaces" have an "Interface Channel". At first I thought this was just a bug with the language file or something but when I change the Item Importer's channel it will still only send items to Interface channel 0, so it seems to be an actual problem with what number it's setting behind the scenes.

#### Steps to reproduce the problem:

1. Place down an Item Importer and set it's Energy Channel to 4.
2. Place down an Item Interface and set it's Interface Channel to 4.
3. Place a variable card in the Item Importer's "Import All Items" slot to pull all items connected.
4. Observe that no items are ending up in the destination location.
5. Change the Item Interface's channel to 0.
6. Observe that all of the items are now moving.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: IntegratedTunnels-1.12.2-1.4.1.jar, IntegratedDynamics-1.12.2-0.10.1.jar
- CyclopsCore: CyclopsCore-1.12.2-0.11.1.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2590

#### Log file:

_Not relevant, no errors occur._

**Comment by josephcsible** [comment]
Not a bug. You set the channel used by importers and exporters in the aspect settings, not the part settings.

**Comment by ZeekDaGeek** [comment]
Why is there an energy channel option on Item Importers then? What's that for?

![Question mark](http://zeekdageek.tv/ss/Zl5wg.png)

**Comment by josephcsible** [comment]
If parts are configured to require energy to work, that's the channel that they draw it from.

**Comment by ZeekDaGeek** [comment]
May I offer a little icon as a suggestion then, saying something like "Settings do not require energy for operation." and graying out the input.

**Comment by ZeekDaGeek** [comment]
Also having them uniformly called "Interface Channels" to prevent confusion would be very helpful. At the moment the Item Importer just says "Channel"

**Comment by rubensworks** [comment]
Yeah, I was concerned about this becoming confusing...

**Comment by josephcsible** [comment]
There's still one confusing case left: interfaces still have a seemingly useful, but useless, energy channel setting.

**Comment by rubensworks** [comment]
That's intended, see extended commit message in 8dce20b65771f11a33825e2d7783379b771499f2.

**Comment by josephcsible** [comment]
Maybe we should give them their own "disabled" tooltip unless/until they do start consuming energy.

**Comment by rubensworks** [comment]
I don't consider this worth the effort, as I highly doubt this feature is widely used. Feel free to send a PR.
