### ISSUE TITLE
Magical Disappearing Items

### ISSUE THREAD

**Issue by ZeekDaGeek** [CyclopsMC/IntegratedTunnels#110]
#### Issue type:

- :bug: Bug

____
#### Short description:
For this magic trick you will require a few things. 1 Player Simulator, 1 World Block Exporter, 1 Item Interface and all the cables required to connect them together.

#### Expected behaviour:
Not losing all of the tools.

#### Actual behaviour:
Losing all of the tools.

#### Steps to reproduce the problem:

1. Set up your magic kit as showing here: ![Magic kit](http://zeekdageek.tv/ss/amfzZ.png)
2. Put a bunch of Stone and Diamond Pickaxes in your chest.
3. Set a Variable card for Item Stone and put it into your World Block Exporter.
4. Set a Variable card for Item Diamond Pickaxes and put it in your Player Simulator.
5. Change the options for your Player Simulator as follows: Right click: false, Left Hand: false, Check Damage: false  _** Edited: Clarified settings better._
6. Impress your audience with all of your now disappeared Diamond Pickaxes.
7. If you really want to impress your friends, attempt to use more valuable tools!

The problem seems to be related to "Left Hand," when left hand is true it doesn't happen, which is weird, by default you use tools in your Right Hand... Setting seems backwards overall.

____
#### Versions:

- This mod: IntegratedTunnels-1.12.2-1.4.1.jar, IntegratedDynamics-1.12.2-0.10.1.jar
- CyclopsCore: CyclopsCore-1.12.2-0.11.1.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2590

#### Log file:

_No errors occurred, obviously expected behaviour._

**Comment by rubensworks** [comment]
Thanks for reporting, this is obviously not supposed to happen.
