### ISSUE TITLE
Loosing/duplicating Watering Can from Mystical Agriculture when using Player Simulator

### ISSUE THREAD

**Issue by bbf** [CyclopsMC/IntegratedTunnels#111]
#### Issue type: 
- :bug: Bug

#### Short description:
I'm trying to automate the use of a watering can from Mystical Agriculture using the Player Simulator. 

#### Expected behaviour:
Crops grow happily and water particles effects should be seen.

#### Actual behaviour:
There are 2 possible outcomes:

1. The item is destroyed with the following log:
[21:45:22] [Server thread/WARN] [Integrated Tunnels]: Just lost stack 1xitem.ma.watering_can@2 while transfering items, report this to the Integrated Tunnels issue tracker with some details about your setup!

2. The item is duplicated and both tossed into the world.

#### Steps to reproduce the problem:
1. Prepare a 5x5 dirt plot.
2. Remove the center block and replace with water.
3. Place one dirt block above the water.
4. Attach the player simulator to the top of that dirt block.
5. Connect a cable to the player simulator.
6. Place a chest over the cable.
7. Attach a item interface between the cable and the chest.
8. Use the programmer to create a variable card for the watering can.
9. Configure the player simulator "Click Item".
10. Place the variable with the watering can on the Click Item.
11. Place the watering can on the chest.

To duplicate the item, use the following params on step 9:
Right Click false
____
#### Versions:
- Integrated Dynamics: 1.12.2-0.11.0
- Integrated Tunnels: 1.12.2-1.5.0
- CyclopsCore: 1.12.2-0.11.2
- Minecraft: 1.12.2
- Forge: 14.23.1.2607
- Mystical Agriculture: 1.6.7

#### Log file:
<snippet pasted above>

**Comment by rubensworks** [comment]
Thanks for reporting! Will look into it.

**Comment by ofseaandstars** [comment]
Can also confirm that this bug exists. I attempted to use a player simulator with a bucket to milk a cow and the bucket just vanished from the network, and had the same error as above.

**Versions:**
- Integrated Dynamics: 1.12.2-0.11.1.jar
- Integrated Tunnels: 1.12.2-1.5.0.jar
- CyclopsCore: 1.12.2-0.11.2.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2610

**Comment by rubensworks** [comment]
@AshenGaming Thanks, pure-vanilla mechanics will be easier for me to test with.

**Comment by JanSeidlerSF** [comment]
Hi there,

this is still happening. I am using ID to automate flowers of Botania. (3 Player Simulators using Click Item each: 1 for planting petals, 1 for bonemealing, 1 to use a Paper Kama on the grown plant.) Result: Paper Kama gets duplicated and thrown into the world.

Modpack: All the Mods 3 v5.12.2 (ForgeMultipart-1.12.2-2.6.1.81-universal)
IntegratedDynamics-1.12.2-1.0.17
IntegratedTunnels-1.12.2-1.6.10
CyclopsCore-1.12.2-1.4.0

**Comment by rubensworks** [comment]
@JanSeidlerSF Could you create a separate issue, and include some more information on how to reproduce the issue? Because it sounds like a slightly different problem to the one described before.
