### ISSUE TITLE
Parts can be clicked through client-side, but not server-side

### ISSUE THREAD

**Issue by ofseaandstars** [CyclopsMC/IntegratedTunnels#113]
#### Issue type:
- :bug: Bug

#### Short description:
When a player simulator and chest are connected (with an item interface), when opening the chest the milk bucket will empty.

#### Expected behaviour:
Opening the chest inventory will not affect the items already in the player inventory

#### Actual behaviour:
The milk bucket is emptied and restacked onto the existing buckets.

#### Steps to reproduce the problem:

1. Have a player simulator facing a cow and connected to an item interface and chest.
2. Have 2 empty buckets stacked in your inventory.
3. Right click a cow (must be in survival mode) to milk it.
4. Open the connected chest and note that the milk bucket has emptied, and restacked onto the existing empty bucket.

Note: Does not seem to affect in-world fluids (such as water/lava). I tested this in an instance only including Integrated Dynamics and Integrated Tunnels (and obviously Cyclops Core/Common Capabilities) etc. Does not occur on a forge-only instance.

[Imgur upload demonstrating bug](https://i.imgur.com/vkuwn0m.gifv)

____
#### Versions:

- This mod: 1.12.2-1.5.2
- CyclopsCore: 1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2615
- Integrated Dynamics: 1.12.2-0.11.3
- CommonCapabilities: 1.12-1.4.0

**Comment by rubensworks** [comment]
Could you clarify your steps to reproduce the problem? Are you right clicking? Or is the simulator right clicking? Where do the buckets go? In your inventory? Of the chest?

**Comment by ofseaandstars** [comment]
I'm right clicking the cow manually. The milk bucket when emptied just
stacks on top of the other bucket in my inventory.

**Comment by rubensworks** [comment]
It's probably just a desync because you're sneaking through a block, your bucket probably was never filled. Can you try reproducing it without right clicking through that narrow space?

**Comment by ofseaandstars** [comment]
I will do that when I'm at my PC later :)

**Comment by ofseaandstars** [comment]
I just tested again without right clicking through the gap, and I can confirm that the bug doesn't occur.

**Comment by rubensworks** [comment]
Alright, I'll change the title of this issue then.

**Comment by rubensworks** [comment]
Just tested this again in the latest ID version (1.0.13), and this seems to be working properly now.
