### ISSUE TITLE
Can't extract water from Cooking for Blockheads sink

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedTunnels#114]
https://www.reddit.com/r/feedthebeast/comments/7xyoqs/comment/duc9b8t

I haven't confirmed this bug myself yet, but I'll try it tonight.

**Comment by josephcsible** [comment]
Confirmed. Versions:
* Minecraft 1.12.2
* Forge 2616
* CyclopsCore 0.11.4
* CommonCapabilities 1.4.0
* IntegratedDynamics 0.11.4
* IntegratedTunnels 1.5.2
* Cooking for Blockheads 6.3.17

**Comment by KITbutler** [comment]
- Direwolf20 MC1.12.2 pack 1.8.0 with manual additions and mod updates
- Forge 14.23.1.2601
- Cyclops Core 0.11.4
- Integrated Dynamics 0.11.4
- Integrated Tunnels 1.5.2
- Cooking for Blockheads 6.3.17

The One Probe shows an empty tank on the sink. ID Fluid Reader output is fully consistent with an empty tank. Block Reader Tile Entity NBT shows _Empty: ""_ and some basic data, no hints towards any hidden fluid source.

Tested both Fluid Importers and Fluid Exporters always with a valid Fluid Interface destination and a blank variable card in the (bool) "All Fuilds" field. Replacing the CfB sink with a Thermal Expansion Creative Tank filled with water immediately outputs fluid as expected. For the record Refined Storage, Applied Energistics 2 with ExtraCells and Extra Utilities 2 all extract water as expected.

**Comment by josephcsible** [comment]
Potentially Cooking for Blockheads' fault. It looks like they're using a container that says it's empty when you ask, but will give you water anyway if you try to drain from it.

**Comment by josephcsible** [comment]
My fix for Cooking for Blockheads got merged, so this will start to work with it in its next release.

@rubensworks Do you consider this to just be a bug in their side that we don't need to worry about, or should we fix this on our side too?

**Comment by rubensworks** [comment]
I guess we can assume contract-adherence of fluid handler implementors. If this would cause further problems in the future, we can revisit this. But for now, I guess we can consider this fixed.

**Comment by FrAmed46** [comment]
doesnt work for me either now
