### ISSUE TITLE
Using Player Simulator Question

### ISSUE THREAD

**Issue by Exanadu** [CyclopsMC/IntegratedTunnels#116]
- :question: Question

So I am just attempting to use player simulator to place an item into a (grindstone) from a chest. I have a chest with item interface, connected to a player simulator and place the item card for the item into the click item slot. it is set to right click but nothing happens. I am not sure what else needs to be done here to grab the item from the chest? Any help would be appreciated.

**Comment by josephcsible** [comment]
What machine? Does right-clicking the machine make the item go in, or is there a GUI? If the latter, use an item exporter instead of a player simulator.

**Comment by Exanadu** [comment]
sorry edited it just before your comment to be more clear, its a grindstone from astral sorcery

**Comment by Exanadu** [comment]
im setting it up to right click the crystal into the grindstone from a chest and keep clicking until cutting is 100% which i have the rest setup but cannot get the player simulator to place a crystal no matter what i have tried so far.

**Comment by Exanadu** [comment]
on a side note i cannot even get it to right click at all even if i place the crystal myself.  just putting click true should make it right click am i right?

**Comment by rubensworks** [comment]
I have no idea tbh, I never played with AS myself. I know other people in the ID discord (link on curseforge) have managed to do this, perhaps you should ask around in there.

**Comment by Saklad5** [comment]
I have the same problem. It outputs correctly when I replace the Player Simulator with an Item Exporter and the Grindstone with a vanilla chest, so I know it isn’t my logic or channels that’s faulty.

Items can also be placed on the grindstone using an Extra Utilities 2 Mechanical User, or placed in the world with the Player Simulator if the latter has a gap in front of it followed by another block. They are also correctly placed in item frames.

The Player Simulator won’t even break the Grindstone if I tell it to left-click. It can’t interact at all.

**Comment by rubensworks** [comment]
@Saklad5 Is it possible that this Grindstone has a smaller bounding box? If so, you should try playing around with things like the x, y, z, yaw and pitch aspect settings.

**Comment by Saklad5** [comment]
That was my initial theory, but it doesn’t seem so. The bounding box of the grindstone is actually a full block, and the player seems to be able to interact with it regardless of angle.

**Comment by Saklad5** [comment]
I tried reading the source, but Astral Sorcery’s code is rather unintuitive. The Player Simulator can interact with other blocks from the mod, by the way: if you put a Spectral Relay (like a pedestal you click items onto) in front of it, it works properly.

I’m going to open an issue about this with Astral Sorcery. Even if none of this happened, it is still ridiculous that the Grindstone doesn’t expose an inventory of any kind.

**Comment by rubensworks** [comment]
Apparently AS intentionally blocks automation, so there's not much I can do from my end.

**Comment by Saklad5** [comment]
I don’t think it is intentional, as other blocks from that mod work fine. In light of that, however, I agree that this issue is not going to be solved by changing this mod.

**Comment by josephcsible** [comment]
It is intentional. Read the comment by @HellFirePVP on the linked bug.

**Comment by Saklad5** [comment]
I just saw it, yeah.
