### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Kenshij** [CyclopsMC/IntegratedTunnels#118]
Hi,

Energy Exporter only exports 4k RF per Exporter, but i can write a higher number in the export rate field. and its nowhere mentioned that it is limited to such a small number.

**Comment by josephcsible** [comment]
The energy exporter has no such limit. It's the thing that it's attached to (or maybe the thing the the interface is attached to) that's limiting you.

**Comment by rubensworks** [comment]
It should indeed be unlimited. It might be the energy battery (or any other kind of attached energy storage) that is limiting you.

Note that there's a `energyRateLimit` setting in the ID config file, which may have been set to 4K in your pack?

**Comment by Kenshij** [comment]
Then i must convert it to a bug, nope works as configurated ^^
Modpack:  Enigmatica 2: Expert
Config :  I:general.energyRateLimit=2147483647

Setup:
From Thermal, Cryo Stabilized Fluxduct, Energy Trash and Creative Powercell vom RFTools
Messure with Multimeter
Powercell -> Trash, 100.000 RF Transfer Rate

Powercell -> Energie Importer -> Energy Interface with Energy Battery -> Energy Exporter to Fluxduct, 2.000 RF 

with multiple Energy Interface with Energy Battery 2.000 RF more each

with another battery from other mod the trasfer works as intended

conclusion the  Energy Battery limits the trasfer rate to 2kRF
 Is there a config option for this limit ? 

Have found it, I:energy_battery.energyPerTick=2000 , so this is the problem, must switch batterie on the interfaces, 
thanks for the time

**Comment by rubensworks** [comment]
> Is there a config option for this limit ?

Yes there is.
