### ISSUE TITLE
Round robin behavior intended?

### ISSUE THREAD

**Issue by bpwhelan** [CyclopsMC/IntegratedTunnels#119]
#### Issue type:

_Only keep the issue types that are applicable._

- :question: Question

Just asking if this is intended behavior. Round robin halts on "current" interface IF an item isn't "pushed." I'm assuming the intended behavior would be "check interface, push items if possible, move onto next regardless of priority." (my assumption could be incorrect of course) In current implementation, if you are pushing and pulling items to/from a block (think slime generators from exU2 with milk buckets), your system will almost always halt indefinitely until the current interface's block is cleared up. 

Possibly an option for strict round robin (current implementation) and loose round robin (assumed intended behavior)?

Apologies if this is confusing, I am willing to give any useful information if needed.

**Comment by rubensworks** [comment]
Hmm, that sounds like non-intended behaviour. It should loop through _all_ interfaces until it finds a valid target.

Could you give some more details on your setup?

**Comment by bpwhelan** [comment]
Hmmm... Seems inconsistent, I made a simple mock setup with 2 slime generators, the RR gets stuck on one of them, but not the other... I was however, able to completely tear this system down and rebuild it and get the same issue.

Video demo: https://www.youtube.com/watch?v=z9UMdkniotE&feature=youtu.be
