### ISSUE TITLE
IndustrialCraft2 Crop Matron (and possibly other machines)

### ISSUE THREAD

**Issue by Daenara** [CyclopsMC/IntegratedTunnels#12]
Sorry, me again. The IndustrialCraft2 people came up with a fix to make it work with mods that don't use interfaces anymore so transferring fluids works, well, in most cases. The Integrated Dynamics fluid reader registers all tested blocks with tanks correctly but the transport to the crop matron won't work. My guess it's because it has two inbuilt tanks. I tested on all sides of the block to rule out that input has to go to a specific side for it to work. The fluid reader told me, that there is a list of fluids this tanks accept, I'm not sure what that list contains because the only one readable was water but since I tested with water it should not be the problem.

Daenara

**Comment by rubensworks** [comment]
Do other fluid transport mods work?
There shouldn't be a reason why machines with multiple internal tanks won't work, unless the machines blocks certain things, or I made a mistake somewhere...

**Comment by Daenara** [comment]
I haven't tried another mod, I don't have one. If you could recommend one working on 1.10 I can try.

**Comment by rubensworks** [comment]
ExtraUtils2 and EnderIO have fluid transfer pipes.

**Comment by Daenara** [comment]
I couldn't get ExtraUtils2 to work at all but I managed to get EnderIo to work. I can't insert fluids to the crop matron with this either but I don't really get why. If I compare the output of a fluid reader stuck to a tank and one stuck to the crop matron the only difference (besides the size) is the number of tanks.

**Comment by rubensworks** [comment]
@Daenara What is the status on this? Has IC2 already been updated to support fluid capabilities?

**Comment by Daenara** [comment]
I'm not sure what the fix they released contains because I don't know their apis but I can tell you that most blocks now work. What still doesn't work is the crop matron, I'm not sure if it's because of their fix or because of the multiple tanks in one block.

**Comment by rubensworks** [comment]
Sounds like an issue on IC2's end then, since other fluid transfer mods are also not capable of inserting fluids.

Multiple tanks in a block shouldn't be an issue in general, unless the receiver machine blocks this.

**Comment by Daenara** [comment]
They fixed it, so it was on their end.
