### ISSUE TITLE
Crash when setting World Energy Exporter Entity Index

### ISSUE THREAD

**Issue by Landstryder** [CyclopsMC/IntegratedTunnels#120]
#### Issue type:
- :bug: Bug

____
#### Short description:
Game crash and loss of the ability to log back in that world when you set the World Energy Exporter value "Entity Index" to -1

#### Expected behaviour:
Tool tip suggest that using a value of -1 will pick an entity randomly

#### Actual behaviour:
When setting it to -1 it crashes the game and then you can no longer log back into that world

#### Steps to reproduce the problem:

1. Place World Energy Exporter
2. Set Entity Index to -1
3. Crash

____
#### Versions:

- This mod: 1.12.2-1.5.2
- CyclopsCore: 1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2623

#### Log file:

https://pastebin.com/bsZHfmBz

**Comment by rubensworks** [comment]
Fyi, you can set the mod to safe-mode via the config file to log back into your world and remove the crashing part.

**Comment by Landstryder** [comment]
It turns out any attempt to use the World Energy Exporter has the same effect, regardless of the settings. As soon as you activate it by putting variable card in it.. CRASH!
