### ISSUE TITLE
Issue with player simulator and choice (?) operator 

### ISSUE THREAD

**Issue by nerfviking1** [CyclopsMC/IntegratedTunnels#121]
#### Issue type:

- :bug: Bug

____
#### Short description:

Player simulator isn't recognizing the change of a choice operator, and continues placing the item even after the operator is returning an empty item.

#### Expected behaviour:

Player simulator should recognized that choice operator now returns an empty item and stops placing it.

#### Actual behaviour:

Player simulator continues repeatedly placing item.

#### Steps to reproduce the problem:

Here's my setup:

- I've got a block reader. I've got a boolean variable that is true if the block in front of the block reader is there, or false if it's empty.
- On the other side of the empty block, I have a Player Simulator. I have it set up to place crop sticks in front of it, but only if the block is empty.

I've set this up with a "?" operator that returns a Crop Sticks item if the block is empty, or an empty item if the block is occupied. When I put the operator into a display screen, it acts as expected, only showing crop sticks when the block is empty, and not when there are already crop sticks there.

When I put the same operator into the Player Simulator, it repeatedly places crop sticks, even when the crop sticks are already there (which has the effect of repeatedly adding and removing cross sticks).

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-1.5.4
- CyclopsCore: 1.12.2-0.11.5
- Minecraft: 12.2
- Forge: 14.23.2.2618

#### Log file:

Log is too big, and there's no crash anyway.  However, I did make an imgur album of what's going on in case my explanation is bad:

[https://imgur.com/a/c5QFq](https://imgur.com/a/c5QFq)

**Comment by rubensworks** [comment]
Thanks for reporting!
