### ISSUE TITLE
Cannot interact with Item importers/exporters

### ISSUE THREAD

**Issue by kevincook** [CyclopsMC/IntegratedTunnels#123]
#### Issue type:

- :bug: Bug

____
#### Short description:
After upgrading to 1.5.5 I can no longer interact with item importers and exporters.  When I right click the interface an exception is logged in the console.  

#### Expected behaviour:

The gui for the importer exporter should show

#### Actual behaviour:

Nothing happens, and an exception is logged in the console.

#### Steps to reproduce the problem:

1. Storage Drawer controller and ender chest have a cable between them.  Interface connected to drawer, export interface connected to ender chest.  Right clicking on the export interface does nothing.  Exception is logged in console.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.5.5
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2627

#### Log file:

https://pastebin.com/2KZnUZJa

**Comment by rubensworks** [comment]
What version did you upgrade from?

Could you share the _full_ forge log?

**Comment by kevincook** [comment]
I'll work on the log and the versions I upgraded from, but wanted to give an update.  

When I create a new world, things seem to work just fine, so it must have to do with the upgrade.

**Comment by kevincook** [comment]
Also, removing CraftTweaker mod seems to have resolved the issue.  I'm happy to add CraftTweaker back and get the log for you if you want, otherwise, I'll just get rid of CraftTweaker and move on.

**Comment by josephcsible** [comment]
Are you on an outdated version of CraftTweaker? Try updating it.

**Comment by kevincook** [comment]
Sorry, I was wrong... it was Crafting Tweaks that I removed, not CraftTweaker.  And my Crafting Tweaks is out of date... I'll update Crafting Tweaks and see if it improves things.

**Comment by kevincook** [comment]
Updating CraftingTweaks does not resolve the issue.  Removing Crafting Tweaks does resolve the issue.  I've attached the log where the latest version of crafting tweaks, integrated tunnels and cyclops core are installed and the problem is exhibited.

[2018-03-23-2.log.gz](https://github.com/CyclopsMC/IntegratedTunnels/files/1841569/2018-03-23-2.log.gz)

**Comment by rubensworks** [comment]
I can't see anything going wrong in your client logs. Could you also share the server logs?

**Comment by rubensworks** [comment]
@kevincook Any progress on the server logs? Closing this otherwise.

**Comment by kevincook** [comment]
I'm sorry @rubensworks I got sidetracked and never made it back to this.  I'm afraid I've lost the instance.  If I run until this again, I'll update you.
