### ISSUE TITLE
Permanent Boolean aspect for Importers/exporters + List iteration?

### ISSUE THREAD

**Issue by bpwhelan** [CyclopsMC/IntegratedTunnels#125]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request
- :question: Question

I think this would be a really nice feature to have, but it is understandable if it is hard to implement. It would be really nice if the boolean slot of an importer/exporter is always "unlocked." An easy example of this, "I want to export items from this list WHILE this inventory is not full." You would put the correct boolean in the boolean slot, and the filter in the export items list slot. Maybe an easier way to do this is to simply add another boolean aspect to turn on/off the importer/exporter. I'm not sure of any way (I've been trying for the past hour or so) to accomplish this at the moment. Could possibly add these to regular interfaces as well, to maybe tell the system to not interface with an inventory based on a boolean, but I'm sure that's more trouble than it's worth.

**Comment by bpwhelan** [comment]
Now that I think about it, there is a workaround, using an intermediate, limited-slot inventory to export items and then export all items on boolean from there....

**Comment by josephcsible** [comment]
The right way to do this is to use the list slot and the "choice" operator. Create a list that equals if(your Boolean condition) then { your list of things to export } else { the empty list }.

**Comment by bpwhelan** [comment]
Ahhh I see! There are so many operators I didn't see that one. Thanks a lot :D

**Comment by bpwhelan** [comment]
Actually, one more question, is there a way to iterate through your list of items? Say the boolean condition is met, and I want to export a stack of each item in the list to theoretically fulfill the boolean condition.

**Comment by josephcsible** [comment]
Do you mean that you want to export one stack of each item?

**Comment by bpwhelan** [comment]
Yeah, I think i know of a way to do it in a limited inventory space (i.e. storage drawer) with export item slot with an increment. But not sure how you would do it in an inventory that has other items as well.

**Comment by josephcsible** [comment]
Filter your list to only include items that aren't in the destination inventory.
