### ISSUE TITLE
Seemingly Random Ceasing of Function

### ISSUE THREAD

**Issue by banggugyangu** [CyclopsMC/IntegratedTunnels#127]
#### Short description:

At seemingly random intervals, transfer of items and/or energy will stop.  Connected machines will run out of buffer power and shut down.  To return to normal operation, a cable must be broken and replaced.

#### Expected behaviour:

Transfer of energy and items continue consistently

#### Actual behaviour:

Items and energy stop transferring randomly.

#### Steps to reproduce the problem:

1. Set up logic cables with appropriate interfaces

2. Wait

3.  Watch devices and monitor power levels/item inventories
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod:   1.12.2-1.5.2
- CyclopsCore:  1.12.2-0.11.4
- Minecraft:  1.12.2
- Forge: 14.23.2.2618

**Comment by rubensworks** [comment]
Could you first try updating to the latest version to see if the problem still occurs for you?

As this in your case includes energy transfer, this has nothing to do with #115, which was only about item transfer.

**Comment by rubensworks** [comment]
@banggugyangu Any update on this? Closing otherwise.
