### ISSUE TITLE
World Fluid Exporter and General Choice Operator issues

### ISSUE THREAD

**Issue by maham** [CyclopsMC/IntegratedTunnels#129]
#### Issue type:

- :bug: Bug

____

#### Short description:

The WFE will not place liquid starlight when it's given from a choice operator.

#### Steps to reproduce the problem:

(I'm referencing variables with line numbers (n) below to shorten it. Hopefully it's readable)

1. Set up a block reader and create a variable from the read block.
2. Create an air block variable
3. Create an equals operator comparing (1) with (2)
4. Create a liquid starlight fluid variable
5. Create a liquid dirt fluid variable (used as a null fluid)
6. Create a choice operator
7. Apply 3 to the choice operator (6) with (3), (4) and (5)
8. When (4) or (7) is inserted into a display it shows the fluid liquid starlight
9. When (4) is inserted into the WFE, liquid starlight is placed
10. When (7) is inserted into the WFE nothing happens

#### Expected behaviour:

The WFE should place a buckets worth of liquid starlight in front of it.
____

#### Versions:

- This mod: 1.5.6
- Minecraft: 1.12.2
- Forge: 14.23.4.2709

**Comment by rubensworks** [comment]
I'll have a look at it, thanks for reporting.

**Comment by rubensworks** [comment]
Fluid transfer has been significantly been rewritten since version 1.6.0.
Could you check if this issue still occurs for you?

**Comment by maham** [comment]
Tested and working. Well done!

**Comment by rubensworks** [comment]
Great, thanks for checking!
