### ISSUE TITLE
Interfaces not Stacking

### ISSUE THREAD

**Issue by RheyvenFox** [CyclopsMC/IntegratedTunnels#13]
When you remove an Interface from a pipe it keeps its ID. This fills your inventory up with non-stackable. You are unable to clear them either by placing them into a crafting slot to clear them or just removing them as normal.

**Comment by rubensworks** [comment]
The ID assignment is intended. But I could indeed implement ID clearing by placing the item in your crafting grid.

**Comment by RheyvenFox** [comment]
Awesome! It just clogs up the inventory rather quickly when you have multiple ones that you remove from an system. Thanks!

**Comment by rubensworks** [comment]
Will be included in next Integrated Dynamics release.
