### ISSUE TITLE
Fluid Exporter Doesn't Respect 'Export Item(s)' Aspect Filters

### ISSUE THREAD

**Issue by ThatGuy435** [CyclopsMC/IntegratedTunnels#130]
#### Issue type:

- :bug: Bug

____

#### Short description:

When more than one fluid is on the network, fluid exporters with variables set in the Export Fluid or Export Fluids do not seem to respect the filter, simply exporting the highest priority Fluid Interface.

#### Steps to reproduce the problem:
Using Integrated Dynamics, Integrated Tunnels, and Immersive Engineering:

1. Put inventories with Water and Biodiesel available, connected to logic net via Fluid Interfaces
2. Decrease priority of Biodiesel interface (I used -10 in my reproduction)
3. Create variable for filtering Biodiesel (either as Fluid or as List:Fluid with 1 entry) on a Fluid Exporter plugged into a Chemthrower Turret
4. Watch as it fills up with water

#### Expected behaviour:

Fluid Exporter should filter according to the Export Fluid(s) aspects - in this case Biodiesel from Immersive Engineering

____

#### Versions:

- Integrated Dynamics 0.11.15
- Integrated Tunnels 1.5.6
- Immersive Engineering 0.12-84
- theOneProbe 1.4.23
- Optifine 1.12.2 HD U E1
- Minecraft: 1.12.2
- Forge: 14.23.4.2745

**Comment by ThatGuy435** [comment]
I also just tested blacklisting (water, in this case) - it doesn't seem to work properly either.

**Comment by rubensworks** [comment]
FYI, this requires some low-level changes in IT. This will be fixed in the next major release, which will consist of a partial rewrite.

**Comment by rubensworks** [comment]
Last week, I released a new version of Integrated Tunnels (1.6.0) that consists of a big rewrite in how things are transferred. This issue is likely to be resolved with this rewrite. I'm auto-closing this issue if no new reports for this come up in the next coming weeks.
