### ISSUE TITLE
Extract Items by Slot Number from Input-Only slots

### ISSUE THREAD

**Issue by Nonsanity** [CyclopsMC/IntegratedTunnels#132]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Some machines have slots dedicated to input items that regular pipes and hoppers don’t pull from. This makes basic automation simple as, most of the time, the player only wants to pull items from the output slots. But with more nuanced automation courtesy of ID and IT, not being restricted by slot I/O settings makes sense.

Example:
In the Roost mod, there is a Chicken Breeder block. It has one input-only slot for seeds and two for chickens. There are three output slots for their offspring. With the Chickens mod, each bird has some stats and breeding can (and usually does) improve them.

I built a system that activates when a new offspring is created. It moves the first input chicken to a chest, moves the second input chicken into the first input slot, then moves the offspring into the second input slot. This rotation has the effect of always breeding the two best (most recent) chickens. However, because the block doesn’t, by default, allow extraction from the input slots, the system doesn’t do anything.

What I’d like to see is that when a specific slot is being targeted, basic I/O restrictions should be ignored, allowing the automation to do what the player could do by hand. Alternatively, this I/O override could be a true/false property in the + button for any of the Inventory Reader modes that it makes sense for. (Slot Item, at the very least.)

**Comment by rubensworks** [comment]
Ignoring I/O restrictions that are put in place by mods doesn't sound like a good idea to me. So I'd prefer not to implement it. (Note that implementing this would require major hacks, so this would likely break many mods)

Wouldn't limiting what goes into the system externally not work in your case?

**Comment by Nonsanity** [comment]
For my particular example, the breeding pair of chickens in the Roost mod stay in the input slots and continue to breed. There’s no automated way to remove or replace them. Normally, inputs use themselves up (like ores in a furnace or bees from Forestry) but some machines have upgrade slots or other slots that, in the normal course of things, are only filled or emptied by the player from the GUI.

I think Steve’s Factory Manager could pull or push to any slot in a machine, but that was back in the 1.7 era. Removing items by pipe shouldn’t be any different (as far as breaking machines) than taking the item out by hand from the GUI.

But if that’s a definite no, I’d understand. (But then I wonder if anyone out there would be interested in taking over Steve’s Factory Manager or one of its forks...)

**Comment by rubensworks** [comment]
I'd suggest you contact the mod author of this Roost mod, and ask if support can be added for automating the input slots. This would be the best solution in any case.
