### ISSUE TITLE
Custom Mining Level World Importer Issues

### ISSUE THREAD

**Issue by pap1723** [CyclopsMC/IntegratedTunnels#133]
#### Issue type:

- :bug: Bug

Using custom mining levels, the World Item Importer cannot mine blocks above a certain level.

#### Steps to reproduce the problem:

1. In Enigmatica 2 Expert, the Livingrock block is set to a mining level of Pickaxe=4. The World Item Importer cannot break the block.

#### Expected behaviour:

The block should be able to be broken.

#### Versions:

- This mod: 1.12.2.0.11.17
- Minecraft: 1.12.2
- Forge: 14.23.4.2760

**Comment by rubensworks** [comment]
Did you already try with any other block? Might be an issue with livingrock.

**Comment by pap1723** [comment]
Yes, it was tried with other blocks as well.

**Comment by rubensworks** [comment]
So what was the verdict, with which blocks did it work, and which didn't?

**Comment by pap1723** [comment]
It didn't work with any blocks that were set above a 3 mining level

**Comment by rubensworks** [comment]
Can you give me a name of any such block? Because I don't know the pack myself, let alone how it is configured.

**Comment by rubensworks** [comment]
So IT does not check harvest levels at all, so the world importer is able to break blocks from any harvest level.

So I assume that your pack contains a mod that listens to the `BlockEvent.HarvestDropsEvent` event (which the world importer _does_ check), and for some reason blocks the fake player from IT.
Unfortunately, there's not much I can do about that from my end. I would suggest that you pinpoint the mod that causes this, and report it to their issue tracker.

**Comment by rubensworks** [comment]
Last week, I released a new version of Integrated Tunnels (1.6.0) that consists of a big rewrite in how things are transferred. This issue is likely to be resolved with this rewrite. I'm auto-closing this issue if no new reports for this come up in the next coming weeks.
