### ISSUE TITLE
World Importer Using Variable Cards from Single Source Cannot All Work At Same Time

### ISSUE THREAD

**Issue by pap1723** [CyclopsMC/IntegratedTunnels#134]
#### Issue type:

- :bug: Bug

____

#### Short description:

I created a setup to automate Livingwood mining for Botania. So I setup 8 World Importers around a Pur Daisy set to import the block when it == Livingwood. Only 5-6 of the World Importers work at the same time.

#### Steps to reproduce the problem:

1. Create a setup of 1 Pure Daisy surrounded by 8 x World Importers
2. Use a single Block Reader to read a block of Livingwood and set that to a variable card.
3. Use the Materializer to set the above variable card to 8 separate Constant Variable Cards
4. Insert the variable cards into the 8 x World Importers connected together with cable and into an Item Interface into a Chest

#### Expected behaviour:

The expected behavior is that each World Importer would be able to mine and import the block when it turns into Livingwood. What actually happens is that only 5-6 of them can function at the same time. The remaining World Importers must wait until there is no block to be read by the working World Importers and then they will process their blocks.

#### Versions:

This mod: 1.12.2.0.11.17
Minecraft: 1.12.2
Forge: 14.23.4.2760

**Comment by rubensworks** [comment]
Did you already try with any other block? Might be an issue with livingrock.

**Comment by tivec** [comment]
I am having this exact issue. I created an Item(Livingwood) card in the Portable Logic Programmer, then I used that card to create 7 copies via a crafting table. I then put these in the World Block Importers. Here is the set up:

![image](https://user-images.githubusercontent.com/717574/45947308-02850e80-bff4-11e8-9a8e-b3a403220709.png)

I have World Block Exporters below the blocks, and World Block Importers on top. 

Once the blocks turn into livingwood (a process in Botania), 5 out of 8 blocks are broken and replaced as can be seen in this image: 

![image](https://user-images.githubusercontent.com/717574/45947394-5b54a700-bff4-11e8-8a36-edd2ea2094d9.png)

The top left corner Importers will not be broken unless I remove the Importer and replace it, putting the card in. It will then import one single block, before it stops functioning.

**Comment by rubensworks** [comment]
@tivec What happens if you try importing any other block? Does it also only import 5 of them?

**Comment by tivec** [comment]
@rubensworks I built a system exporting logs every 60 ticks, and trying to import every tick. With the style of the above build, that worked just fine without hanging or causing any issues.

However, I have made an interesting discovery. If I move the importers to the outside of the three that fails to import in my setup above, it works flawlessly (see image below).

![image](https://user-images.githubusercontent.com/717574/45948453-585bb580-bff8-11e8-8696-6631e56c6796.png)

Something is definitely off here...

**Comment by rubensworks** [comment]
For reference, video of the issue: https://youtu.be/BNUQ5WeGcX4

<blockquote><img src="https://i.ytimg.com/vi/BNUQ5WeGcX4/maxresdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=BNUQ5WeGcX4">Integrated Dynamics Bug?</a></strong></div><div>Possible bug with world importers</div></blockquote>

**Comment by rubensworks** [comment]
Ok, I'm not able to reproduce this myself.
However, I have a strong suspicion as to what may be causing it.
I won't try to explain it here (something with caching), but I'm rewriting significant parts of IT, which will very likely solve this bug as a consequence.
So I'm putting this issue on hold until this rewrite is done.

**Comment by rubensworks** [comment]
For anyone experiencing this issue, doing the following _may_ solve your problem (until I fix the bug).

You may be able to solve the problem by using another aspect. For example, if you'd use the boolean aspect in the block world importer instead of a block-variable importer, then this could fix it.
