### ISSUE TITLE
Exporter malfunctions when I leave the area, with "just lost stack" logspam

### ISSUE THREAD

**Issue by ItsTheKais** [CyclopsMC/IntegratedTunnels#135]
#### Issue type:

- :bug: Bug

____

#### Short description:

Local/single-player world.

A screenshot of the network in question:

![2018-09-28_18 21 09](https://user-images.githubusercontent.com/9879642/46239394-5590f580-c355-11e8-94e1-e20ec1684ffb.png)

The yellow/blue lines in the back are a chunk boundary; the network and the inventories it is attached to span two chunks, both of which are chunkloaded by an Extra Utils 2 chunk loading ward.

The problem exporter is the one on the far right, which is attached to a Cyclic block placer. It is set to output one item every 10 ticks, and the variable that controls it is configured to check the amount of clay in the drawer controller (which is in the other chunk at the far end of the room) and select no item to output to the block placer if there is 2048 or more clay, otherwise select sand (involved operators, in order: Item List Count, Greater Than or Equal, Choice). As long as I stay close enough that the network's chunks are rendered, it works as intended.

If I leave the area, either by teleporting or the old-fashioned way, this exporter will malfunction and begin endlessly pumping out sand. Roughly every two seconds while this is happening, this warning message will be logged:

`[18:29:48] [Server thread/WARN] [Integrated Tunnels]: Just lost stack 1xtile.sand@0 while transfering items, report this to the Integrated Tunnels issue tracker with some details about your setup!`

Neither removing and reinserting the variable card nor changing the amount of clay in storage will "wake up" the exporter. The only way I have found to fix it is by wrenching and replacing any cable or component on the network, which is inconvenient since this network is inside a sealed-off space, not to mention fleetingly temporary as the problem reoccurs each and every time I leave the area.

All other components of this network are behaving themselves; most of them are controlled by the exact same sequence of operators, just comparing against and moving different items.

____

#### Versions:

Minecraft 1.12.2
Forge 14.23.4.2758
Cyclops Core 0.11.10
Integrated Dynamics 0.11.17
Integrated Tunnels 1.5.6

**Comment by rubensworks** [comment]
Thanks for reporting!

I'm currently rewriting major parts of IT, so it is possible that this issue will be fixed after the update, so I'm putting this on hold. Should the issue still persist after updating to the new version (no ETA yet), be sure to ping me here again.

**Comment by rubensworks** [comment]
Last week, I released a new version of Integrated Tunnels (1.6.0) that consists of a big rewrite in how things are transferred. This issue is likely to be resolved with this rewrite. I'm auto-closing this issue if no new reports for this come up in the next coming weeks.
