### ISSUE TITLE
Energy exporter doesn't work properly.

### ISSUE THREAD

**Issue by tksonix** [CyclopsMC/IntegratedTunnels#137]
#### Issue type:

- :bug: Bug

____

#### Short description:

The energy doesn't export energy from interface at all.

#### Steps to reproduce the problem:

1. Connect Energy Exporter to an empty energy cell(used rftools energy cell)
2. Connect Energy Interface to an full energy cell
3. Connect Energy Exporter and Interface with cables
4. Insert a TRUE variable card into energy exporter(which showing a true in the GUI)

#### Expected behaviour:

RF energy flow from full energy cell to empty one
____

#### Versions:

- This mod: 1.5.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by rubensworks** [comment]
That should work though. Have you tried any other energy source, like ID's energy battery? I haven't used the rftools energy cell before, but perhaps you should configure its output sides?

**Comment by tksonix** [comment]
Yeah, I have tried Thermal Expansion's energy cell as well, and I confirm that I've set the sides of the empty cell to input correctly. 
For ID's energy battery, it behaves a bit strange though. It directly connect to the cable and receive energy from the interface, without using any exporters; but if I connect it with an exporter, it doesn't get any energy either.

**Comment by rubensworks** [comment]
@luyiming7 That's weird. Can you reproduce it with just ID installed?

**Comment by rubensworks** [comment]
I can't reproduce this myself, please provide more information. A screenshot/video of your setup with a minimal modset would be great.
