### ISSUE TITLE
Integrated Dynamics x Nuclearcraft interaction bug. 

### ISSUE THREAD

**Issue by Rosethorns** [CyclopsMC/IntegratedTunnels#138]
#### Issue type:

- :bug: Bug

____

#### Short description:

Video walk-through of the bug: []https://www.youtube.com/watch?v=BNUQ5WeGcX4

World Importers will not pull depleted thorium if 2 or more thorium exists on the same network also on world Importers. Seems to affect East and North first.

#### Steps to reproduce the problem:

1. create **3** or more world importers on the same network
2. place a "depleted thorium block" block variable in the pull block slot of each of the importers
3. place thorium on all but one of those importers
4. place depleted thorium on the last importer
5. the depleted thorium should not be retrieved
5a. if the depleted thorium **is** retrieved cycle which importer gets the depleted thorium until the bug appears. 

#### Expected behaviour:

For all world importers on the same network to retrieve the depleted thorium, regardless of the state of the other importers on the network.
____

#### Versions:

- This mod: 1.12.2-1.5.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by rubensworks** [comment]
Thanks for reporting!

This sounds similar to #134, will look into it asap.

**Comment by rubensworks** [comment]
Ok, I'm not able to reproduce this myself.
However, I have a strong suspicion as to what may be causing it.
I won't try to explain it here (something with caching), but I'm rewriting significant parts of IT, which will very likely solve this bug as a consequence.
So I'm putting this issue on hold until this rewrite is done.
