### ISSUE TITLE
Game Crash: Operator ValueTypeOperator$ValueOperator cannot be cast to ValueTypeBoolean$ValueBoolean

### ISSUE THREAD

**Issue by Targren** [CyclopsMC/IntegratedTunnels#139]
#### Issue type:

- :bug: Bug

____

#### Short description:

Similar to #99 but still exists in 1.12.2-1.5.6.

Presumably invalid logic assembly causes game to crash (see details below)

#### Steps to reproduce the problem:

1. Created variable structure ("Label":<desc> for readability)

* "FilterA":  Inventory ReaderA.Items (List<Items>)   
* "FilterB":  Inventory ReaderB.Items (List<Items>)
* "FilterCombine": Concat(FilterA, FilterB)
* "Contains": Operator("List Contains")
* "Doesn't Contain": Negation(Operator(List Contains))
* "Filter Doesn't Contain": Apply("Doesn't Contain", "FilterCombine")

2. Add random items to the inventories connected to InventoryReaders A and B 

3. Put "Filter Doesn't Contain" card in the "Export Items Predicate" slot of an Item Exporter. 

#### Expected behaviour:

Export items from the network that are in neither inventory filled in step 2 (assuming logic is correct), or fail with a red "X" and explanation message (if it is not)

____

#### Versions:

- This mod: 1.12.2-1.5.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

#### Log file:

[Crashlog](https://pastebin.com/L7Mr18TP)

**Comment by rubensworks** [comment]
Hmm, thanks for reporting.

It looks like operators are even harder to implement than they are to use.

**Comment by Targren** [comment]
> It looks like operators are even harder to implement than they are to use.

Does this mean you can see where I screwed up my thinking? I'd love if you'd point it out. I haven't done much FP since college which was... quite some time ago.

**Comment by rubensworks** [comment]
> Does this mean you can see where I screwed up my thinking?

No :-) (not as far as I can see in any case though)
What I meant is that the code that I wrote for implementing the operator system is quite complex, and it's the main source of bugs of this mod.

**Comment by rubensworks** [comment]
Same problem as https://github.com/CyclopsMC/IntegratedDynamics/issues/644 (which has been fixed now), expect a new ID release soon.
