### ISSUE TITLE
RF Transfer

### ISSUE THREAD

**Issue by Rue82** [CyclopsMC/IntegratedTunnels#14]
Not sure if I am just doing it wrong or if it is the version i am using but when i try and transfer RF into a machine from Actually Additions  or the Wireless RF battery from ExtraUtilities2. And I can't seem to transfer RF into the Energy Battery from a EnderIO Capacitor Bank. I am using IntegratedTunnels-1.10.2-1.0.3.jar. If this has been fixed in a more recent update please let me know.  Thanks. Enjoying the mod so far.

**Comment by rubensworks** [comment]
Does this problem only occur with the EnderIO Capacitor Bank, or other RF storage blocks as well?

**Comment by Rue82** [comment]
It can not transfer into the ExtraUtilities2 Wireless battery, and cannot transfer into any Actually addition machines. And cannot accept energy from EnderIO Capacitor Banks but can transfer energy into the Capacitor Bank.  Testing other storage blocks in our pack to see if it has more issues.

**Comment by Rue82** [comment]
Ok so i got it to accept energy from the EnderIO Capacitor but still can not get it to transfer into any Actually Additions machines or the ExtraUtilities2 wireless battery.

**Comment by JFMillerUSA** [comment]
I'm having problems sending RF to an Ender IO Alloy Smelter with Integrated Tunnels.

EnderIO-1.10.2-3.1.164
EnderCore-1.10.2-0.4.1.65-beta
IntegratedTunnels-1.10.2-1.1.0

**Comment by rubensworks** [comment]
Both the AA and Ender IO machines seem to work just fine for me.
![2017-02-15_21 22 09](https://cloud.githubusercontent.com/assets/440384/22993864/db618880-f3c4-11e6-9445-293d79af6e61.png)

Are you sure your setup is correct? Just an importer/exporter is not sufficient as explained on the [curseforge page](https://minecraft.curseforge.com/projects/integrated-tunnels), you'll need at least one functional interface in your network.
Ping me if this is not the cause of the problem.

**Comment by Tylian** [comment]
I'm also having this issue while using the latest(I think?) version of Integrated Dynamics/Tunnels on 1.10.2.

I'm using a very simple setup:
Energy Source -> Importer (with blank variable card) -> Interface -> Machine.

If you place an Actually Additions machine, or the Wireless RF Battery from Extra Utils 2 at the end of the chain, they don't accept energy and remain empty.

Additionally, Capacitor Banks *do* work as an energy source, but they ignore the transfer rate on the exporter and instead just go full throttle. Which is better than "not working" but I'm unsure if that's the intended functionality.

Actually Additions 1.10.2-r105
Extra Utilities 2 1.3.3
Ender IO 1.10.2-3.1.179
Integrated Dynamics 1.10.2-0.6.11
Integrated Tunnels 1.10.2-1.1.1
Cyclops Core 1.9.4-0.10.0


Any ideas?

**Comment by rubensworks** [comment]
Are you sure those machines allow energy extraction? Could you post a picture?
The capacitor bank probably works because it is pushing energy itself.

Note to self: importers should limit the rate when external machines are pushing energy: https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.10/src/main/java/org/cyclops/integratedtunnels/part/PartStateEnergy.java

**Comment by Tylian** [comment]
It's specifically trying to get Integrated Tunnels to insert energy into the machines.

http://imgur.com/a/XwcfW

**Comment by rubensworks** [comment]
@Tylian I'll look into it.

**Comment by rubensworks** [comment]
Next release will contain a fix so that interfaces will always work with either RF, FE or Tesla.
