### ISSUE TITLE
Storage Drawers with "Creative Vending Upgrade" report drawer contents to Item Interfaces, but cannot be extracted from

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedTunnels#140]
#### Issue type:

- :bug: Bug

____

#### Short description:

An inconsistency between what an Item Interface reports to the network and what can actually be exported from the attached inventory. Specifically, with a Storage Drawers drawer that has been upgraded with a "Creative Vending Upgrade".

Item Interfaces will report to Extractors that there is MAXINT of every item in the creative drawer to extract, though absolutely no item transport mod--not even Integrated Tunnels--is capable of actually extracting these items.

#### Steps to reproduce the problem:

1. Build network with
 - 1x Storage Drawer
 - 1x Creative Vending Upgrade (applied to Storage Drawer)
 - 1x Any item (placed into Storage Drawer)
 - Item Interface (on Storage Drawer)
 - Item Exporter (on another inventory)
2. Using TOP, examine Item Exporter. It will report that there is MAXINT of the item available, as if the Exporter contained that in its inventory.
3. Attempt to extract all items using the Item Exporter. Nothing will move.

#### Expected behaviour:

As no item transportation mods, including Tunnels, are capable of moving items out of a Storage Drawer upgraded with a "Creative Vending Upgrade", the expected behavior is that the Item Exporter should not contain a reference to the Storage Drawer's contents.

#### Versions
Storage Drawers: 1.12.2-5.3.7
Integrated Tunnels: 1.12.2-1.5.6

-----

This is largely an issue on the Storage Drawers side. I'll check for a Storage Drawers update to see if it has been resolved, but meanwhile the issue still remains of an Item Interface and Exporter incorrectly reporting that items are available when they cannot be transferred.

**Comment by rubensworks** [comment]
> though absolutely no item transport mod--not even Integrated Tunnels--is capable of actually extracting these items

> This is largely an issue on the Storage Drawers side. I'll check for a Storage Drawers update to see if it has been resolved

Can you report back here if you have updates. Will put this issue on hold until then.

**Comment by GreyMario** [comment]
I checked in on the Storage Drawers github and found [a wide open issue](https://github.com/jaquadro/StorageDrawers/issues/583#issue-266235824) on this very subject that's existed since October 2017.

...With no developer commentary. Just a pile of users complaining that they can't use creative drawers as an endless supply of items in pipes.


Okay, I lied. There's one developer comment. Asking what version the issue is appearing in. Absolutely no followup, as the issue clearly still exists. No mention in commits, no mention in pulls.

**Comment by rubensworks** [comment]
I see, thanks for linking the issue!

**Comment by GreyMario** [comment]
An update was made to Storage Drawers which claims to resolve this issue.

If it does, then the only remaining issue on this front is that Item Exporters can report that they have available inventory attached to Interfaces when they are incapable of actually exporting from those Interfaces.

**Comment by rubensworks** [comment]
> Item Exporters can report that they have available inventory attached to Interfaces when they are incapable of actually exporting from those Interfaces.

I'm not sure what you mean by this though. What do you mean with this 'reporting'?

**Comment by GreyMario** [comment]
Build a network which exposes the issue in an affected Storage Drawers version, then use The One Probe to inspect the Item Exporter's "inventory". The tooltip indicates that the "inventory" of the Item Exporter "contains" the item in the creative vending Storage Drawer, but no item can actually be exported.

[Album of screenshots, because pictures, words, et cetera.](https://imgur.com/a/9mUcYDA)

The issue then becomes that items are "reported" as available (as shown by the tooltip) but cannot actually be moved from the interfaced inventory, causing a disparity in what the user is told they can do and what the user can actually do.

 I _assume_ The One Probe doesn't go out of its way to explore Integrated networks and that this is an intentional aspect of how Tunnels exporters are designed.

**Comment by rubensworks** [comment]
I don't see how this is an issue in IT though. I thought this (the non-extraction issue) was fixed in Storage Drawers?

**Comment by rubensworks** [comment]
I see that https://github.com/jaquadro/StorageDrawers/issues/583 has been closed. @GreyMario could you confirm that this works properly for you now?

**Comment by GreyMario** [comment]
I did a dumb and tried to test this without updating Storage Drawers.

After doing the smart and updating, can confirm that [creative vend drawers work](https://puu.sh/CAqiy.png).

**Comment by rubensworks** [comment]
Great, thanks for checking!
