### ISSUE TITLE
Fluid Importers/Exporters not respecting Exact Amount

### ISSUE THREAD

**Issue by ItsTheKais** [CyclopsMC/IntegratedTunnels#145]
#### Issue type:
* :bug: Bug
____
#### Short description:
Fluid Importers and Exporters are ignoring the Exact Amount setting and blindly moving fluids regardless of the amounts available to be moved, resulting in clogged casting basins.

#### Steps to reproduce the problem:
1. Set up a network consisting either of a Fluid Interface on a source tank and a Fluid Exporter on a destination tank, or a Fluid Importer on a source tank and a Fluid Interface on a destination tank
2. Configure the Import/Export All Fluids aspect on the relevant part to use a certain fluid amount and set Exact Match to true, then enable that aspect
3. Place an amount of fluid lower than the set number into the source tank

#### Expected behaviour:
That the fluid stays where it is until enough is added to the source tank to fulfill the Exact Amount condition
____
#### Versions:
* Integrated Dynamics 1.0.1
* Integrated Tunnels 1.6.1
* Integrated Terminals 1.0.1
* Integrated Crafting 1.0.0
* Cyclops Core 1.0.1
* Common Capabilities 2.0.0
* Forge 14.23.5 2796
* Minecraft 1.12.2

**Comment by rubensworks** [comment]
Hmm, I did test this extensively quite recently though... This must be a recent regression then.

**Comment by xoxfaby** [comment]
@rubensworks in a previous version I noticed that, basically, the predicate logic only considered the transfer rate and not the amount in the tank, I wonder if this issue might stem from the same the same root cause?

**Comment by rubensworks** [comment]
@xoxfaby Probably not, as all of this has been rewritten quite extensively in the latest update. I suspect it's something small though.
