### ISSUE TITLE
Server crash and network broken after placing Energy Interface

### ISSUE THREAD

**Issue by xoxfaby** [CyclopsMC/IntegratedTunnels#148]
#### Issue type:

- :bug: Bug

____

#### Short description:

After placing an Energy Interface next to a DE Infuser ( not sure if related ), the server hard crashed and the network got completely screwed up. After restarting the server the network wasn't work, aiming at energy interfaces to show the energy in Waila spams errors in the server log like crazy, some stuff is being transferred, other stuff isn't, random exporters and importers are erroring. placing and removing parts of the network throws a bunch of errors too. 

#### Steps to reproduce the problem:

Literally just placed the Energy Interface next to the Infuser. I tried to see if just those things in a fresh world would cause any issues and they didn't. Can't reproduce on my server since the network seems completely broken. 
____

#### Expected behaviour:

Things don't go to shit. 
____

#### Versions:

- This mod: 1,6.2
- Minecraft: 1.12.2
- Forge:  14.23.5.2781

#### Log file:

There were so many errors that I just included every log I found from the time it crashed and after. The crash should've happened shortly before 4:04 server time and after is all rebooting and errors. 

http://shr.cx/logs.7z

**Comment by rubensworks** [comment]
This seems to be the same problem as CyclopsMC/IntegratedDynamics#680, will push a fix.

**Comment by rubensworks** [comment]
@xoxfaby Could you try the latest ID dev build (1269) to see if this fixes your problem?

You may need to reset your network by breaking/replacing a cable because of the earlier crash.

**Comment by xoxfaby** [comment]
https://gist.github.com/65c5043928daccfdbf0e349bce61d492

<blockquote><img src="https://avatars0.githubusercontent.com/u/998173?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/xoxfaby/65c5043928daccfdbf0e349bce61d492">cs6p.txt</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by xoxfaby** [comment]
https://gist.github.com/xoxfaby/b2e250cb12ff0d41ad87adae3830e00f

<blockquote><img src="https://avatars0.githubusercontent.com/u/998173?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/xoxfaby/b2e250cb12ff0d41ad87adae3830e00f">HBak.txt</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by rubensworks** [comment]
@xoxfaby So was this before, after or during your network reset?

**Comment by xoxfaby** [comment]
During. And after.

**Comment by rubensworks** [comment]
Ah, interesting. This is in fact a totally different problem, but also related to chunk loading.

Pushed a new ID build (1271) that should fix the error.

Could you let me know how that work for you @xoxfaby?

**Comment by xoxfaby** [comment]
Looks like your fix worked! If something does pop up I will update, but as soon as I placed a new cable, everything sprung back into action.

**Comment by rubensworks** [comment]
Great! Thanks for testing. I'll include these fixes in the next release.
