### ISSUE TITLE
"Exact Amount" ignores target inventory.

### ISSUE THREAD

**Issue by xoxfaby** [CyclopsMC/IntegratedTunnels#149]
#### Issue type:

- :bug: Bug

____

#### Short description:

If you set the item transfer rate to "Exact Amount", it will move items even if the target inventory can't take the actual amount. 

#### Steps to reproduce the problem:

1. Set Exact Amount
1. Have source inventory with amount available and target inventory with less space than the amount, it will move the partial amount to fill the inventory. 

#### Expected behaviour:

It doesn't move anything since it can't move the exact amount. 
____

#### Versions:

- This mod: 1.6.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2781

**Comment by rubensworks** [comment]
Note to self: add an additional check post-simulated-transfer.

**Comment by rubensworks** [comment]
Oof, this one took quite a bit of work to figure out all edge-cases when testing.
