### ISSUE TITLE
interface priority

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedTunnels#15]
when setting an item interface priority and clicking save the interface does not store the priority.

Confirmed this behaviour by inspecting the nbt data. It also appears that the frequency is not stored either.

**Comment by rubensworks** [comment]
Sounds similar to CyclopsMC/IntegratedDynamics#64.

**Comment by rubensworks** [comment]
Will be fixed in the new Integrated Dynamics version.
