### ISSUE TITLE
Progression needs a rehaul. Gating behind ender dragon is bleh

### ISSUE THREAD

**Issue by NolanSyKinsley** [CyclopsMC/IntegratedTunnels#151]
This is just a gripe about the progression in this mod, and the fact that the world importer/exporters  are gated behind the ender dragon kill. Just... Seriously? The ender dragon is late game in most mod packs, and can be extremely hard to get to in others. People will have their bases 90% built and their engines churning well before ever killing the ender dragon, so when they unlock the devices that would be useful to them they have long since used other means to do so, and are not going to rebuild their base to incorporate this new tech.

I understand it is powerful, but make it expensive, or take a few extra steps to make, not gated. People need access to these devices WHILE they are building their base to reach end game, not after they have already gotten there. When new players want to use your mod to simply pick up and place items in the world based on NBT data, step 1 should not be "beat the game", that's all I am saying. Your tech tree goes from level 1, crystallized tree sap and berries, to level 2, BEAT THE GAME!!!.... It is a huge jump, I would understand using blaze rods and powder in place, that would be a reasonable tech progression jump from tree sap and berries.

**Comment by rubensworks** [comment]
Perhaps something for 1.13, I don't want to break existing autocrafting setups.

In any case, feel free to change the recipes in your own world as you see fit.

**Comment by xoxfaby** [comment]
>The ender dragon is late game in most **mod packs**, and can be extremely hard to get to in others.

If mod packs mess with progression and gating, they should change the recipes to accomodate for that.

**Comment by NolanSyKinsley** [comment]
> > The ender dragon is late game in most **mod packs**, and can be extremely hard to get to in others.
> 
> If mod packs mess with progression and gating, they should change the recipes to accomodate for that.

Then this mod should base itself as a standalone and understand that there is very little to no content post ender dragon, because it does not add any, so gating it's content past the literal end of the game makes zero sense. Post wither items are supposed to be OP, post ender dragon items are supposed to be game breakingly OP, these level 2 items aren't even post wither content, they should be post-nether pre-wither for their capabilities and how complex they are to use. If you gate them past what is normally one of the last events in a player's playthrough, they will have little time to experience, use, and learn about these items and how they can be integrated into their base. 

Right now a way to fix this progression hitch, without breaking autocrafting, you could give a way for the player to obtain a chorus fruit pre-ender dragon kill, like how extra utilities gives the ender-lily to get pearls, and ex-nihilo allows us to get end stone. You could still require the use of say, blaze rods, to gate it to post-nether players.

**Comment by xoxfaby** [comment]
I don't know which mod packs you are talking about that make the ender dragon more difficult to fight. Generally with modded weapons and tools and armor it becomes much easier to fight the dragon earlier, making the ender dragon much less of a gate than it is in vanilla. I reiterate, if some niche modpack does make the ender dragon hard to beat, the author can change the recipe.

**Comment by NolanSyKinsley** [comment]
> I don't know which mod packs you are talking about that make the ender dragon more difficult to fight. Generally with modded weapons and tools and armor it becomes much easier to fight the dragon earlier, making the ender dragon much less of a gate than it is in vanilla. I reiterate, if some niche modpack does make the ender dragon hard to beat, the author can change the recipe.


As I said, you should consider this mod a standalone, the ender dragon is literally end game, you beat the dragon, go to the end cities, where the only source of chorus fruit is, and then when you come back it is literally roll credits, game over. With this mod and vanilla, there is literally nothing past the end cities, that is the end of progression, the end of content. People's bases have been built long ago, they are not going to tear down their base to then use this mod where it can be used... This mod's level 1 tech is crystallized tree juice and berries, level 2 should not come after the end credits have rolled, there is a HUGE disparity here. 

 I think I laid out a fairly robust argument that this mod's second tech level should be post nether, pre wither. It simply is not OP to the point of requiring nether stars, and not nearly game breaking enough to be gated post ender dragon by any means.

**Comment by xoxfaby** [comment]
Unlimited, cross dimensional power, fluid and item transfer is about as OP as it gets when it comes to piping mods. And I don't think some weird scenario where someone is only using ID/IT and nothing else is a good argument. ID/IT shines in big mod pack as a supportive mods to automate them.

requiring only getting to the nether is way too cheap.

**Comment by xoxfaby** [comment]
And I completely disagree with the premise that killing the ender dragon is "end of game, roll credits", especially when it comes to modded minecraft.

**Comment by rubensworks** [comment]
It's interesting to hear both sides of the argument here. I'll definitely take both into account when updating to 1.13/1.14.

**Comment by Adirelle** [comment]
The fact that the first tier of ID only requires a vegetal resource makes it very accessible and cheap, compared to other mods that requires a lot of ores. Note that I like the idea though: it makes ID a bit unique. I suppose @rubensworks have selected chorus fruits because it is a plant as well. However the gap to the next tier seems quite big. If you look at other mods providing this kind of features, like Mekanism's Quantum Entangloporter or the old TE's Tesseract, you will see they requires (a lot of) Ender Pearl and/or Blaze Rods and/or Diamonds, but little to no post-dragon resources.

Another point: ID does not impose maximum rate on input/output. They are programmable features more than constraints. In other mods, the maximum rate is often used as a way to provide a progression. Maybe this is a bit artificial though, and there might be better ways to do this.

BTW, @xoxfaby, I am playing with no "official" modpacks and the original recipes from all mods, and I feel there is little to do after defeating the Ender Dragon. I was using Quantum Entangloporters until I could switch to ID's omni-directionnal connectors.
