### ISSUE TITLE
interface filtering

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTunnels#152]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

basically, interfaces should have inbound and outbound rules similar to exporters and importers, but on a passive basis. instead of actively pushing and pulling these filters, they will simply designate what is to be imported and exported from the interfaced machine/storage. for example, you could make a stacksize = 1 predicate in an interface as an inbound rule for a tool-only chest.

**Comment by rubensworks** [comment]
This can be achieved with this feature request: #98.
