### ISSUE TITLE
Fluid Exporters not obeying "exact amount = false", but only sometimes. (Mod Interaction?)

### ISSUE THREAD

**Issue by Targren** [CyclopsMC/IntegratedTunnels#153]
#### Issue type:

- :bug: Bug  (minor)

____

#### Short description:

With certain containers (In this case, Astral Sorcery Lightwells), fluid exporters don't move fluids until the container has more than the "Fluid Transfer Rate" worth of fluid. 

#### Steps to reproduce the problem:

1. Place a fluid interface (default settings) on the bottom of a Lightwell
2. Place a fluid exporter (default settings) onto another fluid container (tested with Openblocks tank, Blood Magic "Blood Tank", Thermal "Portable Tank"). 
3. Connect interfaces with logic cable, and place blank variable card into "Export all fluids" slot of exporter. 
4. Place "Resonating Gem(AS)" in Lightwell. 
5. Fluid is not transferred into tank until 1000mb has built up in the lightwell (if unlucky, may require a 2nd gem)
6. Change "Fluid Transfer Rate" to 1. Fluid begins to flow nearly as fast as it is generated

Note that if you reverse the setup, putting the Fluid Interface on the tank and a fluid importer on the bottom of the lightwell, the fluid will be imported immediately. 

It might be a mod interaction issue, though, because replacing the Lightwell with a TiC smeltery drain as the "source" makes the network behave identically to the importer.  

#### Expected behaviour:

If "Exact Amount" is specified as "false" (as it is by default), the exporter shouldn't wait for the source to build up to that amount. 

____

#### Versions:

- This mod: 1.12.2-1.6.2
- Minecraft: 1.12.2
- Forge: 

Also Mentioned:
- Astral Sorcery 1.10.10

Modpack: Enigmatica 2 (Non-Expert) 1.58

**Comment by rubensworks** [comment]
@Targren What happens if you just any other kind of tank instead of the Lightwell? It may indeed be just a property of that block. Can you export with smaller rates using other types fluid transfer pipes?

**Comment by Targren** [comment]
It looks like it is the lightwell. Going from a Seared Gauge->Portable tank with the same settings and 288mb of fluid worked as expected.

**Comment by rubensworks** [comment]
Ok, thanks for checking @Targren! Could you report this to the Astral Sorcery issue tracker then? (it may very well be intended functionality though) (be sure to link back to this issue here)

**Comment by Targren** [comment]
Sure thing. 

Oh, it might also be worth noting, just for the record, that it also seems to push the contents of the lightwell through the exporter when the stone in the Lightwell breaks, too.

**Comment by GreyMario** [comment]
I actually want to say I've seen this off-beat behavior in a couple of other blocks here and there, but I can't remember what it was. Cyclic's Magma Anvil, perhaps? I'll keep an eye out and see if we can piece together a common cause.

**Comment by Targren** [comment]
I just tested with Astral Sorcery 1.10.17 and Integrated Dynamics/Tunnels 1.0.11/1.6.8 and it looks like it's working as expected now, so whatever was causing it doesn't seem to be around in the latest versions.
