### ISSUE TITLE
Player Simulator wont apply mekamism upgrades

### ISSUE THREAD

**Issue by blinkinglight** [CyclopsMC/IntegratedTunnels#159]
enigmatica 2 expert IT 1.12.2-1.6.7 https://www.youtube.com/watch?v=5M83nWwpoYU

**Comment by rubensworks** [comment]
Please use the proper issue template.

**Comment by blinkinglight** [comment]
____

#### Short description:



#### Steps to reproduce the problem:

(seed video for details)
make variable card with "list" of mekanism upgrades "item" tier 1, tier 2 tier 3. put into slot "click items" attach chest with item interface. (see video for configuration). place osmium compressor and ... nothings happens. (tried rr on/off and other settings - nothing )

#### Expected behaviour:

i think player simulator should instantly apply clicks in same order as variable card list items 
____

#### Versions:



- This mod: 1.6.7
- Minecraft: 1.12.2 
- Forge: 14.23.5.2781

#### Log file:
-

**Comment by rubensworks** [comment]
> i think player simulator should instantly apply clicks in same order as variable card list items

Ah, no, that is not the intended behaviour.

The only thing that the list will do, is specify a whitelist. Each slot will be checked for this whitelist separately. For example, if any of the items can be found in slot 0 of a chest, then that item will be picked, regardless of its position in the list.

So you are responsible yourself for making sure the items in the chest are in the correct order.

The behaviour you want is possible in theory, but is more likely to produce more server lag, so I'm hesitant to implementing that.

**Comment by blinkinglight** [comment]
i thought, that it will iterate over card list and then checks inventory and if yes then tries to apply it.

**Comment by blinkinglight** [comment]
as you can see in video, i placed update into chest in same order as card list but they wont apply till i pickup some item in chest and puttin it back. looks like it starts working on strande chest event. not then they are placed but then they are taked.

**Comment by blinkinglight** [comment]
if i place items manualy in right order from chest slot 1 not 0 - it works because it moves 1 slot item to slot 0

**Comment by rubensworks** [comment]
I'm having a really hard time understanding what you mean. In the video, things seem to work as intended.
