### ISSUE TITLE
CurseForge links to Integrated Dynamics are Bad/Broken.

### ISSUE THREAD

**Issue by Claycorp** [CyclopsMC/IntegratedTunnels#16]
First link uses a redirect URL and not the Curseforge URL. Thus making people think they are leaving curseforge when they are not.
Second Link is an invalid link to nothing.

You might want to double check your links everywhere if they are copy pasted.

**Comment by rubensworks** [comment]
Yeah, for some reason Curseforge likes to change their URL strategy without adding proper redirects...

**Comment by rubensworks** [comment]
Fixed on CurseForge
