### ISSUE TITLE
Card configuration causing crash, ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JoelNordh** [CyclopsMC/IntegratedTunnels#160]
I'm playing sky factory 4 with integrated dynamics and I get a crash when trying to follow a guide on reddit 
https://www.reddit.com/r/feedthebeast/comments/a0uacf/integrated_dynamics_filtering_by_name/
When doing as he suggests and doing the last step the game crashes. 

I'm not totally sure I've done the list correctly but anyhow the game shouldn't crash. 
[crash-2019-04-22_13.05.32-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/3103174/crash-2019-04-22_13.05.32-server.txt)

I attach the crash report,

**Comment by rubensworks** [comment]
Thanks for reporting, but could you please follow the issue template, I need the mod versions.

**Comment by JoelNordh** [comment]
Hi,
I'm sorry I didn't see the template. Here is the template information 



#### Issue type:

- :bug: Bug

____

#### Short description:

A certain configuration causes the game to crash 

#### Steps to reproduce the problem:

Follow the instructions in the answer in this link https://www.reddit.com/r/feedthebeast/comments/a0uacf/integrated_dynamics_filtering_by_name/
When putting in the card in an importer the game freezes then crashes. 
It has time to show that the configuration is correct with the green confirmation symbol

#### Expected behaviour:

Even if the configuration is wrong the game shouldn't crash 

____

#### Versions:

- This mod: 1.12.2-1.0.8
- Minecraft: 1.12.2
- Forge modloader: 8.0.99.99 

#### Log file:

The crash file should be in the original message. 


<blockquote><img src="https://www.redditstatic.com/new-icon.png" width="48" align="right"><div><img src="//www.redditstatic.com/desktop2x/img/favicon/favicon-16x16.png" height="14"> reddit</div><div><strong><a href="https://www.reddit.com/r/feedthebeast/comments/a0uacf/integrated_dynamics_filtering_by_name/">Integrated dynamics: filtering by name</a></strong></div><div>Hi. I am playing the "not the bees" pack right now. I wanted to use integrated dynamics/integrated tunnel to send all my produced bees and comb to...</div></blockquote>
