### ISSUE TITLE
Crash when inserting items into Real Filing Cabinet using Item Interfaces and Importers

### ISSUE THREAD

**Issue by rasm945i** [CyclopsMC/IntegratedTunnels#162]
#### Issue type:

- :bug: Bug

____

#### Short description:

I had made a really detailed description, but I accidentally closed the tab.... I didn't put as much effort into this one, sorry.
The Modpack I'm using is SkyFactory 4.0.5.
My server crashes when Item Interfaces insert items into a Real Filing Cabinet.
I also noticed that Sticks and Oak Logs wasn't pulled, even tho I have a Filing Cabinet for it.

![2019-05-18_00 14 18](https://user-images.githubusercontent.com/30770655/57959197-e592a800-7902-11e9-8868-533ec18e35cf.png)
![2019-05-18_00 13 46](https://user-images.githubusercontent.com/30770655/57959202-e9bec580-7902-11e9-8d19-3d48cc982f48.png)
![2019-05-18_00 10 18](https://user-images.githubusercontent.com/30770655/57959207-f511f100-7902-11e9-8bd6-794f665d7b05.png)
![2019-05-18_00 10 08](https://user-images.githubusercontent.com/30770655/57959216-fba06880-7902-11e9-8e06-5f9e9293781a.png)
![2019-05-18_00 10 05](https://user-images.githubusercontent.com/30770655/57959220-ffcc8600-7902-11e9-987e-e090973150e9.png)
![2019-05-18_00 09 58](https://user-images.githubusercontent.com/30770655/57959224-078c2a80-7903-11e9-91c9-abd9593107ea.png)

#### Steps to reproduce the problem:

1. Make a Hopping Bonsai farm inside a Compact Machine
2. Use Importers and Logic Cables to route items out of the Compact Machine via a Tunnel (from Compact Machines)
3. On the outside, have Interfaces attached to Real Filing Cabinets, which are set up to accept the resources farmed.
4. Wait for the crash to happen.

#### Expected behaviour:

Having an awesome storage system using Real Filing Cabinets for storage and Integrated Tunnels for item transfer.

____

#### Versions:

- This mod: 1.12.2-1.6.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2831

Other mod versions that may be useful:
- Integrated Dynamics: 1.12.2-1.0.8
- Rustic: 1.0.15
- Compact Machines 3: 1.12.2-3.0.17-b267
- Bonsai Trees: 1.1.2-b144

#### Log file:

https://pastebin.com/J8pVdeB6

**Comment by rubensworks** [comment]
This seems to be an issue with Real Filing Cabinet:

> java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
    at com.bafomdad.realfilingcabinet.inventory.InventoryRFC.insertItem(InventoryRFC.java:42)

Could you report it over on their issue tracker?

**Comment by rasm945i** [comment]
Yes sir :)
