### ISSUE TITLE
Items exposed by Exporters for use in external item handlers always channel 0 despite Exporter's channel

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedTunnels#163]
#### Issue type:

- :bug: Bug

____

#### Short description:

When an Item Exporter is used to expose inventory for another device to take over (other mod pipes, reading the contents of a network, et cetera), it always exposes channel 0, and not the channel selected in the Item Exporter. If allowed to export by itself, will correctly obey selected channel.

#### Sample build to reproduce:

![](https://i.imgur.com/lwxsrkF.png)

In short:

1. Set an Item Exporter to export from any channel other than 0, but don't target a valid destination.
2. Attach an inventory using an Item Interface on channel 0.
3. Use an Inventory Reader to read the items being exposed by the Exporter.
4. Try pulling items from the Item Exporter using an Item Importer or a sneaky mod pipe of some sort.

#### Expected behaviour:

The Item Exporter should expose to other handlers the combined inventories of all interfaces on the selected channel.

____

#### Versions:

- InDy: `1.12.2-1.0.13`
- Tunnels: `1.12.2-1.6.8`
- Minecraft: `1.12.2`
- Forge: `14.23.5.2831`

**Comment by rubensworks** [comment]
This is not really a bug, but just not yet a feature :-)

Related to #75, which I hope to implement for at some point.

**Comment by GreyMario** [comment]
Exposing the wrong channel isn't a bug? That... _can't_ be right. Regardless, it's definitely a problem, since it shuts down logically reading the contents of a non-zero channel.

**Comment by rubensworks** [comment]
This should have been fixed in more recent versions.
