### ISSUE TITLE
Dublication / Exchange Bug with AE2

### ISSUE THREAD

**Issue by troneleck** [CyclopsMC/IntegratedTunnels#166]
#### Issue type:

- :bug: Bug

____

#### Short description:

AE2 Storageinterface to Tunnel Storageinterface ends as Item Exchanger.

#### Steps to reproduce the problem:

1. AE2 Contreoller + terminal + power
2. AE2 cable and on his end a storage interface
3. a chest 1 block away from the interface
4. Tunnel interface on chest
5. Integrated d. cable on chest interface
6. put unwantet items in the chest (like gobble)
7. unwantet items have to be on first positions
8. put a item to "Exchange" in the chest
9. exchanged item(s) have to be after the unwantet items in the chest (64 cobble, 64 cobble,1 Diamant)
10. connect tunnel storageinterface to AE2 storageinterface (this conncetion must be the last one)

11. use the AE2 terminal and grap the diamants
12. with 64 cobble + 1 diamant you will end with 65 diamants
13. the chest will be emty.
14. to restart this process you have to disconnect the  Tunnel interface to the AE2 interface...fill up the chest..connect...repeat

#### Expected behaviour:

____

#### Versions:

- This mod: 1.12.2-1.6.8
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2836

**Comment by rubensworks** [comment]
@troneleck I'm sorry, but I don't really understand this issue.

Is this an IT issue? Or a mod compatibility issue?
If the latter, why do you think IT is causing the problem?

Could you perhaps share a video of the problem?

**Comment by troneleck** [comment]
![Basic-setup](https://user-images.githubusercontent.com/17239456/59131226-15692480-8972-11e9-954a-d00994c08efd.png)

The basic setup.


![Basic-setup-items-inside-chest](https://user-images.githubusercontent.com/17239456/59131240-1f8b2300-8972-11e9-9ac4-42cde4652533.png)

Items inside the chest.

![Last-connection](https://user-images.githubusercontent.com/17239456/59131258-2ade4e80-8972-11e9-8aaa-add84f857f19.png)

Make connection with AE2 storage interface and Tunnel item interface.

![looks-normal](https://user-images.githubusercontent.com/17239456/59131287-477a8680-8972-11e9-8bb6-6415f7938cac.png)

It looks normal.

![need-more-diamonds](https://user-images.githubusercontent.com/17239456/59131307-52351b80-8972-11e9-85bf-47eb84b9f0fd.png)

But i can grap more diamonds.


![stone-to-diamond](https://user-images.githubusercontent.com/17239456/59131349-742e9e00-8972-11e9-8ca8-1ec0d9bd59a6.png)

Some cobble is gone but the diamond is still there.


![no-more-diamonds](https://user-images.githubusercontent.com/17239456/59131389-90323f80-8972-11e9-8456-99dec097ae3b.png)

AE2 still shows 128 cobble an 1 diamond but i cant take any more items.


![emty-chest](https://user-images.githubusercontent.com/17239456/59131422-a8a25a00-8972-11e9-9e93-f9b7420433f6.png)


The chest is now emty and the stones are now diamonds.
