### ISSUE TITLE
Refined Storage interface doesn't export anymore in IT items exporters

### ISSUE THREAD

**Issue by lepouletsuisse** [CyclopsMC/IntegratedTunnels#168]
#### Issue type:

- :bug: Bug

____

#### Short description:

According to Integrated Tunnels (IT) Mod Spotlight, it is possible to use a Refined Storage (RS) interface to import/export items in our IT system by adding a IT item interface on a RS interface. While testing it, it seems there is no problem to import items from an IT item importer to the RS system but it seems impossible to export items from our RS system to a chest (for exemple) with a IT item exporter.

#### Steps to reproduce the problem:

1. Build a simple RS system and add some ressource inside.
2. Build a simple structure like the following image:
![image](https://user-images.githubusercontent.com/8804334/59301965-24faad00-8c93-11e9-83c2-34d8eb9faa25.png)
3. Add a variable in the exporter for "Export All Items"

#### Expected behaviour:

There should be the content of our RS system that goes in the chest but nothing is coming.

____

#### Versions:

- This mod: IntegratedTunnels-1.12.2-1.6.9
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2838

**Comment by rubensworks** [comment]
This is actually due to a change in RS, placing a hopper underneath the RS interface won't work anymore either. So if you want this to work again, I would suggest opening an issue in RS. I have no intention to add specific integration for RS in IT.

Thanks for the issue in any case!

**Comment by lepouletsuisse** [comment]
Oh ok, i will open an issue on their side.

Thank you for your answer!
