### ISSUE TITLE
Server crash on chunk unload.

### ISSUE THREAD

**Issue by Claycorp** [CyclopsMC/IntegratedTunnels#17]
NPE in console: http://pastebin.com/TczuUF0c
Crash log that follows: http://pastebin.com/A1LjP7ee

**Comment by BiatuAutMiahn** [comment]
I used to get this alot too, my solution was to increase the view distance in the server.properties to double the view distance of my client. ie: ServerVD: 32 if ClientVD: 16. Afterwards I was able to go all over the map without crash

**Comment by Claycorp** [comment]
That might work for small servers of a handful of people but i'm not going to let 20+ people onto a server with a view distance of 32.... It's not a viable solution to the issue.

**Comment by rubensworks** [comment]
This issue is next on my todo-list, so this solution should only be temporary.

**Comment by BiatuAutMiahn** [comment]
@Claycorp agreed

**Comment by BiatuAutMiahn** [comment]
I noticed this mostly when I was trying to move too fast, such as running, or using a boat

**Comment by BiatuAutMiahn** [comment]
Could be caused by a network extending into multiple chunks.

**Comment by rubensworks** [comment]
@BiatuAutMiahn Any information on what the network that causes the crash looks like could help. I/f you have some pictures with chunk boundaries, that'd be great.

**Comment by Claycorp** [comment]
Here's a screenshot of what we had that crashed. Sadly there's no chunk boundaries but it spans multiple chunks and it never would fail in the same spot. http://imgur.com/DaARbhG

**Comment by BiatuAutMiahn** [comment]
I can confirm that #20 is caused by chunks being unloaded. A few times now id dump items into my inventory system, and leave (about 1024+ blocks away) upon coming back the network is locked up.

Edit: Wrench is the only temporary fix.

**Comment by BiatuAutMiahn** [comment]
@Claycorp, what are those blocks with the red lines?

**Comment by Claycorp** [comment]
Actually additions laser power relays.

**Comment by Brend-Smits** [comment]
Can confirm that my server is having these crashes as well, Sky Factory 3 modpack.

**Comment by rubensworks** [comment]
I've managed to reproduce it myself as well, fixing it as we speak.

**Comment by rubensworks** [comment]
Will be fixed with the next Integrated Dynamics update.

**Comment by Brend-Smits** [comment]
Still happening with the new Integrated Dynamics: https://hastebin.com/oteqomubes.pas

**Comment by rubensworks** [comment]
@Rubbertjuh Any other details you can give me? Does this also occur on chunks unloading?

**Comment by Brend-Smits** [comment]
This happened just after server startup, so not chunk unloading. That's pretty much all the details that I know off and that I can give =/ Sorry.

**Comment by rubensworks** [comment]
@Rubbertjuh I can't reproduce this myself, but I pushed a small change that may resolve your crash. Could you test this on your server?

**Comment by rubensworks** [comment]
Considering this resolved, @Rubbertjuh, let me know if this is not the case.
