### ISSUE TITLE
Exporting non-stackable items causes the server to hang

### ISSUE THREAD

**Issue by Naosyth** [CyclopsMC/IntegratedTunnels#171]
#### Issue type:

- :bug: Bug

____

#### Short description:

Exporting non-stackable items from a network to a container causes the server to hang. This was introduced by the recent updates, although I'm not sure if this is actually a problem with Tunnels or Dynamics or something else.

#### Steps to reproduce the problem:

1. Export non-stackable items
2. Server hangs

#### Expected behaviour:

1. The exporter correctly exports only non-stackable items without freezing the server.
____

#### Versions:

- CyclopsCore: 1.12.2-1.4.0
- CommonCapabilities: 1.12.2-2.4.2
- IntegratedDynamics: 1.12.2-1.0.15
- IntegratedTunnels: 1.12.2-1.6.10
- IntegratedCrafting: 1.12.2-1.0.8
- IntegratedTerminals: 1.12.2-1.0.9
- Minecraft: 1.12.2
- Forge: 14.23.5.2837

#### Log file:
[stall-2019-06-29_19.37.29.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/3342521/stall-2019-06-29_19.37.29.txt)

**Comment by rubensworks** [comment]
Seems to be the same thing as #170, merging it with that issue.
