### ISSUE TITLE
Fluid that can not reach destination create terminal warning.

### ISSUE THREAD

**Issue by desagas** [CyclopsMC/IntegratedTunnels#172]
#### Issue type:

- :snail: Performance issue

____

#### Short description:

Even on a small network, every second, 20 ticks, that an importer can not output to an interface attached to a tank, and an exporter that can not push into a full tank from an interface, IE a tank that is full, a warning is generated in the terminal. This has caused a noticeable drop in performance when looking at the area. I have a network with 128 combined fluid imports, exports and interfaces, handling 24 different fluids. Currently, I have overflow protection on some, and not others, meaning, overflow fluids are trashed in some cases. With some rare fluids, they do not get trashed, which means they are constantly trying to be pushed into a full tank, creating a warming message in the terminal.

#### Steps to reproduce the problem:

As described above: attach an importer to a tank, an interface to a full tank, and an exporter to a full tank, and watch the warning messages emerge.

____

#### Versions:

- This mod: IntegratedTunnels-1.12.2-1.6.8
- Minecraft: 1.12.2, FTB Interactions 1.9.1
- Forge: forge-14.23.5.2838

#### Profiler output:

[Time] [Server thread/WARN] [Cyclops Core]: Slotless source to destination movement failed due to inconsistent insertion behavior by destination in simulation and non-simulation: org. cyclops.integrateddynamics.core.network,IngredientChannelIndexed@____. Lost: net.minecraftforge.fluids.FluidStack@____. This can be caused by invalid network setups.

I did not include the @ codes as they are different every single warning.

**Comment by rubensworks** [comment]
Could you try updating to the latest IT version? Fluid movement has been rewritten a bit, so this may resolve your issue.

**Comment by desagas** [comment]
Perfect. It fixed the issue. Thank you.

Denver Leman

On Jul 16, 2019, at 12:16 AM, Ruben Taelman <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you try updating to the latest IT version? Fluid movement has been rewritten a bit, so this may resolve your issue.

**Comment by rubensworks** [comment]
Great! Thanks for checking.
