### ISSUE TITLE
World Item Exporter

### ISSUE THREAD

**Issue by Perlo0ung** [CyclopsMC/IntegratedTunnels#173]
I have a problem with the world item exporter and i can't figure out what the problem is.

I am trying to do some crystal cluster automation with astral sorcery, basicly u drop a 1 crystal and 1 stardust into a puddle of liquid starlight, which then forms a crystal cluster. The problem i have is that i can't get it to work because if i export an item list (ignoring nbt) of crystal and stardust from a single chest, it sometime just spits auto two stardust instead of one crystal and one stardust (chest contains both items at all time). Why is that? What am I missing?

I would expect that it exports 1 of each, if i make a static list of those items and use item rate 2.
Even if i make a list of those 2 items with stacksize 1, the behaviour is the same.

**Comment by rubensworks** [comment]
The list aspect does not work like that. When exporting a list, the exporter will in each tick try to export the first item in the list that is available in the network.

What you probably need to do, is use two separate world exporters, one for each item you want to export. (there are other, more complex, alternatives though)

**Comment by Perlo0ung** [comment]
oh... that explains a lot :) Thx for letting me know.
