### ISSUE TITLE
Only export certain items based on a condition

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedTunnels#175]
#### Issue type:

- :question: Question

____

#### Question:

Hello there! I am trying to make a system which only exports certain items to a chest based on a condition. For example: when a lever is turned on, cobblestone and granite will be exported to the chest. No other items, only cobblestone and granite. If the lever is turned off, only cobblestone is exported to the chest, so no granite. I'm fairly new to Integrated Dynamics/Integrated Tunnels so I might be missing something obvious, but I've figured it's not possible to have multiple variable cards in multiple slots of the Item Exporter. I suppose I need to do something with a List, so when the lever is turned on, granite is pushed to the list, and when it's turned off granite is removed from the list again, but I'm not sure.

Thanks in advance!

**Comment by rubensworks** [comment]
I'd suggest using the choice operator for this. If true, the choice operator could return a list with cobble and granite, if false, it would return a list with only granite.

(FYI, you may have faster replies to your questions if you go to our Discord server)
