### ISSUE TITLE
Strange change to energy tansfer from older versions

### ISSUE THREAD

**Issue by Pultex** [CyclopsMC/IntegratedTunnels#176]
#### Issue type:

- :question: Why is a DI energy battery needed now for energy transfer between mods like EIO and TE [Thermal Expansion] ?

____

#### Question:

I the past you could take a Energy Input and an Energy Exporter from one mods energy storage and send it to another if they supported the same energy [Forge] at the rate you wanted. Now even if you place an energy storage with an Energy Interface it will not transfer energy but only store energy in the energy storage block from the other mod through the Energy Interface.
The only way I can get the Energy Input and the Energy Export to work is it to have the cable directly connect to the DI battery,not with the energy interface, other wise nothing will transfer.

Was was this done to make stability/accurate transfers ?

There is also and odd effect that if you take three DI energy batteries and place one with and import and export the third with and energy interface all the energy will transfer from the import to the export like expected, then change the block connected to and energy import to and EIO or TE energy cell and no energy transfers. 

With the EIO capacitor it's even weirder if you have Waila or One probe you can see the energy in the importer and in the exporter, IT IS THERE, just will not move to any machine or energy storage connected to them.

**Comment by rubensworks** [comment]
Was this issue meant to be a bug report?
Any changes that were made that somehow broke things that used to work before are definitely unintentional.

Note that EIO used to do some peculiar things with their energy capabilities, which caused funkyness with ID. Not sure if that still is the case.

Also, what do you mean with _DI energy battery_? Are you referring to the ID energy battery, or something else?

**Comment by Pultex** [comment]
Yes the ID energy battery needs to be directly connected to transfer power through the network now.
This could be the ModPack Enigmatica 2 Expert doing it, though I looked at the settings and they seem to be the same as default.
It will work just you HAVE to connect a ID battery to it for any transfer to start, as it seem to just not want to use the ID energy interface to transfer power from any other energy source other into an storage device.

So if you place a ID importer on a EIO capacitor or TE energy cell set to output and you need to place an ID energy Interface on to any other storage device/machine the exporter will not transfer power, the version in Sky Factory 3 did not need this as I used ID exclusively to transfer everything from power, items, fluids around the base.

It makes no error and seems to act like its working fine, just nothing happens, unless you have the ID Battery connected to the network cable.

Battery size makes no difference, just as long as it is there.

So it works just not like in Sky Factory 3.

**Comment by rubensworks** [comment]
Ok, could you create a bug report with all required information (and close this issue here)?
The bug report template will ask for some information that I will need for reproducing and fixing this issue.
