### ISSUE TITLE
Player Simulator and buckets of liquids

### ISSUE THREAD

**Issue by NoX-programer** [CyclopsMC/IntegratedTunnels#178]
#### Issue type:

- :bug: Bug

____

#### Short description:

When Player Simulator used with bucket, it acts wierdly very much:
* igonring Y offset
* cannot be configured to Y_offset < 0
* working with block above the block it's facing
* working with some wrong block (and only places liquid, not removing!) when block above is stuffed
* only removes liquid, but not placing it when half-block (slab) is opposite

#### Steps to reproduce the problem:

We need chest with bucket of liquid, item interface, attached to chest, cable(s) and player simulator. Then try to make this to put/remove liquid to/from block. [Video](https://youtu.be/_0UubwGpnck) will explain even better.

#### Expected behaviour:

* offsets are working, not ignoring
* offsets must be able to be configured in [-1 ... +1]
* by default, with offsets = 0, Player Simulator must put/get liquid only from block directly faced to it
* when configured block stuffed with non-liquid, do nothing (in case of bucket and right mouse)
* it must make no difference and work, no matter what is opposite - slab or full block

____

#### Versions:

- This mod: 1.6.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:

not required, I presume, because of not a crash

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by NoX-programer** [comment]
upd: When it clicking with block, it places block in front of itself - that's ok. But where it tries to click with buckets on my server (Volcano Block modpack), I just have no idea. It is definitely neither Y+1, nor Y-1, I just failed to find out. Maybe we need some visual, chat or other debugging.

**Comment by 1JackBlack1** [comment]
I am having some similar issues, with the same mod pack, so I creative world with only a few mods (only those required for integrated tunnels) to see just what happens.
Setup:
Player simulator facing east.
Connected to a chest with empty buckets, via a logic cable and item interface.
Variable card set to bucket as an item, placed in the "Click item" slot.
Entire setup placed roughly in the centre of a large cube of water.

Having the "target side" set to any of the cardinal directions will result in it first trying to take from 1 block above where it is attached to (i.e. one block above the block directly beside the player simulator).
If this is stone (or presumably any other solid block, I have tried glass and grass as well) nothing happens.
If it is a partial block (such as a chest or logic cable) or air it will then pull from further away (i.e. if the target side is west, it will pull from further to the east.

Setting the target side to up instead has it pick up from 3 blocks above the block it is attached to.
This then has similar behaviour, with it trying to draw from that block or further down.

Setting the target side to down has it first pick from 1 block below the block it is attached to. This then behaves has similar behaviour, with it trying to draw from that block or further up.

Some extra strange behaviour is that of slabs and stairs.
Top slabs and top stairs would stop it drawing any more water.

When the target side was facing up, a bottom slab also stopped it drawing in further water as did any stair. For all other directions bottom slabs allowed it to continue drawing up water.

Having the target side as south had stairs facing north or west stop it, but not east or south.
Having the target side as north had stairs facing south or west stop it but not east or north.
Having the target side as east had stairs facing north or west stop it, but not east or south.
Having the target side as west had all bar stairs facing south stop it. (This remains the same even when the simulator is facing west or south)
Having the target side as south had north and west stop it but not east or south. (Again, this remains the same even when the simulator is facing west or south)

So with that knowledge I can have it reliably pick up a water source block in front of it by having the target side set to up, and making sure 3 blocks above that source are air. Any block within that region will stop it.

Placement of water buckets seemed to mostly work in the same way.

The offset didn't seem to do anything at all.

**Comment by 1JackBlack1** [comment]
Repeating a similar test in the Volcano Block modpack yielded drastically different results, which makes me assume there is at least some kind of cross mod interaction.
Setting the target side to north resulted in the above behaviour, with 5 blocks removed.
Setting the target side to south resulted in the same block being taken first as above, then the block 1 further north as above, but then the block 1 further west, and then proceeding north, for a total of 7 blocks removed.
Setting the target side to west resulted in first the normal block being taken, then one northwest, then proceeding east for a total of 7.
Setting it to east resulted in it first taking the normal block, then one northwest, then one south (so west of the first block to be taken), then continuing to the west, for a total of 7.
Setting it to down resulted in picking up 1 block to the west of were it did in the previous test, and then continuing upwards. (This applied regardless of what direction the player simulator was facing, so when facing west it would take the block directly below where the player simulator was, when facing east it would take a block 2 blocks west and one block below where the simulator was.
Setting the target side to up resulted in no water being collected at all.

Using chests or logic cables will also sometimes appear to obstruct the line of sight preventing more from being taken.

**Comment by rubensworks** [comment]
Will be fixed in the next release. Be sure to open issues should any more problems like this arise in the future.
