### ISSUE TITLE
World block importer duplicates items when block drops multiple items

### ISSUE THREAD

**Issue by 1JackBlack1** [CyclopsMC/IntegratedTunnels#179]
#### Issue type:

- :bug: Bug

____

#### Short description:

When importing charged light collectors from Hearth Well when all bar 1 slot of inventory is occupied the light collector remains in place and is also put into the inventory of the integrated dynamics network, duplicating it each time the importer tries to import.

#### Steps to reproduce the problem:

1. Place a light collector from Hearth Well.
2. Place a world block importer on the light collector and connect to a chest with an item interface (have nothing else in the network).
3. Place an unrelated item in all bar 1 slot in the chest (e.g. stone).
4. Weight for the light collector to get fully charged (charge=3) (needs access to sky).
5. Insert a variable card to have the world block importer import the light collector.
6. Observe the light collector remain in place and also appear in the chest, with more appearing in the chest as time goes on.

#### Expected behaviour:

As inventory cannot accommodate both the light collector and the imprisoned light, nothing should happen.

____

#### Versions:

- This mod: IntegratedTunnels-1.12.2-1.6.10
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2847

Volcano Block mod pack v1.0.34

#### Log file:

N/A, nothing appeared in the logs.

**Comment by rubensworks** [comment]
Could you report this to the issue tracker of the mod owning this Hearth Well block?
I assume that this mod is exposing its inventory in a special way that causes this bugged interaction.

(And please link back to this issue when you do so)

**Comment by 1JackBlack1** [comment]
I decided to do a bit more testing with a more minimal setup to try and see if it was a cross mod interaction.

I created a new instance which only had:
CommonCapabilities-1.12.2-2.4.5
CyclopsCore-1.12.2-1.6.0
IntegratedDynamics-1.12.2-1.1.1
IntegratedTunnels-1.12.2-1.6.10

I then repeated the above setup but instead of the charged light collector I used a flowerpot with a poppy inside.
This resulted in the flower pot being duplicated.
So it appears to be entirely this mod causing the bug.

I was also able to use a more complex setup to duplicate lapis.

On a separate network:
1. Add an inventory reader to the chest from the above setup (chest 1), and store the variable inventory count.
2. Have another variable set to an integer with the value 90.
3. Construct a variable using the "==" operator with the above 2 variables
4. Attach a variable store to store the first 2 variables.
5. Attach an item interface to the chest (chest 1).
6. Place another chest (chest 2) with an item exporter on it.
7. Set this item exporter to export 1 item and have it use the variable from the comparison set up before.
8. Place 63 lapis in the first slot of chest 1. Then place a single item (not lapis) in every other slot.
9. Place a lapis ore block in front of the world block importer.

The world block importer then places a lapis in chest 1, which triggers the second network to export 1 lapis to chest 2, and then the cycle repeats, with more and more lapis being produced.

The same also works with redstone ore.

While I haven't tested every possibility, I believe this results from any block which drops more than 1 item when it breaks, and is easiest to do with blocks which drop 2 different items as then the first slot can be entirely empty.

**Comment by rubensworks** [comment]
Thanks for the additional information!
