### ISSUE TITLE
Subnetworks

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedTunnels#18]
Each Integrated Dynamics component has an ID number. I think it would be useful to add a filter to the Import/Export interfaces to Push/Pull items from a specific Item Interface ID on the network. Could be applied to Energy/Fluid Interfaces as well.

**Comment by rubensworks** [comment]
Note to self: implement channels.
Make capability retrieval from networks channel-based, with `0` as default channel.

**Comment by BiatuAutMiahn** [comment]
Nice, that would be beautiful. Allowing one to create complex networks, and having channels within this network, like channels on a coax (Cable TV)
