### ISSUE TITLE
Ex-/Importers and lists

### ISSUE THREAD

**Issue by Xandaros** [CyclopsMC/IntegratedTunnels#181]
#### Issue type:

- :bug: Bug

____

#### Short description:

The item exporter (and presumably other exporters and importers) is not able to handle a `List[Any]` in the `Export Items` aspect, even if it only contains `Item`s.
This is confusing, since the type of list is not actually visible to the user - when you have an `append` variable card, it will only tell you that it outputs a list. It could therefore be assumed that only the runtime type matters. I certainly assumed that and didn't think there was a difference between `List[Any]` and `List[Item]`.

Furthermore, if you have a `List[Any]` with an `Item` in it and take the `head`, you get a variable card with type `Any`. Putting this in the `Export Item` aspect shows a tick mark, but nothing is ever exported.
If, instead, you take the head of a `List[Item]`, you still have a variable card of type `Any`, but exporting works perfectly fine.
In either case, putting the variable card in a display happily displays the item and they are otherwise indistinguishable.

#### Steps to reproduce the problem:

1. Make a setup with two chests. One with an item interface on it, the other with an item exporter. Include a variable store and connect everything together.
2. Make a variable card of an empty `Any` list.
3. Another variable card with an `Item` of your choosing. Let's take cobblestone as an example.
4. Another variable card that appends the item to the empty list.
5. One last variable card that takes the head of the card created in step 4
6. Place the card made in step 5 in the `Export Item` aspect of the exporter
7. Place all the other cards in the variable store

#### Expected behaviour:

Cobblestone placed in the chest with the item interface should be moved to the chest with the exporter.

____

#### Versions:

- IntegratedTunnels: 1.12.2-1.6.10
- IntegratedDynamics: 1.12.2-1.1.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by Krutoy242** [comment]
Problem with lists can be recreated another way.

```Haskell
list = [] -- List of items from inventory reader

-- Displays item in first slot, but won't push items with exporter. 
-- Also card can be inserted in any aspect
O = Apply2(ListGet, list, 0) 
```
Demonstration: https://imgur.com/2LY9zd8

<blockquote><img src="https://i.imgur.com/2LY9zd8.jpg?fbplay" width="48" align="right"><div><img src="//s.imgur.com/images/favicon-16x16.png" height="14"> Imgur</div><div><strong><a href="https://imgur.com/2LY9zd8">Imgur</a></strong></div><div>Post with 0 votes and 2 views.</div></blockquote>
