### ISSUE TITLE
I want to share the mod to the Chinese MineCraft forum.

### ISSUE THREAD

**Issue by KuraiMoe** [CyclopsMC/IntegratedTunnels#183]
Hi!I like this mod very much because it can help me a lot.
So I want to share the mod to the forum “https://www.mcbbs.net” in China.
I will mark out the author‘s name and download link from curseforge.com or my mirror(Include Simplified Chinese language files).
Thank you very much and have a good day!

**Comment by rubensworks** [comment]
Feel free to share this mod anywhere as long as it links back to curseforge or github, I do not condone any mirrors.
