### ISSUE TITLE
Use checkbox for controlling boolean options

### ISSUE THREAD

**Issue by Gan-N** [CyclopsMC/IntegratedTunnels#186]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

When I want to set the pipeline to not detect NBT, I also need to remove true and then enter 0 or false. It is better to set it as a single option.

**Comment by rubensworks** [comment]
I don't understand what you mean, can you clarify?

**Comment by Gan-N** [comment]
When setting the network output and network input ports to check the validity of the persistence, you need to manually delete the old true to make changes.
It would be better to set as a button to toggle true / false.

**Comment by rubensworks** [comment]
Ok, now I get it. I'll rewrite your issue.
