### ISSUE TITLE
Player simulator does not dye wool on the Ender Tanks or Ender Chests

### ISSUE THREAD

**Issue by Chaz8591** [CyclopsMC/IntegratedTunnels#188]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. Place Ender Chest or Ender Tank
2. Place Player simulator on block one
3. Place Logic Cable on player simulator
4. Place item interface on Logic Cable
5. Place Chest on item interface
5. create variable for dye item
6. place dye in chest
7. place variable in Player Simulator under "Click item"
8. adjust Y offset for good measure

#### Expected behaviour: Player Simulator should dye the center wool piece, just like if a sheep was under the player simulator. You should be able to adjust the X or Z offset to dye the two other pieces of wool.

____

#### Versions:

- This mod: 1.6.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2821

(Using modpack: Direwolf20 1.12 v2.5.0)

**Comment by rubensworks** [comment]
This should be fixed with b6eb8545eab94762e3d500a984b92234d8e71eee.
This fix will be out in the next release (coming soon).
Should you still encounter this problem after updating to the new version, be sure to comment on this issue, so I can reopen it.
