### ISSUE TITLE
Feature: Interface with other slots on Utility blocks?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedTunnels#19]
What of the ability to Push/pull items from a given Utility block, for example: Crafting table (a bit extreme, i know...and not really necessary) Enchantment table, Furnaces, etc.

A couple given senarios:

Furnace: In the event of an unmeltable item is pushed into the furnace, the only way to get it out is manually remove it, or of course filter it out before pushing.

Enchantment Table: If [*this*](https://github.com/CyclopsMC/IntegratedDynamics/issues/139) can be implemented.... Oh say, allow the network to populate the Lapis slot. Then remove it when the player stops using it.

**Comment by rubensworks** [comment]
I'm not sure if I understand your request. This should already be possible with the combination of an importer and exporter based on certain conditions.

**Comment by BiatuAutMiahn** [comment]
In the past I have attempted to use different values in the item slot setting for an Item Exporter, and it didnt seem to have an effect, I will do some more testing

**Comment by rubensworks** [comment]
That _should_ work, perhaps it's a bug then.

**Comment by rubensworks** [comment]
Slot selection seems to work just fine for me.
