### ISSUE TITLE
Item Importers Duplicated

### ISSUE THREAD

**Issue by zig13** [CyclopsMC/IntegratedTunnels#191]
#### Issue type:

- :bug: Bug

____

#### Short description:

Item Importers duplicated in conjunction with scorched duct

#### Steps to reproduce the problem:

1. Put all Integrated items into backpack to avoid confusion
2. Picked up Item Importer from scorched duct with wrench - went to inventory bar slot 0
3. Placed down Item Importer from inventory bar slot 0
4. Noticed I still had an Item Importer in inventory bar slot 0
5. Opened inventory and noticed the variable card that had been in the Item Importer I picked up was not there (sorry didn't notice if it rendered in world or made pickup sound)
6. Picked up Item Importer - now have two Item Importers in inventory bar slot 0
7. Placed and picked up some more times resulting in holding 5 Item Importers
8. Recorded this video: https://youtu.be/1LHVeiPWikE

#### Expected behaviour:

Number of Item Importers should stay constant. Variable cards should not be lost.

____

#### Versions:

- This mod: 1.6.10
- Minecraft: 1.12.2
- Forge: 8.0.99.99
- Modpack: Enigmatica 2 Expert 1.76a

Would like to update but am playing on friend's server

#### Log file:

https://pastebin.com/up4vx1L2

**Comment by rubensworks** [comment]
I see you are not using the latest IT version, could you try with the latest?
Also make sure you are using the latest ID version.

**Comment by zig13** [comment]
The High Oven has been removed/disabled in the latest version of Enigmatica 2 Expert which makes it pretty difficult to test with the setup I have on the server.
Best I could do is manually update the two mods in my client, create a single-player world, cheat in the High Oven+cables and play around for a bit.
Maybe close this issue but keep it in mind as a data point if the issue gets raised again?

**Comment by rubensworks** [comment]
Sounds good.
