### ISSUE TITLE
Add support for Tinkers' Construct Scythe to the Player Simulator

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedTunnels#195]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

The Player Simulator should be able to do a "player" right-click on plants with the Scythe from the Tinkers Construct mod, to automatically perform its harvest function.

Tinkers' Construct says that not the correct "item callback" is being used, of the four available. They pointed me to this line of code (in the direct parent class of the Scythe):
https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/tools/tools/Kama.java#L96

____

#### Additional stuff:

Currently the simulation of the right-click doesn't work, as no harvest is performed. But when using a (continuous) left-click on a Hammer from the same mod, a block does get successfully broken correctly (even if it has a Silk Touch property it'd drop the correct thing). So current support must be only partial.

As a presumable side effect of what is not working, I notice that the 3x3 area of effect of both the Hammer and Scythe are completely ignored when using the Player Simulator, but I'm unable to tell whether that is caused by or otherwise related to the same issue. This is observed by the Hammer only dropping the single middle block directly adjacent to the simulator, and for the right-click with the Scythe, that it only increases the XP on the tool (with Tinkers' Tool Leveling installed) for a single block on each click.

(For reference, also created an issue on their side here: https://github.com/SlimeKnights/TinkersConstruct/issues/4135)

**Comment by rubensworks** [comment]
Thanks for reporting!
I'm going to mark this as a bug, as it definitely sounds like unintended behaviour.

**Comment by Jack-McKalling** [comment]
Thanks! I chatted on discord with some of the ID experts and they suggested it might be a feature request. I originally thought it may be a bug as well.
