### ISSUE TITLE
Energy importer with import rate of 0 still imports energy

### ISSUE THREAD

**Issue by TheAdamizer** [CyclopsMC/IntegratedTunnels#196]
#### Issue type:

- :bug: Bug

#### Short description:

An energy importer attached to a charged fluxduct will allow energy to flow, even if the transfer rate is set to 0.
https://i.imgur.com/YosTTN4.png
A variable card with a value of 0 is set for the energy transfer rate of the importer (the behavior is the same if a blank card it passed to the top slot and the energy transfer is set to a constant 0)
TE Multimeter confirms RF is flowing (interacting with my machines downstream confirms this: they are getting energy still)
https://i.imgur.com/DGMge6g.png
I understand that the paradigm for energy transfer is to use an energy interface, however I do not wish to use ID batteries and I cannot import/output on the same face on my RF Tools battery.

I believe that bug is unexpected enough to report as it seems the behavior to transfer should become a binary 'false' once transfer rate hits 0, however I'll leave it to you to decide if it's a supported case or not.

#### Steps to reproduce the problem:

1. Use any RF battery set to export and place a flux duct on it
2. Setup as follows Battery > Fluxduct > Energy Importer (with transfer rate of 0) > Omnidirectional > another omni > Energy Interface > (any kind of system using RF power)
3. Notice energy flows.
4. Take out the card (or use a 'false' card)
5. Energy doesn't flow as expected.

#### Expected behavior:

When a variable card with energy transfer rate of 0 is placed in an energy importer, the importer should import no energy.
In fact, this problem exists with any other transfer rate (the observed transfer rate doesn't seem to be informed by any of my settings/variables), but again the fact that it's set to 0 and still transfers seems to be most unexpected to me.

#### Versions:

- This mod: 1.12.2-1.6.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:

(I'll provide if you want something from me)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This seems to be caused by #196.

**Comment by TheAdamizer** [comment]
Wait, I'm confused.  This is #196 right?

**Comment by rubensworks** [comment]
Oops, I meant #75.

**Comment by TheAdamizer** [comment]
Ah yes, I would agree.  Thank you!
