### ISSUE TITLE
Crash on World Block Import into Real Filing Cabinet

### ISSUE THREAD

**Issue by Shurlan** [CyclopsMC/IntegratedTunnels#197]
#### Issue type:

- :bug: Bug

____

#### Short description:

If a block is imported by a world block importer and a filing cabinet has a file with the coresponding item connected to the network by an item interface the game crashes.

#### Steps to reproduce the problem:

1. Place a real filing cabinet down with a cobblestone folder and connect to a network via an item interface.
2. Setup a world block importer on the same network set to always import.
3. Place a cobblestone infront of the world block importer.

#### Expected behaviour:

The game not crashing. :P
(After reloading the game, the item is correctly added to the storage. I.e. it did it's job but crashed)

____

#### Versions:

- This mod: 1.6.12
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

#### Log file:

https://pastebin.com/A91pXGVU

**Comment by rubensworks** [comment]
Thanks for reporting!
