### ISSUE TITLE
Fluid Importers/Exporters ignoring priority

### ISSUE THREAD

**Issue by novemix** [CyclopsMC/IntegratedTunnels#198]
#### Issue type:

- :bug: Bug

____

#### Short description:

When more than one fluid importer or exporter is on a network, fluids are taken in or removed equally between the *porter regardless of the priority setting.

#### Steps to reproduce the problem:

(a comparable setup can be built with importers on non empty fluid tanks into another receiving tank)

1. Place a fluid interface on a fluid provider
2. Place 2 fluid exporters on 2 different output tanks
3. Connect interface and exporters with cable
4. Set priority on one exporter to be higher (right click on exporter, click settings in upper right, increase priority and click save)
5. Enable exporters with blank variable cards in Export All Fluids boolean
(timing can be controlled by setting interface to a different channel, inserting variable cards, then setting interface back)

Fluids will be exported equally between non full tanks

#### Expected behaviour:

Higher priority should be exported/imported first until full/empty, then lower priority

____

#### Versions:

(SkyFactory 4)
- This mod: 1.6.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by rubensworks** [comment]
This is the intended behaviour. Priority is used to determine the tick order of parts. For example, during tick X, part A (priority 1) will export Y amount _before_ part B (priority 2).

If you want to control exporting behaviour across multiple ticks, you'll make to add readers to the tanks and export based on their state.
