### ISSUE TITLE
Implement giveItemToPlayer for Player Simulator

### ISSUE THREAD

**Issue by carboniris** [CyclopsMC/IntegratedTunnels#199]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Some things, like the Oreberries mod, like to put items directly into the player's inventory (using ItemHandlerHelper.giveItemToPlayer) rather than dropping them on the ground. A player simulator set to right click these will cause the item to disappear, since the player simulator doesn't have an inventory. Would there be a way to set the player simulator to do something with items given to it (typically importing them into the network)?

**Comment by rubensworks** [comment]
The player simulator does in fact expose an inventory. Do you have an item interface pointing to a valid inventory on your network?

This may be a bug, so please share your mod and MC versions.

**Comment by carboniris** [comment]
I started a new world to reproduce without any other mods present, MC version is 1.12.2, Forge version is 14.23.5.2854. Mods are installed via Twitch Launcher:

- Common Capabilities 2.4.7
- Cyclops Core 1.6.6
- Integrated Dynamics 1.1.9
- Integrated Tunnels 1.6.12
- Oreberries 0.5.0

I have a Player SImulator pointing directly at the Oreberry Bush, set to Click Empty. Connected to that is one Logic Cable, connected to an Item Interface, attached to a chest. When the bush matures the Player Simulator right clicks and the berry is harvested, but disappears and does not show in the chest.
![Screenshot](https://user-images.githubusercontent.com/16262064/91647726-e1649e00-ea12-11ea-9e04-2df497756706.png)
![Screenshot)](https://user-images.githubusercontent.com/16262064/91647729-e75a7f00-ea12-11ea-8237-cf0d54ed66e4.png)
![Screenshot](https://user-images.githubusercontent.com/16262064/91647732-eb869c80-ea12-11ea-973a-e8212a8c8401.png)
![Screenshot](https://user-images.githubusercontent.com/16262064/91647734-ee818d00-ea12-11ea-9689-c8accd0edbf0.png)

The source code in question for the Oreberries mod is here: https://github.com/josephcsible/Oreberries/blob/1.12.1/src/main/java/josephcsible/oreberries/BlockOreberryBush.java#L160

<blockquote><img src="https://avatars3.githubusercontent.com/u/16061266?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/josephcsible/Oreberries">josephcsible/Oreberries</a></strong></div><div>A Minecraft mod that brings back a configurable version of 1.7.10 Tinkers' Construct oreberries - josephcsible/Oreberries</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for the information, that setup looks like it should be working indeed.
