### ISSUE TITLE
[1.10.2] Crash placing Integrated Tunnel Fluid Interface below a ID Squeezer

### ISSUE THREAD

**Issue by b0bst3r** [CyclopsMC/IntegratedTunnels#2]
IntegratedDynamics-1.10.2-0.6.3
IntegratedTunnels-1.10.2-1.0.0

Place down Integrated Dynamics Squeezer
Place Fluid Interface from Integrated Tunnels under it 
Results in the following crash - http://pastebin.ubuntu.com/23548128/

**Comment by b0bst3r** [comment]
Can I also add that once placed the world will refuse to load and it crashes with the above error.

**Comment by rubensworks** [comment]
Seems to be a duplicate of #1, which has been fixed but not released yet.
If you want, you can try out the latest dev build to see if this resolves your problem: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/integratedtunnels/IntegratedTunnels/1.10.2-1.0.0-15/IntegratedTunnels-1.10.2-1.0.0-15.jar

**Comment by b0bst3r** [comment]
Yeah that fixes it thanks.
