### ISSUE TITLE
Bug: Network does not transfer items intermittently

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedTunnels#20]
I notice this happening at random from time to time. In two scenarios...

1, I have a Squeezer, and I have a Drying basin. I have some components to read the inventory of the squeezer to determine if it empty and if it is completely *squeezed*, if it is empty, a Redstone writer will send a true to keep it *reset*, and the other condition is self explanatory. Anyway, the network will put a log in the squeezer, and will take a Menril block out of the drying basin once dried. anyway sometimes this will locked up and a block will not be pulled out of the drying basin.

2, when dumping items into a chest from my player inventory ie; ctrl+clicking at times the items will stop being pulled from the chest.

In either case, the solution would be to take a wrench and disconnect, then reconnect the cable to the network. Sometimes even that does not work, and you have to break the Item interface too.

**Comment by rubensworks** [comment]
Are you waiting long enough? Because due to an optimization, the importers/exporters may be idle for a second or two if there were no changes in the inventory in the near past.

**Comment by BiatuAutMiahn** [comment]
Yes, I could sit there for a few minutes, or leave and come back and that part of the network is locked up.

**Comment by BiatuAutMiahn** [comment]
oh, and removing/readding a variable card had no effect

**Comment by rubensworks** [comment]
Ok, I'll try looking into it soon. In the meantime, if you could provide me with a fully reproducible use-case, that'd help me a lot.

**Comment by BiatuAutMiahn** [comment]
Ill try, but it seems random

**Comment by BiatuAutMiahn** [comment]
I think this might have something to due with the chunk being loaded/unloaded.

**Comment by rubensworks** [comment]
Could be related to #17 then.

**Comment by rubensworks** [comment]
@BiatuAutMiahn Could you check to see if you still encounter this problem in version `0.6.9`?

**Comment by BiatuAutMiahn** [comment]
will do

**Comment by Silvrus** [comment]
I'm wondering if I'm having the same issue. Upon chunk unload, I come back to the extractor/importer showing an error about "Network Corruption Detected". Breaking and replacing fixes the issue.

**Comment by rubensworks** [comment]
@Silvrus Probably related to #23

**Comment by rubensworks** [comment]
Assuming fixed as of Integrated Dynamics `0.6.10`, please comment if this is not the case.

**Comment by BiatuAutMiahn** [comment]
0.6.9 seems to have fixed the issue for me, however I still noticed some minor (possibly unrelated) issues. Will continue to watch out for any more bugs
