### ISSUE TITLE
Player Simulator Duplicating Aquamarine (Astral Sorcery)

### ISSUE THREAD

**Issue by ElahiKeru** [CyclopsMC/IntegratedTunnels#200]
#### Issue type: 

- :bug: Bug

____

#### Short description:

When setting up a player simulator to simulate right click with right hand and supplying the network with aquamarine from Astral Sorcery, I noticed that the count of aquamarine in the chest attached to supply the network was growing. 

#### Steps to reproduce the problem:

1. I've attached a screenshot of my setup. 
2. Logic includes searching for Nighttime and a non-full tank.
3. Logic is set into the Click element of the Player Simulator

![2020-09-15_13 50 04](https://user-images.githubusercontent.com/29162323/93252070-9fe62980-f75a-11ea-94aa-2a091a7c8102.png)

#### Expected behaviour:

I would expect for items to not be duplicated when simulating a right click using a player simulator against an Astral Sorcery Lightwell.

____

#### Versions:

- This mod: 1.6.14
- Minecraft: 1.15
- Forge: 31.2.36

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like the same problem as #205.
