### ISSUE TITLE
Player Simulator can't interact with cauldron from More Cauldrons

### ISSUE THREAD

**Issue by mkaito** [CyclopsMC/IntegratedTunnels#201]
#### Issue type:

- :bug: Bug

____

#### Short description:

Cauldrons from the More Cauldrons mod can be used to generate lava by placing it over a torch and right clicking cobblestone onto the cauldron. This does work when done by hand by the player, or by the Auto Clicker from Click Machine, but trying to use the IT Player Simulator does not work.

The PS is configured with a Variable Card configured as Item Cobblestone in the Click Item slot.

Interestingly enough, if you swap the Cobblestone card out with a blank card placed in the Click aspect, it will successfully click cobblestone into the cauldron once, but never again.

#### Steps to reproduce the problem:

1. Have a cauldron from the More Cauldrons mod placed on top of a heat source (torch will do)
2. Have cobblestone in ID network
2. Put a Player Simulator on the side of it
3. Set the PS to right click with cobblestone
4. Nothing happens

#### Expected behaviour:

Lava should appear in the cauldron as cobblestone gets right-clicked into it.

____

#### Versions:

- Minecraft: 1.12.2

* Integrated Dynamics 1.12.2-1.1.6
* Integrated Tunnels 1.12.2-.1.6.11
* More Cauldrons 1.4.6
* Click Machine 1.12.2-1.2.0

- Forge: 14.23.5.2854

Modpack: SkyFactory 4 - 4.2.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
What I did to get this automation to work, is to use World Item Exporters instead of Player Simulators. It's got something to do with the way the cauldrons accept the items. Don't ask me how it works. But in this way I've successfully constructed an automation that brews speed potions of all tiers.

**Comment by rubensworks** [comment]
I can't seem to make this More Cauldrons mod accept cobblestone in my dev environment.
Since @Jack-McKalling found a workaround, I'm considering this a wont-fix (since 1.12 is going to be abandoned).
