### ISSUE TITLE
1.12: World Block Importer doesn't respect "Blacklist" aspect config and instead turns aspect into "import anything"

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedTunnels#202]
#### Issue type:

- :bug: Bug

____

#### Short description:

The World Block Importer does not respect the "Blacklist" aspect config option when set to true, whether it's Item, List&lt;Item>, Block, or List&lt;Block>. Setting Blacklist to "true" for any of these causes the Importer to import blindly.

____

#### Versions:

- Dynamics: `1.12.2-1.1.7`
- Tunnels: `1.12.2-1.6.12`
- Minecraft: `1.12.2`
- Forge: `14.23.5.2847`

**Comment by GreyMario** [comment]
Update: This also seems to happen to predicates, whether Item or Block. Tested with a simple `Relational Not Equals` and `Stone` item/block.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by GreyMario** [comment]
A bit of additional testing seems to sugest that Lists aren't being checked *at all* (treated as zero-length, effectively), which goes hand-in-hand with the Blacklist version importing everything; it seems *nothing* gets imported when a List in whitelist mode is used.

**Comment by rubensworks** [comment]
I can't seem to reproduce this on my end. Everything seems to be working as intended.
Were you by any chance working with a list having empty entries?

If not, could you share a guide/video showing step-by-step what I need to do to reproduce this?

**Comment by GreyMario** [comment]
If memory serves, the test case was a List&lt;Item&gt; and later a List&lt;Block&gt; containing exactly one entry for Stone (1x) and no other entries. When used in the List aspect and set to whitelist, the World Block Importer would import literally anything; when set to blacklist, it imported nothing.

I can probably record a demonstration Monday, if I'm lucky.

**Comment by GreyMario** [comment]
Okay, I'm in a position where I can reinvestigate properly. I can't seem to replicate any part of this in the following:
- Dynamics `1.1.10`
- Tunnels `1.6.13`
- Forge `2854`

Rolling Tunnels back to `1.6.12` to see if it suddenly appears.
E: Nope. Rolling InDy back... Nope. Rolling Forge back...

I can't replicate, even with Dynamics `1.1.7`, Tunnels `1.6.12`, and Forge `2847`. What the hell happened to break it, past me?

**Comment by GreyMario** [comment]
..I still have the instance and the build that breaks. I can't replicate the issue, even with the same versions of everything the offending broken instance uses.

The only conclusion I have left is that something in Compact Claustrophobia is interfering with the function of the World Block Importer, and right now I really don't feel like shoveling through that modlist to find out what broke it.

On those grounds, closing the issue.

**Comment by rubensworks** [comment]
Thanks for checking in any case!
