### ISSUE TITLE
Exporter won't push most modded items

### ISSUE THREAD

**Issue by scialt61** [CyclopsMC/IntegratedTunnels#204]
#### Issue type:

- :bug: Bug 

____

#### Short description:

For some reason, Item Exporters are not exporting most modded items. All my items are connected via item interfaces, and there is an item exporter with a variable card in the "Export Item" slot. The exporter is connected to a Precision Sawmill from Mekanism, although the problem still occurred when using Drawers or Chests. The exporter could push vanilla blocks.

I attempted to replace the variable card, but it still failed to work. I did have Integrated Crafting and Integrated Terminals installed, as well as ~220 other mods.

#### Steps to reproduce the problem:

1. Set up an Integrated Dynamics system that uses Integrated Tunnels, Integrated Terminals, and Integrated Crafting.
2. Set up your external storage such that they are connected via item exporters.
3. Set up an item exporter into a machine or chest that has a modded item in it. In my case, it did not work with Menril Wood. It did work with Menril Wood Planks for some reason, but not Menril Wood or other items such as Enhanced Energy Conduits, Logic Cables, and Copper Ingots. 
4. Watch the item exporter fail to export items into the machine/chest. 

1. ...

#### Expected behaviour:

I expected the item exporter to push the Menril Wood into the sawmill. This would have produced lots of Menril Wood Planks passively. The item exporter also failed to push the Menril Wood into a chest when I tested it out.

____

#### Versions:

- This mod: 1.12.2-1.6.12
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

Note: I was playing on my custom modpack, so that may have an effect on this issue.

Link to modpack: https://mega.nz/file/BEpXXKaY#aJnLG4XHDCwhWHyZpe0AS5ODiN4IwdB6sM-wNgKSWPU

Link to world download: https://mega.nz/file/BMxj2CKD#LXKkTLqkcqYop9bjHYS18942ZdmveQmOP4cxoJUNOis

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
That's really strange. First time I hear something like this.
I suspect a mod in your pack is breaking things.

Could you try without any other mods installed?
