### ISSUE TITLE
Player simulator right click not working.

### ISSUE THREAD

**Issue by staviq** [CyclopsMC/IntegratedTunnels#205]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I'm not sure if it's one bug or two separate ones, but player simulator does almost never work properly when trying to right click, and if I tell it to right click with item, it duplicates items like crazy.

#### Steps to reproduce the problem:

1. Place dirt, hoe it, and place seeds so wheat can grow.
2. Place one cable, player simulator facing the wheat, and item interface with a chest attached.
3. Put empty variable in the player simulator "Click", so it tries to click with a random item from the chest.
4. Put some bonemeal in the chest.

Now two things are happening wrong:

5. Wheat grows to 100% with the bonemeal ( that part works ), but it does not get harvested ( player right clicking grown wheat results in the wheat being harvested ).
6. Bonemeal in the chest is multiplied ad infinitum.

Some other examples of right click not working:
- Clicking the ground with a shovel should make it a dirt path
- Clicking with a bucket of water, places water infinitly, emptying and refilling the bucket magically.
- Clicking dirt with a poppy should plant it.

____

#### Versions:

- Modpack: E2E.

- This mod: IntegratedTunnels-1.12.2-1.6.13
- Minecraft: 1.12.2
- Forge: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2

#### Log file:

No errors in the logs, and no other messages when the problem is happening.

**Comment by rubensworks** [comment]
Thanks for reporting!



<div align="right"><a href="https://github.com/CyclopsMC/IntegratedTunnels/actions/runs/383894714">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>
