### ISSUE TITLE
Shulker Box Inventory deleted when placed by a block exporter

### ISSUE THREAD

**Issue by gdar463** [CyclopsMC/IntegratedTunnels#207]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The inventory of a shulker box deletes when is placed by a world block exporter

#### Steps to reproduce the problem:

1. Place a item interface on a chest
2. Place a world block exporter on a block 
3. Break the block
4. Place a logic cable con the item interface and a world block exporter
5. Insert a variable card in the first slot of the block exporter
6. Insert a Shulker Box withinventory in the chest

#### Expected behaviour:

The block exporter should place the Shulker Box with the items in

____

#### Versions:

- This mod: 1.6.4
- Minecraft: 1.16.4
- Forge: 35.1.29

**Comment by rubensworks** [comment]
Thanks for reporting!
