### ISSUE TITLE
Item Interface does not pull from Storage Drawers Slave Controller

### ISSUE THREAD

**Issue by Peppe-KSP** [CyclopsMC/IntegratedTunnels#209]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Interface on Storage Drawer Controller Slave with export to a chest all items does not move any items.  Interface on Storage Drawers controller moves items.

#### Steps to reproduce the problem:

1. Add items to a drawer  
2. Add storage controller connected to drawer
3. Add storage controller slave connected to controller/drawer
4. Place a chest near by
5. Place interface on slave controller and logic cables to the chest with exporter on chest (all items variable)
6. Verify no items transfer.
7. Move item interface to real controller - verify items move.

#### Expected behaviour:

Slave controller should operate the same as the controller and allow item I/O.

Appears slave controller inventory is being removed (one probe no longer shows items in the slave when the interface is on it), but no item are actually removed from the storage drawer network and no items show in the export chest.
____

#### Versions:

- This mod: IntegratedTunnels-1.16.4-1.6.16.jar
- Minecraft: 1.16.4
- Forge: 35.1.36

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Sounds like a discrepancy in the Storage Drawers mod. Could you report this to their issue tracker?

**Comment by Jack-McKalling** [comment]
I also experience this issue. Goin to try to get them to look into this.
Also I want to mention this only happens if the drawer controller slave, is a remote location as opposed to a direct connection. In other words, importing from the slave works fine, just not exporting to something else.

**Comment by wrincewind** [comment]
I'm playing around with the Storage Terminal from Integrated Terminals and i can confirm that the behaviour is the same there - the terminal can connect to the controller, but not to the slave.
