### ISSUE TITLE
Unable to milk a cow. Is it possible?

### ISSUE THREAD

**Issue by cgarz** [CyclopsMC/IntegratedTunnels#210]
Sorry to bother you but I have looked around and cant see any information regarding this use case.
I've messed about for a few hours now with fluid importers, world fluid importers and player simulators set to right click with an empty bucket.

However no matter what I've tried I can't seem to get it to work.

Is it actually possible or am I missing something obvious?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by cgarz** [comment]
Ah that's perfect thanks. I actually had a look for a discord on the curse and readme.md pages before posting here.

**Comment by rubensworks** [comment]
It definitely should be, yes. I remember this working in the past at least, just via an item-right click with empty bucket item in the player simulator.

Should this not be working anymore in the latest version, be sure to submit a bug report.

**Comment by cgarz** [comment]
Sorry for being slow. It seems the problem is on my server's modpack configuration or something. It's McEternal.

I have since tested with only ID and IT and it works fine.
I even also tested playing on the modpack locally and it strangely worked fine.
