### ISSUE TITLE
Wrenched cable parts cannot be crafted back into themselves anymore to remove Part ID and NBT data etc

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedTunnels#214]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If you use the wrench to pick up a cable part such as an Item Interface or an Energy Importer, it will retain its Part ID. It used to be possible to remove that data again so the item can stack with others once more, by crafting it by itself. This recipe seems to have been removed or broken as none of the items give any output in a crafting grid.

#### Steps to reproduce the problem:

1. Place a Logic Cable
2. Attach any part to it (e.g. Item Interface, but I tested all cable parts)
3. Go into Survival mode
3. Now shift-rightclick the Item Interface with an Integrated Dynamics Wrench
4. Place the picked up item in your crafting grid (inventory)
  ❌ the recipe gives no output result

#### Expected behaviour:

The recipe output should be a newly crafted version of the item, with no ID or placement data attached to it anymore, just like how it currently does that for **all** Integrated Dynamics parts, and just like it did for all Integrated Tunnels parts in the 1.12 version.

The only way of converting such a "wrenched" part now, is by mining it with a pickaxe, which is much slower and inconsistent with the base mod.

____

#### Versions:

- Integrated Tunnels: 1.16.4 - 1.6.16
- Integrated Dynamics: 1.16.5 - 1.5.0
- Common capabilities: 1.16.5 - 2.5.6
- Cyclops core: 1.16.5 - 1.11.3
- Minecraft: 1.16.5
- Forge: 36.0.43

**Comment by rubensworks** [comment]
Thanks for reporting!
