### ISSUE TITLE
[1.16.5] Mod Compat Crash

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/IntegratedTunnels#218]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1595#issuecomment-794305999
See https://github.com/NillerMedDild/Enigmatica6/issues/1595#issuecomment-793471520 for an idea of what could be the cause

#### Issue type:

- :bug: Bug 

____

#### Short description:

On a dedicated server, setting up a Powah Creative Capacitor -> (Energy Importer -> Logic Cable -> Energy Interface) -> Refined Storage Crafting Grid and then opening the energy importer's GUI crashed my client

#### Steps to reproduce the problem:

1. On a dedicated server, place down a Powah Creative Capacitor. Adjacent to that, place a Logic Cable. Adjacent to this Logic Cable, place any energy storage device (I used an Integrated Dynamics Energy Battery), and a Refined Storage Controller. Adjacent to the Controller, place a Crafting Grid, so the Controller uses energy.
2. Attach an Energy Importer to the Creative Capacitor, and Energy Interfaces on the Battery and Controller.
3. In the Energy Importer, put a Variable Card in the "Import Energy" function. To speed up the process, change the rate to 10000.
4. Once both energy receivers are full, change the "Import Energy" Round Robin setting to `true`. This should crash the server.

#### Expected behaviour:

No crash

____

#### Versions:

- This mod: IntegratedTunnels-1.16.5-1.6.17
- Minecraft: 1.16.5
- Forge: 1.16.5-36.0.44

Happens in Enigmatica 6 v0.4.3, looking at the stacktrace this is most likely reproducible with:
- Powah (+lib)
- Refined Storage
- Integrated Tunnels/Dynamics (+lib)

#### Log file:

[2021-03-09-1.log](https://github.com/NillerMedDild/Enigmatica6/files/6110693/2021-03-09-1.log)

Other similar Round Robin crash:
[2021-03-09-2.log](https://github.com/NillerMedDild/Enigmatica6/files/6110722/2021-03-09-2.log)
[2021-03-09-1.log](https://github.com/NillerMedDild/Enigmatica6/files/6110724/2021-03-09-1.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This seems to be the same problem as https://github.com/CyclopsMC/IntegratedDynamics/issues/999, which has actually been fixed as of ID 1.5.1 (you seem to be using 1.5.0).

**Comment by NielsPilgaard** [comment]
Ah my bad, didn't check Integrated Dynamics for duplicates. Thank you!
