### ISSUE TITLE
Player Simulator crashes when using an item that applies a potion effect

### ISSUE THREAD

**Issue by jeremiahwinsley** [CyclopsMC/IntegratedTunnels#219]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using an item that applies a potion effect, such as an Allthemodium Carrot from Allthemodium, the server crashes.

This seems to be related to https://github.com/MinecraftForge/MinecraftForge/issues/6358

____

#### Versions:

- This mod: 1.6.17
- Minecraft: 1.16.5
- Forge: 36.0.46

#### Log file:

https://gist.github.com/jeremiahwinsley/bdde0d70292ff35a2706de2522baa5f9

**Comment by rubensworks** [comment]
Thanks for reporting!
