### ISSUE TITLE
Inconsistency: Item Exporter, Enchanted Books

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedTunnels#22]
-When using a variable Item("Enchanted Book") on an item exporter, the Filter is too strict. The resulting variable says "Enchanted Book" however, it will not accept any Enchanted Book, only the book with the specific enchantment with the variable was created with.

**Comment by rubensworks** [comment]
You should be able to disable NBT matching in the aspect settings
