### ISSUE TITLE
Milking cows player simulator

### ISSUE THREAD

**Issue by PandaGamersHDNL** [CyclopsMC/IntegratedTunnels#220]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using the player simulator to milk cows the bucket disappears. You hear the "milking cow" sound. But when putting water infront of it it does pick it up and gets put in the chest.

#### Steps to reproduce the problem:

1. place a chest put in some buckets.
2. place an interface on the chest
3. place a player simulator
4. add variable card of a bucket in the "click item" category
5. connect with logic cable
6. put cow infront of player simulator

#### Expected behaviour:

Milk buckets in the chest after the "milking cow" sound is heard
____

#### Versions:

- This mod: IntegratedTunnels-1.16.5-1.7.0
- IntegratedDynamics-1.16.5-1.6.1.jar
- CommonCapabilities-1.16.5-2.5.7.jar
- CyclopsCore-1.16.5-1.11.4.jar
- Minecraft: 1.16.5
- Forge: 36.1.3

#### Log file:
[latestlogs.txt](https://pastebin.com/pj13uyX1)

**Comment by rubensworks** [comment]
Thanks for reporting!
