### ISSUE TITLE
[1.16]  Mekanism + Integrated Tunnels crash

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTunnels#223]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I have found a consistent server crash that happens when exporting power to a power cube via integrated dynamics power interfaces.
#### Steps to reproduce the problem:

1. Connect a full and empty power cube via integrated dynamics power interface and exporter respectively
2. Set the exporter to export power by giving it a blank variable card
3. When the power cube fills, the server will crash with a java.lang.StackOverflowError

#### Expected behaviour:

 I expected the power cube to fill properly when being fed power via an integrated tunnel
____

#### Versions:

- This mod: 1.7.0
- Minecraft: 1.16
- Forge: 36.1.0

#### Log file:
[crash-2021-04-11_15.24.36-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/6293106/crash-2021-04-11_15.24.36-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to the latest CommonCapabilities version, it has been fixed there.
