### ISSUE TITLE
Item Interface/Storage Terminal not requiring power

### ISSUE THREAD

**Issue by rckymtnrfc** [CyclopsMC/IntegratedTunnels#224]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The item interface and storage terminal are allowing pulling (and putting) items to/from the network inventory without power in the network

#### Steps to reproduce the problem:

I just dropped down 2 chests (with some items inside), connected an item interface to each,, ran some cable between the two and the connected a Storage Interface.  I'm able to add or remove items from the network.  No power is connected.

I do have interfaceItemBaseConsumption = 10  and terminalStorageBaseConsumption = 20 in the configs.

#### Expected behaviour:

Expected it to use power

____

#### Versions:

- Integrated Dynamics: 1.7.2
- Integrated Terminals: 1.2.2
- Integrated Tunnels: 1.7.1
- CyclopsCore: 1.11.5
- CommonCapabilities: 2.6.0
- JEI: 7.6.4.88
- Minecraft: 1.16.5
- Forge: 36.1.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You also need to configure `energyConsumptionMultiplier` in Integrated Dynamics for this to work.

**Comment by rckymtnrfc** [comment]
energyConsumptionMultiplier = 20 in my config

**Comment by rubensworks** [comment]
Then that may be a bug.
