### ISSUE TITLE
Crash with Player Simulator after updating to newest version

### ISSUE THREAD

**Issue by Kyiki-Nasoka** [CyclopsMC/IntegratedTunnels#227]
#### Issue type:

- :bug: Bug 

____

#### Short description:
 Game crash on network edit with Player Simulator

#### Steps to reproduce the problem:

Appears to be after updating mod from InDy 1.16.5-1.7.2 and InTu 1.16.5-1.7.1 to InDy 1.16.5-1.8.0 and InTu 1.16.5-1.8.0
Removing cards from Player Simulator (Clicking Shears) allows network to be edited. Other parts can be interacted with and cards inserted / removed. Replacing card into Simulator crashes. Replacing Simulators does not fix issue

#### Expected behaviour:
In-game error for player mistake or not crashing

____

#### Versions:

- This mod:  InTu 1.16.5-1.8.0,
- Minecraft: 1.16.5
- Forge: 36.1.4

#### Log file:
Crash after locating issue to player simulators: https://pastebin.com/NaG5Es41
Had a crash while dealing with something right before update that may be relevant: https://pastebin.com/55MXgQim

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Has already been fixed in dev (d4de7c1c63a3a29a41052345e245c71ea0860c5d), will be released soon!
