### ISSUE TITLE
[1.12.2] Mod Interaction bug: Thermal Expansion Cache and Item Interface

### ISSUE THREAD

**Issue by HexArtificerUK** [CyclopsMC/IntegratedTunnels#228]
#### Issue type:

- :bug: Bug 

____

#### Short description:

There are two issues I've noticed.
Firstly, when the interface extracts the final item, it 'unlocks' the cache, allowing any other item to flow in.. that shouldn't happen.
Secondly, and more importantly.. It seems items get deleted.
#### Steps to reproduce the problem:

Since explaining it is a bit complicated, I just made a [short video](https://youtu.be/iWGU3b_iLR0) instead.
#### Expected behaviour:

Items being extracted from the cache without being deleted and if the final item is removed, the cache should remain locked.
____

#### Versions:

Discovered in:
- This mod: 1.12.2-1.6.12
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

Tested in:
- This mod: 1.12.2-1.6.14
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

The issue was first discovered in CompactClaustrophobia, but I can confirm that it still occurs with just the following:
```
Non-Content Mods:
CyclopsCore,
CodeChicken Lib,
Redstone Flux,
CoFH Core,
CoFH World,
CommonCapabilities

Content Mods:
Thermal Foundation (Dependency for Thermal Expansion),
Thermal Expansion,
Integrated Dynamics,
Integrated Tunnels
```

#### Log file:

No log generated.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by HexArtificerUK** [comment]
No problem!

Just to add onto it:
I noticed that test was heavily based on manually adding items to the cache, which might have affected things... so I tested again with using a hopper to pump into the cache.  Video [here](https://www.youtube.com/watch?v=l8RGu6K1N6s)

The result is the same as single clicking the cache manually- Everything gets deleted.

**Comment by rubensworks** [comment]
Sounds like a bug in TE.
1.12 is not being maintained anymore, so there's not much I can do about it unfortunately.
Feel free to re-open this issue if it should still occur in MC 1.16.
