### ISSUE TITLE
Crash when block importer break a block in its network.

### ISSUE THREAD

**Issue by shBLOCK** [CyclopsMC/IntegratedTunnels#229]
#### Issue type:
- :bug: Bug 

#### Short description:
Crash when block importer break a block in its network.

#### Steps to reproduce the problem:
1. Setup a network like this:
![java_nzLTXGJ5Aq](https://user-images.githubusercontent.com/50770712/120097965-f5862900-c165-11eb-842b-46a7bfeb717b.png)
2. Let the world block importer break the variable store.

#### Log file:
https://pastebin.com/fgqctYsj

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please update to MC 1.16.
