### ISSUE TITLE
Unloaded chunks ticking crash

### ISSUE THREAD

**Issue by tommyTT** [CyclopsMC/IntegratedTunnels#23]
Forge log link:
https://hastebin.com/imijadahif
https://hastebin.com/narojayevu (Crash Report)

Problem:
The game crashed with an NPE.

Expected behaviour:
No crashes :)

Steps to reproduce the problem:
This is hard to reproduce, I wasn't able to recreate this. The crash from the log happened as followed:
- Setup a forestry squeezer that processes the menril logs.  
- Use a fluid interface on the squeezer and a fluid exporter on a drying basin and export all fluids.
- Have an item importer on the drying basin and an iteminterface on a vanilla chest. The importer imports everything from the basin.
The strange thing is, that this happened while I was in the nether. Since I don't have any chunkloaders setup, the whole system shouldn't been running.

**Comment by rubensworks** [comment]
Strange, this should've been fixed already...
But your using the latest ID version, so I guess there's still something wrong.
I'll look into it.

**Comment by Silvrus** [comment]
Confirming the issue. Single fluid interface and extractor on my smeltery. Crash log is [here](https://gist.github.com/Silvrus/84835089fcb49491f35e06ca1df45030)

**Comment by rubensworks** [comment]
I've been able to reproduce this in an SSP environment, for some reason it doesn't occur in SMP.
If someone would encounter this error in SMP as well, please let me know.

I'm looking into resolving this issue, but it's a tricky one...

**Comment by rubensworks** [comment]
Fixed in Integrated Dynamics `0.6.10`. Please comment with a crashlog if you would still encounter the issue.
