### ISSUE TITLE
Network corrupted after server restart

### ISSUE THREAD

**Issue by x13x54** [CyclopsMC/IntegratedTunnels#230]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When making a network using fluid/item importer/exporter/interface (only tested these so far) it will corrupt itself on a server reboot.
Reseating the variable card does not fix the corrupt network, breaking the im/exporter and placing it back with the same variable card does fix it.
This issue seems to not affect IntegratedDynamics networks.

#### Steps to reproduce the problem:

1. Make the simplest item/fluid transfer thing you can (interface, im/exporter, 1 variable card)
2. Reboot the server
3. Network corrupted

#### Expected behaviour:
Server reboot does not affect network negatively. It will keep piping through items/fluids when fed.

____

#### Versions:

Server is using:
IntegratedCrafting-1.16.5-1.0.15.jar
IntegratedDynamics-1.16.5-1.8.3.jar
IntegratedTerminals-1.16.5-1.2.4.jar
IntegratedTunnels-1.16.5-1.8.1.jar
- Minecraft: 1.16.5
- Forge: 36.1.24

Mods are used as part of AllTheMods6 1.6.7 modpack, and i have filed an issue with the modpack as well at https://github.com/AllTheMods/ATM-6/issues/1761

#### Log file:
Nothing of interest has been found in the logs during discovery of network corruption or when searching for integrated* to find possible logs during server startup, however logs can be requested.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by x13x54** [comment]
Sure thing! I'm barely getting started but i like the mod already

**Comment by x13x54** [comment]
After another restart i noticed that breaking the item interface and placing it back also repairs the network (or creates a new one).
Since the chunks are force-loaded this can be the same issue as #124

**Comment by rubensworks** [comment]
Could you try reproducing without any other mods installed?

**Comment by x13x54** [comment]
I can try in the near future. Are you able to reproduce the issue?
