### ISSUE TITLE
Fluid Exporter not exporting fluid

### ISSUE THREAD

**Issue by DraGonFiirE** [CyclopsMC/IntegratedTunnels#233]
#### Issue type:

- :bug: Bug

____

#### Short description:

Fluid Exporter is not exporting fluid when using a list and `check fluid amount` is set to `true`

#### Steps to reproduce the problem:

1. Have 3 tanks of some sort filled with different fluids and have fluid interfaces attached to them
2. Put one tank down and attach a Fluid Exporter to it
3. In the LP make a list with the 3 different fluids (1000mb each) you have put in the tanks
4. In the Fluid Exporter change the property in the `Export Fluids` aspect: `check fluid amount ` to `true`
5. Insert your List of fluids
6. Nothing happens

#### Expected behaviour:

One of the fluids gets inserted into the tank by exporting 1000mb per tick, not less

____

#### Versions:

- This mod: IntegratedTunnels-1.16.5-1.8.1
- IntegratedDynamics-1.16.5-1.8.2
- CommonCapabilities-1.16.5-2.7.0
- CyclopsCore-1.16.5-1.11.6
- Mekanism: 1.16.5-10.0.21.448
- Minecraft: 1.16.5
- Forge: forge-1.16.5-36.1.16

![grafik](https://user-images.githubusercontent.com/75578285/124368086-9ed8a700-dc5d-11eb-9a5e-2fe4c1960694.png)
Im pretty sure its not a Mekanism issue as I've tested other mods tanks aswell

**Comment by rubensworks** [comment]
Thanks for reporting!
