### ISSUE TITLE
Filtering interfaces: craft ID reset.

### ISSUE THREAD

**Issue by User-green** [CyclopsMC/IntegratedTunnels#234]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Filtering item interfaces have no way of reseting ID. 

#### Steps to reproduce the problem:

None. Issue present by default.
You may whant to check it with JEI, however. 

#### Expected behaviour:

Filtering item interfaces resets ID after been processed in crafting grid. 
____

#### Versions:

- This mod: 
1.8.1
- Minecraft: 
1.16.5
- Forge: 36.1.0

**Mod assembly is used!** 
However, I am shure that any other mods IS NOT responsibe for this issue, because all other mods targets world generation, not crafting or player's GUI.

#### Log file:

None, due to issue been non-faliature.

Aditional logs may be collected if needed

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by User-green** [comment]
Also present on "clear" IntegratedDynamics-1.16.5-1.8.5 + IntegratedTunnels-1.16.5-1.8.3 + CommonCapabilities-1.16.5-2.7.0 + CyclopsCore-1.16.5-1.11.7.
