### ISSUE TITLE
World Item Importer server crash

### ISSUE THREAD

**Issue by lavraleksej** [CyclopsMC/IntegratedTunnels#235]
#### Issue type:

- :bug: Bug 

____

#### Short description:

A World Item Importer with Import Items from Entities Boolean card causes a server crash upon card insertion, even with no entities in range
#### Steps to reproduce the problem:

1. Place down a World Item Importer
2. Place a blank variable card into the Import Items from Entities aspect
____

#### Versions:

- Integrated Mods:
IntegratedCrafting-1.16.5-1.0.15.jar
IntegratedDynamics-1.16.5-1.8.2.jar
IntegratedTerminals-1.16.5-1.2.3.jar
IntegratedTunnels-1.16.5-1.8.1.jar 
- CyclopsCore-1.16.5-1.11.6.jar
- Minecraft: 1.16.5
- Forge: 36.1.25
- Modpack: Stacia Expert 1.11.4

#### Log file:

[crash-2021-07-07_16.45.41-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/6777730/crash-2021-07-07_16.45.41-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You're not using the latest mod version.
