### ISSUE TITLE
Player Simulator causes crashes

### ISSUE THREAD

**Issue by TheTechPny** [CyclopsMC/IntegratedTunnels#236]
#### Issue type: 
:bug: Bug

____

#### Short description:
Looks like player simulators crash my server

#### Steps to reproduce the problem:
Place down a player simulator

____

#### Expected behaviour:
Not to crash

____

#### Versions: 
- This mod: 1.8.4
- Minecraft: 1.16.5
- Forge: forge-1.16.5-36.1.32

____

#### Log file:
https://pastebin.com/paDeCx0V

**Comment by rubensworks** [comment]
Could you share some more detailed steps to reproduce the problem?

Does this always occur? Or just in some specific scenarios?

**Comment by TheTechPny** [comment]
> Could you share some more detailed steps to reproduce the problem?
> 
> Does this always occur? Or just in some specific scenarios?

Void Dimension from Just Another Void Dimension mod

**Comment by rubensworks** [comment]
> Void Dimension from Just Another Void Dimension mod

Yeah, I'm going to need more information than that...

**Comment by TheTechPny** [comment]
I removed the void dimension addon and it seems to be working fine. The problem occurred when a player simulator was placed in javd:void the server would crash. I opened this ticket before I had enough information to properly diagnose the problem, sorry.
