### ISSUE TITLE
Server crash due to interaction between Integrated Tunnels and GregTech Community Edition

### ISSUE THREAD

**Issue by Ropuce** [CyclopsMC/IntegratedTunnels#238]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Server crashes when trying to insert into a GTCE input bus. This happened while I was (re-)building my ore processing setup in the FTB Interactions modpack (more specifically version 2.0.10, though it's not official).

(also crashes if played on singleplayer)

#### Steps to reproduce the problem:

GTCE = GregTech Community Edition

1. Connect an item interface to a GTCE output bus set to channel 15. The output bus should NOT be facing the interface to avoid GTCE pushing items into ANY inventory in the system.
2. Connect the logic cables into a compact machine.
3. Within the Compact machine, place a GTCE crate with an exporter set to import all items from channel 15, round-robin set to true and with an item rate of 6400.
4. On the same crate, put an item interface set to channel 11.
5. Place another crate down with an exporter with the same configuration as the previous one, except channel, which is set to 11. The crate has an Ore Dictionary Filter attached to it, configured to insert items of a general OreDictionary entry (example: "crushedPurified*").
6. Attach a conveyor on the crate to export into another inventory, which has an item exporter set to channel 12, 6400 items per operation.
7. Outside the Compact Machine, place an item interface on an input bus and set it to channel 12. Like the output bus, the input bus shouldn't be pointing toward the item interface to avoid GTCE from pulling from any inventory in the system.

At this point the server should crash soon (maybe sooner, I have a suspicion it's the output bus and not the input bus that causes this crash).

No other GTCE machine or part causes my local server to crash so far, or at least not this consistently.

Attached to this issue is my test world in which the crash happens not long after you disconnect and reconnect the cables connected to one of the compact machines.

#### Expected behaviour:

Fast, filtered item transfer with buffer for ore processing purposes with no server crashing.

____

#### Versions:

- This mod: 1.6.12
- CommonCapabilities: 2.4.6
- Compact Machines 3: 3.0.18-b278
- GTCE: 1.10.1.557
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

This bug was found while playing the FTB Interactions modpack on version 2.0.10 (unofficial)

#### Log file:

https://pastebin.com/W7uzLuZz

I'm reporting this here as it seems the crash is caused by Integrated Tunnels or one of its dependencies. I'm sorry if I should've reported this somewhere else.

Edit: Forgot to attach the test world (oops!)
[Test World.zip](https://github.com/CyclopsMC/IntegratedTunnels/files/6978593/Test.World.zip)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
It looks like GT is exposing incorrect slot counts, which makes IT interact with slots that don't exist, hence the crash.

Could you report this to their issue tracker?

**Comment by Ropuce** [comment]
Thank you for the clarification, I'll report it as soon as possible

**Comment by rubensworks** [comment]
Closing this one here in the meantime. Feel free to comment when there is anything required on this end.
