### ISSUE TITLE
Modular Tunnels Parts

### ISSUE THREAD

**Issue by bangplaysgames** [CyclopsMC/IntegratedTunnels#239]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Would it be possible some time in the future to create a means of having multiple tunnel parts inhabit the same block space and direction?  My thought is to have a "Modular Interface" which could then be combined with other parts to grant their functionalities.  Need to insert redstone and extract destabilized redstone from a thermal magma crucible?  Combine a fluid importer and an item exporter with a Modular Interface, and use 2 variable cards.  Want to provide power also?  Add an energy exporter and another variable card to the mix.  Admittedly, this is mainly a request to beautify my IT builds, but it's one function that I feel has always been lacking.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Merging this into https://github.com/CyclopsMC/IntegratedDynamics/issues/278
