### ISSUE TITLE
Check stack size missing for some transfers; not working correctly if available // Items destroyed

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedTunnels#240]
#### Issue type:

- :bug: Bug 

____

#### Short description:

1) 
Function "exact amount" disappeared from export options by commit
https://github.com/CyclopsMC/IntegratedTunnels/commit/6549b163d534f88048257dfbb3278e4cc5feac27
Was not replaced by "check stack size"

2)
New function does transfer less than the configured stack size by combining multiple stacks

#### Steps to reproduce the problem:

On the entries that offer "check stack size" it did work, but most entries did not have that option to begin with.

E.g. "Export all items":

Channel
Round-Robin
Item Transfer Rate
Item slot
Passive Interaction
No "check stack size".

I just tested it with a multiservo press (Thermal):
Chest → Export Item, card = empty item card, transfer rate = 9, Slot = -1, Check Stack Size = true, Empty is wildcard; rest unchanged.

Put two charcoal into the chest, each being one stack. Both are inside the Multiservo Press.

Test again, Slot = 0: Same.

#### Expected behaviour:

1)
All entries should offer to transfer exactly the stack size. It makes sense because "Export (specific) Item, but item is wildcard" does the same as "Export all items"

2) Even if there are multiple stacks they should only be transferred if they combine to the correct amount of items.

3) Ceterum censeo that "Exact amount" was the better name

____

#### Versions:

- This mod: IntegratedTunnels-1.16.5-1.8.5.jar

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by 7eggert** [comment]
Now I tested it with the same setup as above, but with a copper collossal chest. Now it does transfer even if the things are on one stack.

Next problem: I have a stack of 8 Futurecraft zinc that can't be accepted by the multiservo press, (transfer amount is 9), next stack is 25 redstone and it doesn't transfer. Third is 3 Lapis. Take away the zinc ingots and quickly put them in a slot a row below: All the items get transferred but 6 zinc remain. The machine briefly tries to run but then the input slot is empty, no output in target chest either. **The items are destroyed.**
