### ISSUE TITLE
Item Interface can transfer items when not connected to a Logic Cable directly

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedTunnels#243]
#### Issue type:

- :bug: Bug 

____

#### Short description:

An Item Interface doesn't need to be attached to a Logic Cable in its own blockspace (as long as its blockspace is adjacent to a Logic Cable) for it to be targetable by an Item Exporter. Eventhough you cannot open it for configuration.

#### Steps to reproduce the problem:

1. Place two chests next to each other but with a gap of 2 blocks in between
2. Place one Logic Cable in the gap next to the chest on the right
3. Place an Item Exporter between that chest and the Logic Cable
4. Insert a blank Variable Card into the Item Exporter
5. Insert a random item into the left chest (I used another blank Variable Card in video below)
6. Attach an Item Interface to the left chest, in the space between it and the Logic Cable
   → ❌ Notice that the item has moved to the right chest, eventhough the Item Interface doesn't connect to the Logic Cable
   → ❌ Also note that while this is the case, you can still not right-click the Item Interface to configure it

![Magic item transfer](https://user-images.githubusercontent.com/14236702/132107869-d28320e8-1d1e-4636-ada7-cd13e64bc3d9.png)

Video: https://drive.google.com/file/d/1YzrSodjTQjp-OH0iTPpizWWYeO9aamxF/view?usp=sharing

#### Expected behaviour:

When a cable part doesn't connect to a network directly yet because it is missing a cable, I would expect it not to be able to perform its function.

#### Further testing:

It doesn't matter in which blockspace the Item Interface is placed, as long as that blockspace is adjacent to a Logic Cable of the network in question. Items are not transferred as intended if the Logic Cable is more than 1 block away. It seems that the Logic Cable requirement only applies to opening the part GUI, but not to the part's function, as long as it would connect to the network if it had a Logic Cable of its own.

____

#### Versions:

- Dynamics: 1.9.4
- This mod: 1.8.6
- Core: 1.11.9
- CC: 2.7.0
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
When following your steps, the item in the chest is (correctly) not moved, so it seems I can not reproduce your problem.
Can you try again and double-check the steps to reproduce?
If you can still reproduce it, please share a minimal world with me.

**Comment by Jack-McKalling** [comment]
Strange, that you cannot reproduce it. I just created a blank world with the exact setup and it still happens exactly the same.
World download:
[Spooky Action At A Distance.zip](https://github.com/CyclopsMC/IntegratedTunnels/files/7194720/Spooky.Action.At.A.Distance.zip)

Dynamics: 1.9.4
Tunnels: 1.8.6
Core: 1.11.9
CC: 2.7.0
Minecraft: 1.16.5
Forge: 36.2.5

**Comment by rubensworks** [comment]
Thanks, managed to reproduce it. Looks like it is related to a recent Forge version.
