### ISSUE TITLE
Non-stackable items ignore priority

### ISSUE THREAD

**Issue by callmejay758** [CyclopsMC/IntegratedTunnels#244]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Non-stackable items don't seem to respect priority when being exported. The behavior is not observed in importers in my brief testing. In further testing, it seems to be using metadata for priority instead. I used priority 1 wooden swords and priority 0 diamond pickaxes and then I flipped the priorities. In both cases wooden swords took priority.

#### Steps to reproduce the problem:

1. Set up three inventories.
2. Attach two interfaces & 1 exporter.
3. Change one of the interface's priority to anything above 0
4. Place non-stackable items into the lower priority inventory & stackable items into the higher priority inventory.
5. Allow exporting with a variable card.

https://user-images.githubusercontent.com/37318891/134012999-7f1812a3-03ec-46ee-8fee-956a06d61f89.mp4

#### Expected behaviour:

Stackable items having equal priority in exporters.

____

#### Versions:

- This mod: 1.8.6
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Just non-stackable items? Or are there priority problems with regular items (like stone types) as well?

**Comment by Jack-McKalling** [comment]
I tested Stone with Grass Block, and it seemed to work just fine with those. It may not necessarily be "non-stackable" though, if there is another reason why wooden swords are different from these blocks as far as the system is concerned.

I also tested the same setup but with the two input chests vertically organized. The result is the same as the horizontal setup from the above video.

Lastly I also tested switching the priorities and contents of the two input chests, and as long as the wooden sword has lower priority than the stone, the wooden sword was transported first no matter in which chest it came from. So from that logic, "distance" is not affecting the problem.

**Comment by callmejay758** [comment]
I tested basalt & cobblestone. Cobblestone takes priority in both cases. It also seems to be affecting regular items and the title should be updated.

**Comment by rubensworks** [comment]
Thanks for checking. So priorities are just not working anymore.

**Comment by Jack-McKalling** [comment]
Just checked whether the order of placement for the interfaces matters, and it doesn't.

Also tested reorienting the whole setup in a different cardinal direction, and this _does_ affect the issue.
So either it is not the priority that is broken but something else related to the (facing)direction, or the priority is broken and because of that the direction is what next influences the order.
