### ISSUE TITLE
Item Interfaces not accepting "ticks per operation" other than 1

### ISSUE THREAD

**Issue by SirGeremiah** [CyclopsMC/IntegratedTunnels#245]
#### Issue type:

- :bug: Bug 

____

#### Short description:

On standard item interface (not filtering version), it won't accept a tick value higher than 1.

#### Steps to reproduce the problem:

1. Add item interface on an inventory.
2. Enter GUI and set ticks per operation to any number other than 1 (type or use iterating buttons - I tried multiple values up to 20).
3. Click Save.
4. Value reverts to 1.

#### Expected behaviour:

Entered value should be accepted.
____

#### Versions:

- This mod: InDy 1.10.2, InTu 1.8.6
- Minecraft: 1.16.5
- Forge: 36.2.4

This has been replicated by met4000 in a clean test world, InDy 1.10.2, InTu 1.8.6.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I can also reproduce this. The GUI does save settings, as I can successfully change the side setting from east to down for instance, it's just the ticks setting specifically.

And I'm using Forge version 36.2.8 even.
