### ISSUE TITLE
README file has broken link

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedTunnels#246]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The link to the download page for Lombok plugins is dead. It has an incorrect file extension, currently it is `download.htm` but it should be `download.html`.

I found this by trying out various file extensions, and everything but the HTML one gave me a 404. This one just redirects to the correct page (which has no extension, so you could also just remove it altogether).

#### Steps to reproduce the problem:

1. Go to https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.16/README.md
2. Click the "here" link at the bottom
3. Notice the 404 page

#### Expected behaviour:

The link should not give a 404

____

#### Versions:

- This mod: see the github link in repro steps
- Minecraft: 1.16.5
- Forge: n/a

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This change will probably be needed for all Cyclops repos. PRs are welcome.

**Comment by Jack-McKalling** [comment]
Actually Integrated Dynamics is fine, that's why I reported it here.
But some other repos do indeed also have the problem, so I'll see what I can do

**Comment by Jack-McKalling** [comment]
Oh man this is going to take a while. I have to sign the CLA for all 18 of the affected projects? :(

**Comment by rubensworks** [comment]
The CLA should be Cyclops organization-wide.

**Comment by Jack-McKalling** [comment]
There, 18 PRs done. A note however, the following repos didn't require an approval of a maintainer while all others did:
- EverlastingAbilities-PotionCore
- EnergySynergy
- FluidConverters
- CompressedChests

**Comment by rubensworks** [comment]
Super, thanks a lot! :-)
