### ISSUE TITLE
Buckets being deleted when filling a tank with a player simulator

### ISSUE THREAD

**Issue by JunaidA197** [CyclopsMC/IntegratedTunnels#248]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When the tank is full, the player simulator deletes all but one bucket.

#### Steps to reproduce the problem:

1.) Have a milk setup (pictured)
2.) Wait till tank gets full
3.) Watch buckets get deleted

#### Expected behaviour:

When the tank is full, I wouldn't expect buckets to get deleted.
____

#### Versions:

- This mod: 1.8.7
- Minecraft: 1.16.5
- Forge:  Unknown (FtB University 1.3

#### Log file:
![image](https://user-images.githubusercontent.com/44754456/140649482-fcd2eebc-2d58-4c15-833a-3ac067f2e4ff.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Sounds related to #220, and possibly also to CyclopsMC/IntegratedDynamics#1046

**Comment by rubensworks** [comment]
I wasn't able to reproduce this problem with a tank myself (probably the issue doesn't contain much details...).
In any case, I made a minor change that could be related to the problem.
