### ISSUE TITLE
Feature: Allow multiple filters on Exporters?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [CyclopsMC/IntegratedTunnels#25]
Normally you can only use one, like Export all Items, Export Item(s), etc It would be useful to allow us to set multiple conditions. Like Export All Items, and The use of a list, or an item.

**Comment by rubensworks** [comment]
The aspects increase in expressivity, the earlier ones can be expressed in terms of the ones after that, so I see no need for this.

**Comment by BiatuAutMiahn** [comment]
So If i make a condition that is bool, can it still filter out items of a given type? 

In an exporter, I have a var that says if an inventory is less than 2 then return true. But would this work: (Inv()<2&&Item=Blank) Would that work?

**Comment by rubensworks** [comment]
Yes, you can do that using an operator.

**Comment by BiatuAutMiahn** [comment]
ok, cool. The only problem is that I still don't understand how to use those. I get the concept of a lambda, but I don't know how to use an operator.

**Comment by rubensworks** [comment]
I'm writing a manual, in which I will explain operators in detail.

**Comment by BiatuAutMiahn** [comment]
ok, sounds good
