### ISSUE TITLE
Allow in game configuration of time importers/exporter sleep before checking unchanged targets again

### ISSUE THREAD

**Issue by IDontKnow11010111000** [CyclopsMC/IntegratedTunnels#250]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

A field in the configuration options, (wherever the priority is changeable), that allows you to change the "inventoryUnchangedTickTimeout = 1" for importers and exporters.

#### You can ignore this:

When setting up a system to automatically dipper blocks, in ftb ocean block, I had an importer, world block exporter, then a regular item exporter on a chest.  What kept happening was all of the items would end up in the exporter's chest, even when I set up the import logic for importer to only import if there was space to place a block.  Even with the priority of the exporter set to -20, (idk how exactly it works), and the block exporter left at 0, most of the time all of the items ended up in the exporter chest.  After changing that value to 1 in the config, it seems to be working now.  I *could* use two channels, but I dont know, feels like this could be useful elsewhere.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I may be misunderstanding, but we already have such a config option, so there is nothing to be added?

I also don't really understand the use case.
Happy to re-open this issue if you could clarify the use case.
