### ISSUE TITLE
World Fluid Exported cannot replace fluid flow by fluid source

### ISSUE THREAD

**Issue by hohserg1** [CyclopsMC/IntegratedTunnels#251]
#### Issue type:

- :bug: Bug 
- :heavy_plus_sign: Feature request 

____

#### Short description:

World Fluid Exporter cannot place fluid source at fluid flow.

#### Steps to reproduce the problem:

1. Make follow build. Each World Fluid Exporter will place fluid on related button press
![image](https://user-images.githubusercontent.com/35610168/144963513-14282405-3b91-4be8-a675-24da570659b9.png)
2. Press first button => first World Fluid Exporter will place first water source and two other blocks will be filled by water flow
![image](https://user-images.githubusercontent.com/35610168/144963998-654d7eed-0866-42c3-b829-0af704128931.png)
3. Press second button => second World Fluid Exporter will **not** place second water source
4. Press third button => third World Fluid Exporter will **not** place third water source

#### Expected behaviour:

Fluid flow must be replaced by fluid source.
As feature request: add property "Replace flow" to World Fluid Placer

____

#### Versions:

- This mod: IntegratedTunnels-1.12.2-1.6.14
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I'm sorry, but 1.12 is not supported anymore unfortunately.
