### ISSUE TITLE
[1.16.5] duplication bug of item exporter

### ISSUE THREAD

**Issue by KronosX523** [CyclopsMC/IntegratedTunnels#255]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Duplication bug of item exporter, when **Check Stack Size**  is set to true.

#### Steps to reproduce the problem:

1. Place an item interface on a chest, an item exporter on another chest, then conncet them with logic cable.
2. Change the propertis of  Export All Items, set **Check Stack Size**   to true and put on an variable card.
3. Put some diamonds and emrald into the chest with item interface, make sure the sum of their numbers equals **Item Transfer Rate**.
4.You will get the diamond or emrald (It depends on which is more) with a quantity equal to the **Item Transfer Rate**. This bug works for all stackable items.

#### Expected behaviour:
Nothing should be transmitted.

Versions:

- This mod: 1.8.9
- Minecraft: 1.16.5
- Forge: 36.2.34

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by KronosX523** [comment]
[v](https://youtu.be/rAxKOTqCN2U) An video of this.
