### ISSUE TITLE
Crash when matching Immutable block item drop lists

### ISSUE THREAD

**Issue by shBLOCK** [CyclopsMC/IntegratedTunnels#257]
#### Issue type:

- :bug: Bug

____

#### Short description:

Crash when block breaker tries to match a block from a mod that returns its drops as an Immutable list.
The crash happens because it's trying to remove elements from the Immutable list.
See: https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.18/src/main/java/org/cyclops/integratedtunnels/core/ItemStorageBlockWrapper.java#L158
Doing a check and converting it to a Mutable list if needed will fix it I think.

#### Steps to reproduce the problem:

Haven't figured out what block it was breaking when the crash happens, but this should be easy to fix, and probably won't require testing after the fix.

____

#### Versions:

- This mod: 1.18.2-1.8.11
- Minecraft: 1.18.2
- Forge: 40.1.47

#### Log file:

https://pastebin.com/3R6sZzf7

**Comment by rubensworks** [comment]
Thanks for reporting!
