### ISSUE TITLE
"Click with Diamond Sword" advancement given regardless of item

### ISSUE THREAD

**Issue by nskobelevs** [CyclopsMC/IntegratedTunnels#258]
#### Issue type:

- :bug: Bug 

____

#### Short description:

`integratedtunnels.click_sword` advancement "Click with a Diamond Sword" is given for regardless of the item.

In this example, the item was a "Variable Card"

[Demonstration Video](https://user-images.githubusercontent.com/34107736/190727540-5a912577-f13b-498f-a907-001c5a4923c5.mov)

#### Steps to reproduce the problem:

1. Setup a Player Simulator.
2. Add a variable card with any Item variable.

#### Expected behaviour:

The advancement should only be given if the item is a Diamond Sword.

____

#### Versions:

- This mod: 1.8.15
- Integrated Dynamics: 1.11.10
- Cyclops Core: 1.17.10
- CommonCapabilities: 2.8.3
- Minecraft: 1.19.2
- Forge: 43.1.25 and 43.1.1 (Tested 43.1.1 as it's the recommended version in case the issue is a Forge one introduced since then)

**Comment by rubensworks** [comment]
Thanks for reporting!
