### ISSUE TITLE
player simulator doesn't drop broken blocks

### ISSUE THREAD

**Issue by ellisten** [CyclopsMC/IntegratedTunnels#262]
#### Issue type:

- :bug: Bug
____

#### Short description:

player simulator doesn't drop broken blocks

#### Steps to reproduce the problem:

1. set up player simulator with an available tool
2. make it mine the block in front of it

#### Expected behaviour:

drops the broken block if it would drop when mined by a player

____

#### Versions:

- This mod: 1.8.17
- Minecraft: 1.18.2
- Forge: 40.2.1

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by ellisten** [comment]
i don't know too much about modding but it may actually be a Forge problem, currently testing PNC drones and they don't drop blocks when mining either.

**Comment by ellisten** [comment]
it is a me problem, i had tiledrops gamerule disabled....
