### ISSUE TITLE
1.19.2 - Crash when placing logic pipe between ``Mechanical Basin`` and ``Squeezer`` on dedicated server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/IntegratedTunnels#263]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crashed when placing logic pipe from integrated between Mechanical and Drying Basin.

#### Steps to reproduce the problem:

Placed logic pipe or blue tube thing vertically between Mechanical and Drying Basin

#### Expected behavior:

No crash.

____

#### Versions:

- This mod: IntegratedTunnels-1.19.2-1.8.18, IntegratedDynamics-1.19.2-1.15.1.jar, CyclopsCore-1.19.2-1.17.5.jar, ColossalChests-1.19.2-1.8.4.jar, CommonCapabilities-1.19.2-2.9.0.jar, IntegratedTerminals-1.19.2-1.4.4.jar, IntegratedCrafting-1.19.2-1.1.0.jar
- Minecraft: 1.19.2
- Forge: 43.2.6

I don't have time. If the log is not helpful I will just remove mod.

#### Log file:

https://gist.github.com/P3rf3ctXZer0/bac02dfed303269886a2b16f629cfe86

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
That's a crash I have never seen before :O
Can you reproduce this without any other mods installed?

**Comment by P3rf3ctXZer0** [comment]
I don't have time right now ... but I assume it is two parts 1 part tick drop due to server lag other part d-sync. I hope that helps.
