### ISSUE TITLE
Player simulator not attacking 

### ISSUE THREAD

**Issue by phorced** [CyclopsMC/IntegratedTunnels#264]
There seams to be lack of information or I don't understand it correctly the player simulator says that u can auto attack but I can not seam to get it to function at all 

I get it to place blocks and filter block types but it does not work as what is on the label even as the tutorial shows in the book if it does work and I just have no idea or am overlooking something please explain it and maybe the ingame guide book needs more info

**Comment by rubensworks** [comment]
Could you ask your question in our Discord server? https://discord.gg/9yDxubB

<blockquote><img src="https://cdn.discordapp.com/icons/386052815128100865/68f625b3e17e3b805e762a37a4d4e97f.jpg?size=256" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/invite/9yDxubB">Join the CyclopsMC Discord Server!</a></strong></div><div>A place to discuss or ask questions about Cyclops mods. Every mod has its own dedicated channel. | 1,973 members</div></blockquote>
