### ISSUE TITLE
Crash while scrolling down in network reader

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [CyclopsMC/IntegratedTunnels#266]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash
#### Steps to reproduce the problem:

Put network card down with cable and open it, then scroll down

#### Expected behaviour:

____

#### Versions:

Easier to copy paste the list
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      
		IntegratedTunnels-1.19.4-1.8.18.jar               |IntegratedTunnels             |integratedtunnels             |1.8.18              |DONE      
		CyclopsCore-1.19.4-1.18.2.jar                     |Cyclops Core                  |cyclopscore                   |1.18.2              |DONE      
		CommonCapabilities-1.19.4-2.9.0.jar               |CommonCapabilities            |commoncapabilities            |2.9.0               |DONE      
		forge-1.19.4-45.0.55-universal.jar                |Forge                         |forge                         |45.0.55             |DONE      
		IntegratedDynamics-1.19.4-1.16.2.jar              |IntegratedDynamics            |integrateddynamics            |1.16.2              |DONE      
		IntegratedCrafting-1.19.4-1.1.1.jar               |IntegratedCrafting            |integratedcrafting            |1.1.1               |DONE      

#### Log file:

https://pastebin.com/CGMLg0XM

**Comment by rubensworks** [comment]
Thanks for reporting!
