### ISSUE TITLE
Part offset in-world display 'lags' when crouching

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedTunnels#267]
#### Issue type:

- :bug: Bug 

____

#### Short description:

While holding a wrench, parts with a part offset have a 'hologram' of the location they are targeting. This hologram is normally positioned correctly even while the player is moving, however it seems to 'lag' behind when the player crouches (or uncrouches).

#### Steps to reproduce the problem:

1. Set up a part with a part offset
2. Hold a wrench
3. Crouch

Videos

https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/b5d7fb02-dd5c-4e63-8932-3031f92502b0

A [video](https://cdn.discordapp.com/attachments/386054223688630272/1107577429565902918/Minecraft__1.19.2_-_Multiplayer_3rd-party_Server_2023-05-15_02-56-44.mp4) of a different setup on a different machine, from the [discord](https://discord.com/channels/386052815128100865/386054223688630272/1107577430320889876).

#### Expected behaviour:

The hologram is positioned correctly at the target location at all times, with no 'delay' before snapping to the correct location when crouching or uncrouching.

____

#### Versions:

mod | version
--- | ---
MC | 1.19.4
InTu | 1.8.19
InTu Compat | 1.8.19
Cyclops Core | 1.18.2
Common Capabilities | 2.9.0
Forge | 45.0.63
InDy | 1.16.4
InDy Compat | 1.16.4
InCr | 1.1.3
InTerm | 1.4.8
InTerm Compat | 1.4.8
InREST | 1.1.10

**Comment by rubensworks** [comment]
Thanks for reporting!
