### ISSUE TITLE
Interfaces missing part offset settings UI

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedTunnels#268]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Place an interface
2. Use offset part enhancements on it - the normal popup detailing the range increase occurs
3. Open the interface's UI - no interface for the part offset is available

![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/bf3f16e0-e39d-41d0-b52c-c74ab60d479e)

The offset is set by and displayed by the wrench correctly:
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/db573b57-3dba-4889-b213-598ce2ae8eb8)

#### Expected behaviour:

A button to access the part offset settings for the part, like other parts have.

![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/91aef1f3-078b-4dc6-8b9f-38122d07b609)

____

#### Versions:

mod | version
--- | ---
MC | 1.19.4
InTu | 1.8.19
InTu Compat | 1.8.19
Cyclops Core | 1.18.2
Common Capabilities | 2.9.0
Forge | 45.0.63
InDy | 1.16.4
InDy Compat | 1.16.4
InCr | 1.1.3
InTerm | 1.4.8
InTerm Compat | 1.4.8
InREST | 1.1.10

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Hmm, interfaces actually shouldn't accept offset part enhancements, so I'll have to block them from being applied.

**Comment by met4000** [comment]
Can I flip this from a bug report to a feature request then? lol

**Comment by rubensworks** [comment]
Nvm, will enable them in the next version, shouldn't be too difficult :-)
