### ISSUE TITLE
Support for gasses(mekanism)

### ISSUE THREAD

**Issue by Emotional-Support** [CyclopsMC/IntegratedTunnels#269]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

It would be nice if you could look into adding support for mekanism gasses. I know there have been two other requests about this, but both are 5 and 6 years old at this point, so i thought id try asking again. thanks

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Duplicate of #128
