### ISSUE TITLE
Cannot push energy from/to Thermal Expansion machines

### ISSUE THREAD

**Issue by laserswald** [CyclopsMC/IntegratedTunnels#27]
For some reason, the interfaces just won't move any energy. 

I am using the latest Curse release of both. I have one Steam Turbine connected via an Energy Importer / Cable / Energy Interface to a Pulverizer, and fuel and water for the Turbine, with no energy given to the Pulverizer. 

I can give screens and other data if need be.

**Comment by rubensworks** [comment]
Can you send me a screenshot of the setup?
