### ISSUE TITLE
Crash on world load with Mekanism

### ISSUE THREAD

**Issue by dustinsurwill** [CyclopsMC/IntegratedTunnels#270]
#### Issue type:

- :bug: Bug 

____

#### Short description:

World loads then crashes before world renders.

#### Steps to reproduce the problem:

I am not sure. The world was fine when I was last in the world, but now it crashes on load. From memory I can remember that I had the following connections between this mod and Mekanism:
- Energy interface on Mekanism Advanced Universal Cable (~2.2M RF)
- Crafting interface and Item importer on Mekanism tank
- Fluid interface with priority 5 on Mekanism Advanced tank
- Item importer on both Mekanism Enrichment Chamber and Mekanism Metallurgic Infuser

#### Expected behaviour:

World does not crash.

____

#### Versions:

- This mod: 1.8.19
- Minecraft: 1.19.2
- Forge: 43.2.14
- Modpack: ATM8 1.0.21b

![ModList](https://github.com/CyclopsMC/IntegratedTunnels/assets/7518797/fb3a54ca-7d37-4a1c-8e2d-527709963e44)

#### Log file:

[crash-2023-06-25_00.47.37-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/11859092/crash-2023-06-25_00.47.37-server.txt)
[latest.log](https://github.com/CyclopsMC/IntegratedTunnels/files/11859091/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!
