### ISSUE TITLE
'Export Item Predicate' not exporting when multiple valid stacks

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedTunnels#271]
#### Issue type:

- :bug: Bug 

____

#### Short description:

In 1.18, 'export item predicate' aspect of the item exporter does not appear to be slot independent (at least for the predicate given below).
Also occurs in 1.19, ~~but does not on~~ **and** 1.20.

#### Steps to reproduce the problem:

![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/f7064d84-4e58-4fce-a2a5-25411a03f646)
1. setup as in the picture above
2. put an item predicate in the exporter, such as `apply(relationalEquals, variableCardItem)` or `apply(listContains, itemListWithVariableCardItem)` - note that the item stack size is respected by these, so they will only return true for stacks with a size of 1

#### Behaviour:

Placing 1 stack of 2 items in the left chest:
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/17dc4eba-b7c0-4c5f-8b81-a524c8c4d651)
Behaviour: no items are transferred (correct)
Expected behaviour: no items are transferred

Placing 1 stack of 1 item in the left chest:
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/17d219b4-967f-44e5-89cb-1797a514d3c8)
Behaviour: items are transferred (correct)
Expected behaviour: items are transferred

Placing 2 stacks of 1 item in the left chest:
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/d7a75f2f-0c62-4fba-8915-ac3b4468b317)
Behaviour: no items are transferred (incorrect)
Expected behaviour: all items are transferred

i.e.: works correctly, unless there are multiple stacks that should be exported

____

#### Versions:

- Minecraft: 1.18.2
- Forge: 40.1.0

![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/ba74a187-c455-4f0e-a2fd-5ead689d43e3)

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Also occurs in 1.19, but does not on 1.20.

Huh, that's surprising. AFAIK, nothing has changed between these versions related to item transfer or operator handling.

**Comment by met4000** [comment]
Yeah, I went through the diff for 1.18 vs 1.20 for InTu and nothing seemed relevant. It might be a change in InDy or CyclopsCore. Have you been able to reproduce this for yourself on 1.18 vs 1.20?

**Comment by met4000** [comment]
Hmm, nevermind I guess; I just loaded the 1.20 test world back up for something else and it's not working there either - I'm not sure why I thought it was before but I'll put it down to misremembering rather than it actually happening and being inconsistent, at least until I see it actually happen (again?).

**Comment by met4000** [comment]
Might be relevant, or a separate issue; in both 1.18 and 1.20, if you specify a transfer rate and 'check stack size', then exporters work as expected (tested using the 'export item' and 'export item list' aspects). However, if you instead use an importer and interface, it seems to operate 'slot-wise' - with a transfer rate of 48 and 3 stacks of 64 initially in the chest, it transfers three lots of 48 leaving behind 3 stacks of 16, rather than transferring a fourth lot of 48 as well.

![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/022716f9-e41a-4ba0-9693-ebe6c095a71a)
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/15624876/f069b993-5c0d-409b-9bae-b13add864627)
