### ISSUE TITLE
Is Player Simulator able to “use” items?

### ISSUE THREAD

**Issue by neksword** [CyclopsMC/IntegratedTunnels#273]
#### Issue type:

- :question: Question 

____

#### Question:
Hi,
Please see the references issue in IC2 classic issue. https://github.com/TinyModularThings/IC2Classic/issues/859

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by neksword** [comment]
Looks like a bug because I was able to do the same thing with Modular Routers Activator module

**Comment by rubensworks** [comment]
Could you report this as a bug, so I have all of the necessary version information? Thanks!
