### ISSUE TITLE
Item exporter with "Export Items Predicate" ignores channels

### ISSUE THREAD

**Issue by satoon10** [CyclopsMC/IntegratedTunnels#274]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Item exporter with "Export Items Predicate" ignores channels, and exports from any interface connected.
#### Steps to reproduce the problem:

1. Add an Operator card to the "Export Items Predicate" slot on an item exporter;
2. Item export ignores channels and pulls from any interface.

#### Expected behaviour:

Item Exporter export items in the selected channel.

____

#### Versions:

- This mod:  1.8.21
- Minecraft: 1.19.2
- Forge: 34.2.14

**Comment by rubensworks** [comment]
Thanks for reporting!
