### ISSUE TITLE
Crash with world fluid importer filling up spout from Create

### ISSUE THREAD

**Issue by AlexiyOrlov** [CyclopsMC/IntegratedTunnels#275]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Game crashes after Spout from Create filling one bottle with water which is filled with water via integrated cables via World Fluid Importer.

#### Steps to reproduce the problem:

1. Place World fluid importer over a water pool so it extracts the water
2. Insert a card to the 'Pick up all fluids' aspect
3. Place a Depot from Create nearby
4. Place a Spout above the Depot
5. Connect World fluid importer to Spout via Logic cable and fluid interface
6. Place empty bottles on the depot

#### Expected behaviour:

Spout should fill several bottles with water without crashing

____

#### Versions:

- This mod: 1.20.1-1.8.22
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:

[https://pastebin.com/zKmEUEey](url)

**Comment by rubensworks** [comment]
Thanks for reporting!
