### ISSUE TITLE
Part Offset seems to be ignored

### ISSUE THREAD

**Issue by ZeekDaGeek** [CyclopsMC/IntegratedTunnels#277]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When setting an offset for the Item Interface the setting appears to be ignored

#### Steps to reproduce the problem:

1. Set offset on Item Interface.
2. Make sure it's upgraded.
3. Notice how it's not actually drawing from targeted chest.

![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/1709288/18383c46-7e97-4570-86cc-7a8c7568e59c)

____

#### Versions:

- This mod: 1.8.21
- Minecraft: 1.19.2
- Forge: 43.2.14

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by ZeekDaGeek** [comment]
Actually, it appears the issue is a little different than what I reported. If you update the network by adding a new Logic Cable the network appears to update properly and the offset will take effect.

Maybe the problem is more localized to the offset changes not updating the network state.
Assigning values in the UI doesn't update until you physically update the network, and using the wrench to apply the setting has the same problem.
