### ISSUE TITLE
Player Simulator Continuous click not working as expected

### ISSUE THREAD

**Issue by OoTMaestro** [CyclopsMC/IntegratedTunnels#279]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Continuous click not continuous on player simulator, instead simulates spamming right click

#### Steps to reproduce the problem:

1. Have player simulator try to eat any food, use any bow/crossbow, potions work but are instantaneous with 1 tick consumption time. 
2. Try to make player simulator properly use fishing rod will produce fishing rod sound but no line/lure

#### Expected behaviour:

With the settings; right click, right hand, continuous click, expectation is that anything that requires holding down right key will operate, initial issue was with modded items like soul extractor from F&A or horn of the wild from Botania

____

#### Versions:

IntegratedTunnels-1.20.1-1.8.24.jar

- This mod: IntegratedTunnels-1.20.1-1.8.24.jar
- Minecraft: 
- Forge: 47.1.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I've branched this off into two new feature requests:
- https://github.com/CyclopsMC/IntegratedTunnels/issues/280
- https://github.com/CyclopsMC/IntegratedTunnels/issues/281
