### ISSUE TITLE
Exported items from filtered item interfaced inventory disappear

### ISSUE THREAD

**Issue by ChipWolf** [CyclopsMC/IntegratedTunnels#282]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When using a filtering item interface and an item exporter on the network, exported items disappear from the inventory attached to the interface and are not present in the inventory attached to the exporter.

When using a regular item interface, the items appear in the inventory attached to the exporter as expected.

#### Steps to reproduce the problem:

**Demo video:** https://www.youtube.com/watch?v=EZeakkpdUnk

1. Place a sophisticated storage chest adjacent to the sophisticated storage controller.
2. Attach a filtering item interface to the storage controller.
3. Create a variable card configured as virtual piped operator to filter items by name starting with a mod name of your choosing _(I chose `allthecompressed:`)_.
4. Insert a variable card into the filter items predicate slot of the interface.
5. Place a second chest somewhere _(**not** adjacent to the storage controller or the first chest)_
6. Attach an item exporter to the second chest
7. Create a variable card configured as a virtual piped operator to filter items by name, regex matching the mod name of your choosing at the start of the string with some common suffix at the end of the string _(I chose `^allthecompressed:.+_1x$`)_.
8. Insert the variable card into the export items predicate slot of the exporter.
9. Ensure the intermediary variable cards are available in a variable store on the network that is connected to both the interface and the exporter.
10. Insert some items into the first chest that match your startsWith string configured in step 3 of which some match the regex pattern configured in step 7.
11. Note that the items matching the regex pattern disappear from the first chest and are not present in the second.
12. Remove the filtering item interface, replacing it with a regular item interface, repeat step 10 and see the expected output in the second chest.

#### Expected behaviour:

I expect the filtered items to not seemingly disappear into the void.

____

#### Versions:

- This mod: 1.8.24
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
