### ISSUE TITLE
Display panel visibility range with shaders

### ISSUE THREAD

**Issue by jeytee84** [CyclopsMC/IntegratedTunnels#283]
#### Issue type:

- :question: Question 

____

#### Question:

The display panels are only visible from about 3 blocks far with shaders turned on. Wondering if you guys know why this might happen and maybe have any advice on changing particular settings in the shader to make tha panels show properly.

https://imgur.com/a/BxesOaM

Running ATM9 0.2.25 with Complementary Reimagined r5.1.1

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
The render distance is set by default to 15 via `partOverlayRenderdistance` in the config. Perhaps that got changed in your pack?

**Comment by jeytee84** [comment]
I'm sorry i couln't repply earlier. The 15 distence by default is still there, when the shaders is turned off, it is visible from 15.
Only when the shader is turned on, does it reduce to around 3 blocks.

**Comment by rubensworks** [comment]
That's weird. Could you report this to the shader's issue tracker? Sounds like an issue on their end.
