### ISSUE TITLE
Systems not working after login

### ISSUE THREAD

**Issue by jeytee84** [CyclopsMC/IntegratedTunnels#284]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Uppon logging in to my singleplayer world all my ID systems need a "manual restart".

There are 3 systems shown on the videos:
https://imgur.com/a/ApGkGuG
The first one has a machine reader reading and displaying the fill level of a battery and writing a redstone signal if it's bellow a threshold.
https://imgur.com/a/qzlOVzu
The second and third ones are checking the apropriate create machine inventories if they contain any items and turns their motors off via a redstone signal if they dont.

The problem is, that every time I join the game the ID system does nothing and I have to "restart them" by for example reseating some variable cards or putting an item into one of the read inventories.

#### Steps to reproduce the problem:

1. Quit, to title
2. Rejoin singleplayer world

#### Versions:

**ATM9 0.2.25**
IntegratedCrafting-1.20.1-1.1.6.jar
IntegratedDynamics-1.20.1-1.20.2.jar
IntegratedTerminals-1.20.1-1.4.11.jar
IntegratedTunnels-1.20.1-1.8.24.jar
- Minecraft: 
1.20.1
- Forge: 
47.2.14

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
What error message is shown when you hover over the red cross inside the broken parts?

**Comment by jeytee84** [comment]
Yet again sorry for being so late with the response. If I remember correctly it showed an error about a specific variable missing. But I'll do some research on the bug in the next few days when i have some free time.
