### ISSUE TITLE
crash when loading back chunks with item interface

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [CyclopsMC/IntegratedTunnels#287]
#### Issue type:

- :bug: Bug,bug.... bug!

____

#### Short description:

a crash happens after unloading then reloading item interfaces hooked into sophisticated storage chests  and a storage terminal 

i am unsure if its specifically related with sophisticated storage or not, as im playing on a server im hosting, my players wont appreciate me crashing the server now, may update with more tests later

#### Steps to reproduce the problem:

1. set up a  simple storage system that is hooked up with sophisticated storage (unsure if problem happens with 
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/40670872/fd3db972-e4d2-4068-8e2a-588f6ac36e1b)
2.travel away from the setup to unload the chunk
3.come back (teleport back) to the setup
4. ????
5. crash report!! 🥳 

#### Expected behaviour:

hopefully no crashes :)

____

#### Versions:

- integratedtunnels  |1.8.25   
-integrateddynamics|1.21.2 
probable other mods that could be the issue, may update to confirm it later)
-sophisticatedstorage |0.10.10.757 
|sophisticatedcore |0.6.9.569
- Minecraft: 1.20.1
- Forge: 47.2.20

#### Log file:

https://pastebin.com/XTp9MYRw

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by PoptartOverlord-Xabedo** [comment]
i seem to have isolated the issue to be related to my filtered interface that is hooked up to a copper chest, with enchanted book as a variable , set on filter item with NBT disabled
