### ISSUE TITLE
Item Importer Predicate does not respect Round Robin

### ISSUE THREAD

**Issue by Telmooo** [CyclopsMC/IntegratedTunnels#288]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Item Importer with an “Import Items Predicate” does not respect Round Robin option.

#### Steps to reproduce the problem:

1. Create a network with 3 chests, with following layout

|    |   | C2 |   |   |    |
|----|---|----|---|---|----|
| C1 |   |    |   |   | C3 |

2. Chest 1 & 2 have Item Interfaces (default settings).
3. Chest 3 has an Item Importer.
4. Create a Predicate (e.g. Operator :: Item Enchantable), and put in Item Importer with Round Robin active.
5. Fill Chest 3 with Enchanted Items (e.g. Enchanted Armor piece)
6. All the items get placed into Chest 2.

#### Expected behaviour:

Items should be split evenly between Chest 1 and Chest 2.

This expected behaviour is exactly what happens when using the "Import All Items" under the same setup.
____

#### Versions:

- This mod: 1.8.26
- Minecraft: 1.20.1
- Forge: 47.2.20
- Integrated Dynamics: 1.21.3

#### Log file:

None.

**Comment by rubensworks** [comment]
Thanks for reporting!
