### ISSUE TITLE
Interfaces ignore variable cards in offset

### ISSUE THREAD

**Issue by coolbot100s** [CyclopsMC/IntegratedTunnels#289]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Interfaces, such as the item and energy interface will ignore variable cards placed in the offset slots, and always use the manually applied offsets instead. (including no offset if all values == 0)

#### Steps to reproduce the problem:

1. Place any Interface 
2. Apply offset enhancements
3. Insert any variable card into the interface

#### Expected behaviour:

The screenshots below demonstrate the issue, in this case, all 4 parts have an integer variable in the x direction with the value of 2, the Player Simulator and Item Exporter behave as expected, however the Item Interface and Energy Interface ignore the variable cards.
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/76798835/1c75cb80-990f-43b4-83c0-c30e22baf668)
![image](https://github.com/CyclopsMC/IntegratedTunnels/assets/76798835/ff3a00d1-0916-432e-8502-ae91c3951a8b)

From what I can tell this is universal and I've tried to account for any variables and tested this on the latest versions with only the required mods installed on a fresh world and instance.

____

#### Versions:

- This mod: 1.8.26
- Minecraft: 1.20.1
- Forge: 47.2.30

**Comment by rubensworks** [comment]
Thanks for reporting!
