### ISSUE TITLE
Crash when Unpausing Singleplayer while Fluid Tunnels are Unloaded

### ISSUE THREAD

**Issue by Revvilo** [CyclopsMC/IntegratedTunnels#29]
I was trying to set up a lava pump in the nether and had to pause the game for a sec to do something, and when I came back to unpause it, the game crashed immediately.
It's being quite intermittent though, sometimes crashing when unpausing, but sometimes not, I've also had it crash while logging back into the world once.
Crash Log • https://pastebin.com/khcJszXH

**Comment by rubensworks** [comment]
This seems related to #23 which I assumed was fixed.

**Comment by Revvilo** [comment]
Further testing confirms that if I unload a machine involving fluid interfaces and pause and unpause a few times it will crash.

**Comment by rubensworks** [comment]
Thanks for checking, I'll look into it soon.

I was planning on releasing new ID/IT versions soon, but I'll try to resolve this issue before I do that.

**Comment by Revvilo** [comment]
Sounds good :)
Hey also, might be unrelated, but I'm finding I have to break and replace part of the network to get it to start moving items/fluid again. Something I encountered while trying to add the automatic removal of menril blocks from drying basins to this contraption;
![picture of auto crystal menril block machine](http://i.imgur.com/3SyWHGm.png)
I'll do further testing at some point to work out why and when it might happen and open an issue if I gather enough info.

**Comment by rubensworks** [comment]
@Revvilo Last Integrated Dynamics fix (which will be included in the new release) _should_ resolve this issue (again).

It's a difficult one, so if you would encounter this issue again after the new version is released please let me know ASAP.
