### ISSUE TITLE
Player Sim 

### ISSUE THREAD

**Issue by Corrad93** [CyclopsMC/IntegratedTunnels#291]
I have been trying to make the areal pearl automation using a player sim but I cant get it to work. The way it is set up in the pearl goes in to the barrel and the player sim has a card with the pearl on click item slot. Has a green tick just not doing anything.
Help please

I have even tried with a sword still will not do anything
![2024-06-15_18 37 46](https://github.com/CyclopsMC/IntegratedTunnels/assets/98434841/39a36df8-3623-4519-9c57-122b3ddb2d50)

**Comment by rubensworks** [comment]
Could you ask this question in our discord server? People will be happy to help you there :-)
https://discord.gg/9yDxubB

<blockquote><div><img src="/assets/images/favicon.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/invite/9yDxubB">Join the CyclopsMC Discord Server!</a></strong></div><div>A place to discuss or ask questions about Cyclops mods. Every mod has its own dedicated channel. | 2519 members</div></blockquote>
