### ISSUE TITLE
World block importer and world block exporter cause crash

### ISSUE THREAD

**Issue by ab9rf** [CyclopsMC/IntegratedTunnels#292]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Dedicated server crashes when a world block exporter or world block importer is placed and enabled to import or export blocks

#### Steps to reproduce the problem:

Crash 1 (exporter):

Place a world block exporter. Connect to an item interface connected with an inventory. Configure exporter to export block in the supplied inventory. Server crashes with 
```
java.lang.NoSuchMethodError: 'void net.minecraft.server.network.CommonListenerCookie.<init>(com.mojang.authlib.GameProfile, int, net.minecraft.server.level.ClientInformation, boolean)'
        at org.cyclops.integratedtunnels.core.FakeNetHandlerPlayServer.<init>(FakeNetHandlerPlayServer.java:34) ~[IntegratedTunnels-1.20.4-neoforge-1.8.25.jar%23256!/:1.8.25] {re:classloading}
```
On restart, server crashes with a watchdog timeout. On second restart, server starts successfully, but the Integrated Tunnels network that the world block exporter was connected to is in a lockout state and will not operate.

Crash 2 (importer):

Place a world block importer. Connect to an item interface connected with an inventory. Configure importer to break the block the importer is adjacent to. Server crashes with 
```
java.lang.NoSuchMethodError: 'void net.minecraft.server.network.CommonListenerCookie.<init>(com.mojang.authlib.GameProfile, int, net.minecraft.server.level.ClientInformation, boolean)'
        at org.cyclops.integratedtunnels.core.FakeNetHandlerPlayServer.<init>(FakeNetHandlerPlayServer.java:34) ~[IntegratedTunnels-1.20.4-neoforge-1.8.25.jar%23256!/:1.8.25] {re:classloading}
```
On restart, server crashes with a watchdog timeout. On second restart, server starts successfully, but the Integrated Tunnels network that the world block importer was connected to is in a lockout state and will not operate.

#### Expected behaviour:

In case 1, the expected behavior is the exporter will place the block into the world.
In case 2, the expected behavior is the importer will break the block and store it in the attached inventory.
____

#### Versions:

- This mod (Integrated Tunnels): 1.8.25
- Integrated Dynamics: 1.21.4
- Cyclops Core: 1.19.1
- Minecraft: 1.20.4
- Forge: NeoForge 20.4.237

#### Log file:

[crash logs](https://gist.github.com/ab9rf/bac8fd061ac113f7f20abffb6b175170)

`crash-2024-07-06_12.15.54-server` is the log for the exporter crash
`crash-2024-07-06_12.25.06-server` is the log for the importer crash

#### Aside:

I also recently had a crash involving a world block reader which renderer that chunk permanently unloadable (any attempt to load the chunk containing the world block reader crashed the server), but I'm less clear on the circumstances of that crash and I'm not certain if I still have the logfile or what versions of the mod were in use. We ended up discarding that world rather than try to recover from it.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like NeoForge made a breaking change. Will be fixed in the next release.
