### ISSUE TITLE
Server crash when working together with Sophisticated Storage and AE2 auto crafting

### ISSUE THREAD

**Issue by suoliangao** [CyclopsMC/IntegratedTunnels#293]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The server crashes when I'm trying to craft some stack upgrades using AE2 auto crafting system.
Some limited barrels are connected together by a controller and connected to my AE system with storage bus.
Also, a integrated dynamics logistics system was also connected to the same controller to move items form the sieving system to the storage system.
The crash seems happens when the compression upgrade try to compress materials, but probably initiated by the item exporter.
This is more likely a bug of Sophisticated Storage, but every time it was the integrated dynamics trigger the crash.
The crash happens randomly on the server, the same setup was not tested in a single player world.

#### Steps to reproduce the problem:

I have no idea how to reproduce the problem, it just happens randomly.

1. ...

#### Expected behaviour:

Not crashing XD

____

#### Versions:

- Modpack: ATM9sky_1.0.6
- This mod: 1.22.1
- Minecraft: 1.20.1
- Forge: 47.2.20
- Sophisticated Storage: 0.10.25.804
- AE2: 15.2.4

#### Log file:

[crash_report.txt](https://github.com/user-attachments/files/16133233/crash_report.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by suoliangao** [comment]
Well, I changed my setup so is pure ae2 managing the 'drawer wall' now and the ae behavior cause the crash, so this is the bug of Sophisticated Storage and Integrated Tunnel causing the crash every time is probably because the update sequence in a tick.
