### ISSUE TITLE
Crash when right-clicking any network devices with Caupona installed

### ISSUE THREAD

**Issue by unilock** [CyclopsMC/IntegratedTunnels#294]
#### Issue type:

- :bug: Bug

____

#### Short description:

When [Caupona](https://www.curseforge.com/minecraft/mc-mods/caupona) is installed alongside Integrated Tunnels, the game crashes when right-clicking any Integrated Dynamics / Tunnels network devices, including Logic Cables.

#### Steps to reproduce the problem:

1. Install Caupona, Integrated Tunnels, and all dependencies
2. Start the game; create a new Creative mode superflat world
3. Give yourself a few Logic Cables and place them
4. Right-click the Logic Cables with an empty hand
5. Crash

#### Expected behaviour:

Game don't crash!!

____

#### Versions:

- This mod: 1.20.4-neoforge-1.8.25
- Minecraft: 1.20.4
- NeoForge: 20.4.237
- ...
- Caupona: 1.20.4-0.5.0
- Common Capabilities: 1.20.4-neoforge-2.9.1
- Cyclops Core: 1.20.4-neoforge-1.19.1
- Integrated Dynamics: 1.20.4-neoforge-1.21.4

#### Log file:

[latest.log](https://gist.github.com/unilock/cd1c25afeef8fdc193850f48670a7df1)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/IntegratedDynamics/commit/c6a6c44750be32cca90c6fddc39175f9a175dfb3
