### ISSUE TITLE
Player Simulator showing as "Logic Cable"

### ISSUE THREAD

**Issue by Moj-FPS** [CyclopsMC/IntegratedTunnels#295]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Player Simulator is showing as "Logic Cable" and is inaccessible. Reproduced issue with only Integrated Tunnels and its dependencies installed.

#### Steps to reproduce the problem:

1. Craft Player Simulator
2. Place down Player Simulator
3. Player Simulator now shows "Logic Cable"
4. Right click Player Simulator
5. Nothing happens

#### Expected behaviour:

1. Craft Player Simulator
2. Place down Player Simulator
3. Right click Player Simulator
4. Access Player Simulator GUI/interface

____

#### Versions:

- This mod: 1.8.28
- Minecraft: 1.20.1
- Forge: 47.2.23

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Moj-FPS** [comment]
Wanted to add to this real quick - it is not only the Player Simulator that has this issue. The majority of the blocks in the mod are also inaccessible. I can get a list of everything that this is happening with if that would help, just let me know. Appreciate your work!

**Comment by rubensworks** [comment]
I just tried this myself with the Forge version specified, and everything is working fine here.

Are you certain you have no other mods installed?

Do you see anything popping up in your client/server logs?

**Comment by Moj-FPS** [comment]
I'll have another go at it tonight. Will let you know what I find!
