### ISSUE TITLE
Crash in MC 1.20.4 with Integrated Tunnels Fluid Interface

### ISSUE THREAD

**Issue by dustinsurwill** [CyclopsMC/IntegratedTunnels#296]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash in MC 1.20.4 with Integrated Tunnels fluid interface when connected to either Modern Industrialization or Mekanism tanks with fluid in them. 

#### Steps to reproduce the problem:

Cannot seem to reproduce on purpose, but unable to load 2 worlds due to this. Will supply those broken worlds upon request.

#### Expected behaviour:

No crash.
____

#### Versions:

- This mod: 1.8.26
- Minecraft: 1.20.4
- NeoForge: 20.4.237
- Modpack: FTB NeoTech 1.6.0
- IntegratedCrafting: 1.1.7
- IntegratedDynamics: 1.21.5
- IntegratedTerminals: 1.4.13
- CyclopsCore: 1.19.3

#### Log file:

Optional cannot be cast to class net.neoforged.neoforge.fluids.FluidStack: [crash-2024-07-28_23.59.26-server.txt](https://github.com/user-attachments/files/16409006/crash-2024-07-28_23.59.26-server.txt)
WorldSlice cannot be cast to class: [crash-2024-07-25_00.24.47-client.txt](https://github.com/user-attachments/files/16409007/crash-2024-07-25_00.24.47-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
