### ISSUE TITLE
'Place Logs' tutorial name does not hint to tags

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedTunnels#298]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

We've had a few people not finding a tutorial on e.g. exporting items by item tag and asking about it on the discord - e.g. [this message](https://discord.com/channels/386052815128100865/386054223688630272/1269496537067815085) ("Out of everything the book tells you how to do, filtering by tags was the only thing I expected, and was unable to find anything about.")

Currently the main tutorial for that is 'Place Logs', which is for configuring an world item exporter to export logs via the item tag, although the name for this tutorial doesn't immediately make it clear that this tutorial is to do with this.
An alternative name such as 'Place Logs by Tag' or 'Place Items by Tag' could help make it clearer this is where people should look to be introduced to tags.

**Comment by rubensworks** [comment]
Thanks for the suggestion!
