### ISSUE TITLE
'Place Logs' tutorial uses old operator name in text (oredict instead of tags)

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedTunnels#299]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The 'Place Logs' tutorial refers to `tag_values` as the 'oredictionary values operator' (the old name) in the tutorial text.

#### Steps to reproduce the problem:

https://integrateddynamics.rubensworks.net/book/tutorials/tutorials/integratedtunnels/place_logwood.html

![image](https://github.com/user-attachments/assets/b932cd20-6613-46d8-bec7-c3d46543e934)

#### Expected behaviour:

Some version of the new long name of the operator is used instead of refering to it with oredict.

It looks like the name is hardcoded in the localisations (`info_book.integratedtunnels.tutorials.place_logwood.text1`) rather than pulling the long name of the operator from the registry, which has lead to the discrepancy, although changing that would be much larger than simply only updating the name in the localisations.

____

#### Versions:

N/A

#### Log file:

N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
