### ISSUE TITLE
Item request terminal?

### ISSUE THREAD

**Issue by gazpachoking** [CyclopsMC/IntegratedTunnels#3]
I'm not sure if it fits with your vision for the mod, but a special type of item exporter for manual user requests would be nice. Something that would give the player an interface showing all items in storage attached to interfaces on the network, and the ability to request those items, something like an ME terminal.

**Comment by gazpachoking** [comment]
More thoughts: Maybe the request panel could be separate than the item exporter, and you could configure it to send to one of the item exporters on the network.
Some setups I'm imagining building, for context:
- Crafting Station:
  One of the mod crafting tables with integrated storage hooked up to an item exporter, a request panel near the table configured to send its requests to said item exporter. Probably also an item importer on the table, with a button to turn it on, (to send all the extras back into the system when done.)
- Smeltery:
  Have a request panel configured with an item exporter on your smeltery. The request panel could be put in your crafting area, even though the ores would be sent down to wherever your smeltery is when requested.

**Comment by gazpachoking** [comment]
Okay, been thinking a bit more, and maybe most of my request is something for Integrated Dynamics rather than Tunnels. What I do think would be nice from tunnels is a way to get a few variables out, for example, the list of items in all attached item interfaces on a tunnel network (is that possible already? I looked a bit, couldn't find a way other than putting item readers on all the inventories as well. (Now I'm totally off topic, but is there an operator to concatenate 2 lists? I couldn't find a way to concat all the items from multiple item readers.)) I think it would also make sense to let the item importers and exporters act as item readers as well. The interfaces could then act as special item readers that read the inventories from all the item interfaces on the network.

The request terminal could then be implemented purely in integrated dynamics, which would be a nice interface to set a variable dynamically. It could be fed in a list variable to display to the user (perhaps the list of all items in your tunnel interface network,) and the user could select an item from that list which would be set to a variable. I haven't worked out the specifics, but somehow use that variable in the item exporter to export a certain amount of that item then stop. It'd be sorta complicated to set up, but I feel like that's already sorta the theme here. 😉

**Comment by rubensworks** [comment]
This is indeed something that is still on the roadmap, somewhere.
It won't be implemented any time soon though...

**Comment by antrobot1234** [comment]
why is this still open? this is basically integratedCraafting

**Comment by rubensworks** [comment]
Ah indeed, this can be closed.

https://minecraft.curseforge.com/projects/integrated-terminals

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/165/801/120/120/636694374476455275.png" width="48" align="right"><div>Minecraft CurseForge</div><div><strong><a href="https://minecraft.curseforge.com/projects/integrated-terminals">Integrated Terminals</a></strong></div><div>Terminals for managing and overviewing Integrated Dynamics networks</div></blockquote>
