### ISSUE TITLE
Fluid/Energy Transfer Rates are set to 0 on load.

### ISSUE THREAD

**Issue by VampireValik** [CyclopsMC/IntegratedTunnels#30]
- Minecraft: 1.11.2
- forge-1.11.2-13.20.0.2299
- IntegratedTunnels-1.11.2-1.2.0.jar
- A bunch of other mods as well, all up-to-date. If you can't reproduce the issue I can narrow down mods in case of a bad interaction.

Pretty simple to reproduce. I updated to the latest Integrated Tunnels (and Integrated Dynamics and all dependencies) and noticed none of my fluid or energy transfers were working. I checked and the transfer rates were set to 0. I changed them back to what I wanted and things started working again. Then I quit the game but upon loading it again the transfer rates were back to 0.

My item transfer tunnels are not working, either, but none of the values appear reset so I don't know if it's related.

**Comment by rubensworks** [comment]
Note to self: might have something to do with fdb20dd03c096f5f8604e0c1d6802fedf932d7bb
Problem seems to be more generic than that. All configured aspect property values are set to 0 after restart.

Will look into it tomorrow.

**Comment by BrewingCoder** [comment]
I can confirm this; just swung on by to report this.  Every load in SSP fluid and energy importers/exports are broken.  

I can pull them all off, reset them in a crafting grid, and then replace them and they work.  That is until the next time the SSP  world is loaded or the SMP server is rebooted.  I tried it both ways.

**Comment by rubensworks** [comment]
Will release a new patch today.
