### ISSUE TITLE
List generated from inventory reader, will always export apples when used in item exporter

### ISSUE THREAD

**Issue by Nathan1506** [CyclopsMC/IntegratedTunnels#301]
#### Issue type:

- :bug: Bug 

____

#### Short description:

A list variable generated using an inventory reader on any inventory, when used in an exporter (export items) will always export vanilla apples from the network, as well as the items on the list. Apples are exported even if the list is empty.

#### Steps to reproduce the problem:

1. Place a chest
2. Attach an inventory reader to the chest
3. Place a variable in the "items" slot to generate a list of the chest contents
4. Attach two more inventories to the network
5. Place apples in one inventory (and any other items)
6. attach an item interface to the chest
7. attach an item exporter to the other chest
8. use the list (generated in step 3) in the export items slot

#### Expected behaviour:

The exporter should only export items on the list.

____

#### Versions:

- This mod: ID 1.23.1    Integrated Tunnels 1.8.29
- Minecraft:  1.20.1
- Forge:  47.3.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by the-annatar** [comment]
we did some testing on discord and the issue seems to also happen when making a list with an empty entry. so i would say its empty list entries being counted as apples.

**Comment by met4000** [comment]
Can confirm on latest versions as well, e.g.:
![image](https://github.com/user-attachments/assets/19537a64-fff8-49cb-8167-0f14235aabc8)

See also the conversation on the discord - [initial question](https://discord.com/channels/386052815128100865/386054223688630272/1271071816751775826), [testing and empty slots causing apples to be exported](https://discord.com/channels/386052815128100865/386054223688630272/1271133298974003260)

**Comment by rubensworks** [comment]
Heh, that's a funny bug :p

**Comment by Nathan1506** [comment]
> Heh, that's a funny bug :p

I spent 3 days wondering why all my apples were being burned in my ore smelter, it was pretty funny!
Ty for the quick fix <3
