### ISSUE TITLE
Very high lag with Integrated Tunnels and Iron Furnaces.

### ISSUE THREAD

**Issue by marcelo-jrkiko** [CyclopsMC/IntegratedTunnels#303]
#### Issue type:

- :bug: Bug

____

#### Short description:

Recently investigating why my world was super legacy, using Spark Profiler I identified the cause.

#### Steps to reproduce the problem:

To reproduce, simply place an Iron Furnaces furnace with an Item Exporter exporting any material to it. In my case it is "Oak Log". This causes monstrous lag in the world.

![2024-10-18_15 53 54](https://github.com/user-attachments/assets/92d4ddc7-ad03-45c7-883f-909ed02c2c28)

#### Expected behaviour:

The Item Exporter works correctly, but causes huge lag in the world. Removing the furnace and replacing it with something else will do the trick and resolves the problem. 

____

#### Versions:

- This mod: 1.8.28
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.69

#### Log file:

https://spark.lucko.me/1HTNyB7o4X

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
From the logs, it looks like the furnace is actively _pulling_ items from the exporter (as opposed to just the exporter _pushing_ items into the furnace).
If your network is very large, then this will cause the furnace to iterate over all slots in your network every tick.
There should be an aspect setting in your exporter to disable this kind of passive interaction, which should resolve your problem.
Please let me know if this would not work.
