### ISSUE TITLE
Extreme Lag after leaving server on for more than a day

### ISSUE THREAD

**Issue by QBos07** [CyclopsMC/IntegratedTunnels#307]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

A freshly rebooted server has allmost perfect performance but leaving it running for a while makes it impossible to play.

#### Steps to reproduce the problem:

Happend randomly, the most probable culprit is this setup (I dont have any other really active setups)
![2024-10-31_14 31 18](https://github.com/user-attachments/assets/e2a73754-b98f-4f1d-b18b-0ad565ee1bf1)
![2024-10-31_14 31 25](https://github.com/user-attachments/assets/7f30d8bb-ee97-4afe-a55a-698d3f83d984)

____

#### Versions:

- This mod: 1.8.31
- Minecraft: 1.20.1
- Forge: 47.3.7
- Modpack: ATM9 0.3.2

#### Profiler output:

![image](https://github.com/user-attachments/assets/50127cfa-096e-4fe2-9d4c-e8b2201d64a5)
[TeOULLUCc9.sparkprofile.zip](https://github.com/user-attachments/files/17588502/TeOULLUCc9.sparkprofile.zip)

---

I can give you server access if you need for further analysis

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Are you certain you're on the latest Integrated Dynamics version?

**Comment by QBos07** [comment]
Integrated Dynamics is still on 1.23.2

**Comment by QBos07** [comment]
I have gone trougth the release notes and coulnd find anything related. I still try to replicate it on the currently latest (1.23.10)

**Comment by rubensworks** [comment]
Thanks!

In case it would still be laggy in 1.23.10, could you also try 1.23.8 to see if there's any improvement on your end there?
That could help me identifying what exactly goes wrong.

**Comment by rubensworks** [comment]
What could also help, is using the `\integrateddynamics networkdiagnostics` command to pinpoint the exact part that is causing the lag.
If you could tell me which part and aspect causes the lag, this would also greatly help me.

**Comment by QBos07** [comment]
Here are 1.23.10 results: Still an issue
![image](https://github.com/user-attachments/assets/2721ac6b-813b-41df-9d92-9cade75378a2)
[q48sMZApiT.sparkprofile.zip](https://github.com/user-attachments/files/17599839/q48sMZApiT.sparkprofile.zip)
(Less severe since i let it running for only a bit under 24h)

**Comment by QBos07** [comment]
here is the website output:
![image](https://github.com/user-attachments/assets/965690cc-2b54-4489-8912-365ef5a1c375)

**Comment by QBos07** [comment]
btw in the 1h since these posts tps fell from 16 to 12...

**Comment by rubensworks** [comment]
Which aspects are active in those item exporters?

Could you also have a look if downgrading to 1.23.8 has any impact?

**Comment by rubensworks** [comment]
Another question; does resetting the network (breaking/placing a single cable) also reset the tps lag?

**Comment by QBos07** [comment]
I use a blank variable card in export all items. I'm currently testing 1.23.8 but I will have to wait until i can test your resetting idea.

Intrestingly enough my most used setup (the 9 cables, overworld one) wich transport 10x the amount into a rf-tools crafter and an even bigger drawer grid from a 3x chest does not suffer from this issue altougth it shares the same configuration

**Comment by QBos07** [comment]
also the laggy ones appear to be the ones with multiple inputs (2x simulation chambers) and outputs (drawer access point; loot fabricator). the single block, single io ones are fine

**Comment by rubensworks** [comment]
I've had a look at it, and I'm not quite certain yet if I found what is causing the problem, but I've pushed a new dev build with a potential fix.
@QBos07 Could you try out [the latest dev build of ID](https://github.com/CyclopsMC/packages/packages/769739) (`integrateddynamics-1.20.1-1.23.10-913.jar`), and let me know if this fixes your problem?

**Comment by QBos07** [comment]
reseting the network worked as a temporal "fix"
EDIT: 1.23.8 still has the problem

**Comment by rubensworks** [comment]
@QBos07 Not sure if you saw [my previous message](https://github.com/CyclopsMC/IntegratedTunnels/issues/307#issuecomment-2452108026), hence the re-ping.
Could you let me know if the linked dev build fixes your problem?

**Comment by rubensworks** [comment]
You know; since I have high confidence in this change, I'll just release it.
Should you or anyone else still encounter this issue, please let me know, so I can re-open this issue.

**Comment by QBos07** [comment]
that fixed it! thanks for the awsome support

**Comment by rubensworks** [comment]
Great, thanks for the confirmation!
