### ISSUE TITLE
Items inserted by passive interaction ignores importer's setting

### ISSUE THREAD

**Issue by AlisonHuang777** [CyclopsMC/IntegratedTunnels#308]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When inserting items with external devices (e.g. hopper), the items will always try to go to the interfaces of which the channel is set to `0` (which is default value), ignoring that of the importer. Also if round-robin is enabled it will also get ignored. Therefore I consider that items, as the title described, will omit the settings of the importer and follow the default behavior.
Currently only tested with item importers/interfaces, but same issue might occur with other variation as well.

#### Steps to reproduce the problem:

Please watch this footage: https://youtu.be/4jYrVpU2A7c
Using ATM9 0.3.2.

#### Expected behavior:

Items should only go to interfaces with channel `1` and the amount of them being transferred to each of the barrel should be the same (at least be close).

____

#### Versions:

- Integrated Tunnels (this mod): 1.8.31
- Integrated Dynamics: 1.23.11
- Mod loader: Forge 47.3.0
- Minecraft: 1.20.1

#### Log file:

*no response*

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm unable to reproduce your problem.
Can you try reproducing the problem without any other mods installed?
If so, could you share a video or a more details step-by-step guide on how to reproduce your problem?

**Comment by Jack-McKalling** [comment]
Did you possibly use a negative value for the Item Interface channel setting?

Or did you use a negative value for the source slot to pull from, instead? (separate question)

**Comment by AlisonHuang777** [comment]
Sorry for the late update, and sorry again for that there were mistakes in the original description. Therefore I have recorded a footage to showcase the bug more clearly, link in the edited description.

**Comment by Jack-McKalling** [comment]
Ah. So you're using round-robin mode, but that's actually confusing the situation. Try to see if the problem happens without using round-robin, to see what really happens. That setting already deliberately ignores all priority settings according to its tooltip (see CyclopsMC/IntegratedDynamics/issues/1406).

With my own observations, it looks like with the passive interaction _enabled_, and the hopper pointing into the importer, items are sorted through the incorrect channel `0` as well as the correct one. With the hopper pointing elsewhere and exclusively the importer pulling form it, this will not happen.

_However_, interestingly, with the passive interaction setting disabled, it still happens! So there must be something wrong with the hopper interaction, maybe overriding the passive interaction setting or just ignoring the channel setting.

**New repro steps;**
- place a row of 4 inventories
- attach item interfaces to the top of each, with a logic cable
- modify the two on the right to interface channel `1`
- add an importer to the network, with a hopper pointing into it
- modify the top aspect of the importer to insert into channel `1` as well, and transfer rate 1/t
- insert a 64 stack of items into the hopper
- notice that one of the inventories on the left is getting filled by hopper speed (wrong channel), and one on the right at fast speed (correct channel)

**Comment by rubensworks** [comment]
Thanks for the additional information @AlisonHuang777 and @Jack-McKalling!

**Comment by AlisonHuang777** [comment]
Removed the footage on Youtube as this issue has been closed.
