### ISSUE TITLE
Cannot clear ID off of tunnels through crafting table

### ISSUE THREAD

**Issue by N1ghthauq** [CyclopsMC/IntegratedTunnels#309]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Cannot craft tunnels to clear ID.

#### Steps to reproduce the problem:

1. Place a logic cable
2. Place an interface on the logic cable
3. Remove interface with the wrench to preserve the ID of the interface
4. Put interface in a crafting table and observe the lack of output for the recipe

Note: Breaking the interface from the world without the wrench can clear the ID.

#### Expected behaviour:

Placing a interface in the crafting grid produces a cleared interface

____

#### Versions:

- This mod: 1.8.29
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.80

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
This happens for me too. This wasn't a problem yet in 1.20.4 so it was introduced in the above mentioned MC release versions.
