### ISSUE TITLE
Exporters just won't work.

### ISSUE THREAD

**Issue by xxjetterxx** [CyclopsMC/IntegratedTunnels#31]
If I attach an exporter to a network that has an item interface on the other chest (two chests, like the example on the mod page) no matter what I do, I can't get it to pull any items to the chest with the exporter on it. I'm putting a blank card in the export item slot, it's active (not errored) and should be working (again, it's the same as on the example page).

**Comment by rubensworks** [comment]
@xxjetterxx Seems to work just fine here.
This *might* have been related to #30 though, so let me know if you still encounter this problem after I release the new (ID) update.

Also, if it doesn't work, please send me a screenshot of the setup and the export gui.

**Comment by xxjetterxx** [comment]
I still can't get it to work, even with the new update. I took some screenshots: 
![2017-05-21_12 25 36](https://cloud.githubusercontent.com/assets/7423931/26286013/3532bd1c-3e29-11e7-98de-d9ce77fed37d.png)
![2017-05-21_12 25 40](https://cloud.githubusercontent.com/assets/7423931/26286014/3533169a-3e29-11e7-8f86-d027a445a801.png)

It should move items in the chest from left to right, but it doesn't.

**Comment by rubensworks** [comment]
That's strange, I just tested the exact same thing myself and that worked.

Can you try removing all other mods and try in a fresh new world?
Perhaps some other mod is breaking something.

**Comment by xxjetterxx** [comment]
Just tried that, can't get it to work, even with a brand new world and a brand new minecraft install. I'm running the latest version of forge (2299) and cyclopscore 0.10.3, commoncapabilites 1.3.2. Is there a dependency I need to update or something?

**Comment by rubensworks** [comment]
No other dependencies are needed.
Are you able to make a short recording of you building your setup and demonstrating that items aren't being transferred?
Perhaps you somehow are doing something special what breaks it, somehow...

**Comment by xxjetterxx** [comment]
Sure, give me a few minutes

**Comment by xxjetterxx** [comment]
https://www.youtube.com/watch?v=M1Cq0VUUAWE&feature=youtu.be
There, that should work

**Comment by rubensworks** [comment]
Thanks for the video.
When using your Forge version I can indeed reproduce the problem. I'm looking into it...

**Comment by xxjetterxx** [comment]
Perfect, in the meantime I'll just use an older version of forge

**Comment by rubensworks** [comment]
Ok, apparently I broke something recently in the 1.11 version.
I'm pushing out a new (1.11) release at the moment, should be on curseforge in a few minutes.

Thanks for your help in debugging this!

**Comment by xxjetterxx** [comment]
No problem, I'll keep you up to date with any other issues I find!
