### ISSUE TITLE
Cannot Interact with Player Simulator 

### ISSUE THREAD

**Issue by Moj-FPS** [CyclopsMC/IntegratedTunnels#314]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Cannot interact with player simulator. Had this same issue before as well but never got around to testing it further (my bad). Not sure if I am just missing a step or what the issue may be, but I currently have only Integrated mods installed and cannot get it to work for the life of me.

![image](https://github.com/user-attachments/assets/a1ad0c2f-fce9-423f-b748-922992f0ae53)

#### Steps to reproduce the problem:

1. Create player simulator
2. Place down player simulator
3. Player Simulator shows as "Logic Cable"
4. Right click Player Simulator with no effect

#### Expected behaviour:

Player Simulator should show as "Player Simulator," and right clicking should open a GUI. 
____

#### Versions:

- This mod: 1.8.30
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.84

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Moj-FPS** [comment]
Just a clarification, the screenshot is from an instance that did have mods (as you can see Journeymap) - but the issue persists with only Integrated mods installed.

**Comment by rubensworks** [comment]
All parts need to be attached to a cable before you can interact with them.
In case this still wouldn't work for you, please let me know.
