### ISSUE TITLE
Fluid exporter exporting wrong fluid

### ISSUE THREAD

**Issue by BrewingCoder** [CyclopsMC/IntegratedTunnels#32]
Problems I've had with fluid in the last two updates:

Exporters exporting wrong fluid.

Interfaces nuking contents of a container/tank to use for a different fluid.

I was finally able to find a problem I could reproduce easily... it may have to do with the proximity of the the tanks/exporters.. who knows.  

ID ver:  1.10.2-0.7.1
IT ver:  1.10.2-1.2.0

https://youtu.be/Hy-NxniB0Ug

**Comment by rubensworks** [comment]
Thanks for the detailed video.
I'll look into it asap.

**Comment by rubensworks** [comment]
I've managed to reproduce and fix the issue. Will make a new release later today.
