### ISSUE TITLE
Energy crashes client and server

### ISSUE THREAD

**Issue by NoLiver92** [CyclopsMC/IntegratedTunnels#33]
If the energy transfer connections are connected to a buildcraft item and you put a variable in or change frequency it crashes the client and server. Ive included the crash report which seems a method is being called which doesnt exist

[crash-2017-06-04_13.09.10-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/1050307/crash-2017-06-04_13.09.10-server.txt)

**Comment by rubensworks** [comment]
It looks like you're not using the latest ID and IT versions, please update to the latest versions and let me know if the issue persists.
