### ISSUE TITLE
Payload may not be larger than 32767 bytes after error spam

### ISSUE THREAD

**Issue by Revvilo** [CyclopsMC/IntegratedTunnels#35]
While fiddling around trying to solve a problem, I kept encountering a bug which seems to cause an immense amount of errors being saved into NBT causing me to be disconnected for the above error about payload sizes.
My newly discovered way to recreate:
- Place a chest with one item inside
- Connect it to a network via an item interface
- Connect another inventory with an item exporter in order to export items from that interface
- Place a **raw item equals** operator variable that has been negated (via the |. operator) into the **item transfer predicate** aspect
(I'm sure this works with other operators too)

You should see a ton of errors pop up in The One Probe or WAILA just from that one item, (there's around 107 from my testing).
It seems from testing that placing more items in the chest does not cause more errors until you re-plug the variable card into the exporter, which will then kick you if there are enough items in the inventory.

- Minecraft Ver • 1.10.2
- Forge Ver • 12.18.3.2316
- Integrated Dynamics Ver • 0.7.2
- Integrated Tunnels Ver • 1.2.1

**Comment by rubensworks** [comment]
Oops, 107 errors indeed seems to be a bit much...

**Comment by Revvilo** [comment]
Hehe, while in MCEdit (to fix affected worlds) I've seen over 1700 errors in the NBT. Not surprised poor ol' mc can't handle it :3
