### ISSUE TITLE
Localisation issue with pipe(?) operator

### ISSUE THREAD

**Issue by Revvilo** [CyclopsMC/IntegratedTunnels#39]
![image](https://user-images.githubusercontent.com/13816212/27413469-b05e578c-574f-11e7-82e2-87765a25d29c.png)
To recreate:

- Apply a list of items to a **contains_p** operator variable
- Then use pipe like so: (the prev. applied **contains_p**  |  **raw item equals** operator variable)
- And stick it in an Item Exporter

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/IntegratedDynamics@b8493eef49b3ac8629d2c4d0cc8e29faaea3c75b
