### ISSUE TITLE
[1.0.0] Crossmod issue with Item Interface

### ISSUE THREAD

**Issue by Belgabor** [CyclopsMC/IntegratedTunnels#4]
The Integrated Tunnels item interface does not work with a lot of inventories from other mods including Actually Additions inventories (Storage crates, item interface), Gendustry and ExU2 machines, Storage Drawers and others.
It seems to work if you use importers or exporters on them, just the (IT) item interface does not work.

**Comment by rubensworks** [comment]
It seems the problem had nothing to do with other mod inventories.
I apparently just forgot to handle one edge-case.
