### ISSUE TITLE
Add Actually Additions Compat

### ISSUE THREAD

**Issue by Epic428** [CyclopsMC/IntegratedTunnels#40]
SkyFactory 3.0.13
Integrated Tunnels 1.2.1
Integrated dynamics 0.7.3
Cyclops Core 0.10.5
Minecraft 1.10.2
Actually Additions 1.10.2-r105

It appears that none of the importers/exporters/interfaces for Items, energy, and fluids are compatible with Actually Additions machines. Not sure if this can be fixed or not or if it would have to fixed on AA's side.

Thanks,
James

**Comment by rubensworks** [comment]
This mod is fully capability-based, so if AA doesn't support that, there's not much I can do.

But I thought AA implemented capabilities, so will have a look to see what is going on there.

Can you give me an exact example of a machine that *doesn't* work?

**Comment by Epic428** [comment]
I had issues when connecting item importers/exporters to the powered furnace and the crushers. I also had issues when transferring energy into the same machines. Essentially, nothing would transfer. I'm currently at work but later tonight I can get some screenshots of the setup if necessary.

**Comment by Epic428** [comment]
OK so I did a bit more testing and it seems it is only the energy import/export/interface that doesn't work with the two machines I mentioned above. Lol I forgot the crate was Actually Additions which I am successfully transferring items in and out of. It appears the two machines also work for items leaving energy the only thing that's not working correctly. The energy issue was what actually prompted me to submit the bug report as I just assumed that since the importers/exporters/interfaces utilize similar code they were all affected. 

Edit: (I'm also assuming that fluids work as items do even though I have not tested fluids.)

**Comment by rubensworks** [comment]
Looks like you may be doing something wrong, works just fine here using the latest 1.10.2 versions.

![2017-07-17_08 24 21](https://user-images.githubusercontent.com/440384/28257214-5e0c3174-6ac9-11e7-8c60-f7af35df3bb2.png)
