### ISSUE TITLE
Importers don't work with Immersive Engineering auto ouput

### ISSUE THREAD

**Issue by Epic428** [CyclopsMC/IntegratedTunnels#41]
SkyFactory 3.0.13
Integrated Tunnels 1.2.1
Integrated dynamics 0.7.3
Cyclops Core 0.10.5
Minecraft 1.10.2
Immersive Engineering 0.10-60

It seems that certain machines such as the Garden Cloche or Industrial Squeezer have a side which auto-outputs to an inventory. I read an issue on IE github about the Cloche not auto outputting to Ender IO conduits where in the comments it was mentioned that it didn't work due to the conduits not having an actual inventory.

Item/fluid/(haven't tested energy) importers don't work when attached to these machine sides. I discovered that if I use an interface instead, I can "import" to the network, but I lose the finite control I get from using actual Importers. It also appears that for the interfaces to work, there has to be an inventory on the network to act as a buffer, you can't straight export to a machine. I'm not sure how trivial this fix would be or if its possible.

Edit: link to IE Issue for reference: https://github.com/BluSunrize/ImmersiveEngineering/issues/2186

If you need more info let me know.

Thanks,
James

**Comment by rubensworks** [comment]
This should work though.

Are you sure that there is at least one valid item interface when your importer is connected to the cloche?
Importers *have* a (virtual) internal inventory.
Last time I checked this still worked.

**Comment by Epic428** [comment]
100% positive I had an interface. I had the importers connected to the cloche on the side of the dome where it should be. I ran the cable direct to a basic chest with an interface and even attempted a direct connection to an exporter attached to a machine. Later tonight when I get home from work I can put together some screenshots of the setup.

**Comment by Epic428** [comment]
http://imgur.com/a/a6iAn

OK. I tried to take a video but, my laptop is garbage so, I took screenshots instead. Please note that the exact same issue applies to the industrial squeezer as I have tested that also, though, it is not included in the screenshots. I setup 4 cloches, with the left two using item importers and the right two using interfaces. The left two do not transfer items to the chest which is connected via interface. The right two do transfer items to a chest which is also connected via interface. 

To be honest, given that this issue also affects Ender IO conduits and ExU 2 Pipes per the referenced issue, the best solution in my opinion would be for Immersive engineering to not auto output the way that it does. My guess is that it's done that way due to being a multiblock structure but I could be totally wrong.
