### ISSUE TITLE
Exporter/Importer Doesn't Work with Static Item Variable

### ISSUE THREAD

**Issue by bcrotty** [CyclopsMC/IntegratedTunnels#42]
When I make a static item variable and put it in the Export/Import Item slot of the respective part, it doesn't do anything. In order to get it to work, I have to make a single element list and put the variable in the Export/Import Items slot.

**Comment by rubensworks** [comment]
That's strange, this worked last time I checked. MC/mod version?

**Comment by bcrotty** [comment]
1.10.2 and IntegratedDynamics-1.10.2-0.7.7

**Comment by rubensworks** [comment]
This seems to work just fine for me, both importing and exporting with a static item.

I'll need additional details of your use case if the issue still persists for you.
