### ISSUE TITLE
Suggestion: Allow Importers/Exporters to Also Be Interfaces

### ISSUE THREAD

**Issue by bcrotty** [CyclopsMC/IntegratedTunnels#43]
I essentially have a string of 9 inventories that I'm moving items between, and it would be a whole lot cleaner if I didn't need to have two connections on most of the blocks. There are probably times that it wouldn't be good, so you could have an option in the GUI to disable the interface portion.

**Comment by rubensworks** [comment]
This would require a complete rewrite of how the tunnels system works, and this doesn't really fit into the design of this mod. You might be able change the way you transfer your items by only using interfaces on the blocks that normally have two parts.
