### ISSUE TITLE
Suggestion: let player simulators use fishing rods and leads

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedTunnels#49]
Player simulators currently seem unable to properly use items that require multiple clicks to use, such as fishing rods and leads. Could this ability be added?

**Comment by rubensworks** [comment]
This *should* already work. Will look into what is going wrong there. If it's too complex too fix, I'll add functionality for this in the future, as I intended to release these new world interaction features soon.

**Comment by rubensworks** [comment]
Items like this work now.

The only limitation is that their related entities won't be rendered, due to MC requiring (fake) players to exist client-side. Perhaps I can come up with a clean solution to fix this in the future.
Following up in #50
