### ISSUE TITLE
Issue with Fluid Interfaces

### ISSUE THREAD

**Issue by orionSquared** [CyclopsMC/IntegratedTunnels#51]
https://pastebin.com/V1aCjyRa

Unsure of what is causing this. I have a fluid extraction on an Immersive Engineering Coke Oven leading to a fluid interface on a tank port from Simple Fluid Tanks. This has caused my client to crash twice. Both times, I was in the nether, exploring. The integrated tunnels stuff is back at my base. My base is not chunk loaded.

**Comment by rubensworks** [comment]
Thanks for the info, this should help me to better debug #46.
