### ISSUE TITLE
Random crash related to integrated tunnels

### ISSUE THREAD

**Issue by JonaBrackenwood** [CyclopsMC/IntegratedTunnels#55]
Crash report: https://pastebin.com/vSywswNw
Could be a problem with partly loaded network?

After restart of the server, and after breaking and replacing a cable of the Integrated Dynamics network, things started working again.

**Comment by rubensworks** [comment]
Haven't seen that before, will check.

**Comment by rubensworks** [comment]
Actually, this might be similar to #46.

**Comment by orionSquared** [comment]
I'm having this same issue. My world is almost unplayable as I crash every 30 minutes or so. Can provide a crash report if necessary, but it's basically the same thing.

**Comment by rubensworks** [comment]
@orionSquared Feel free to use the latest dev build to see if it resolves the issue for you.

**Comment by orionSquared** [comment]
Where can I find the dev build for the 1.11.2 version? Sorry if that's a stupid question.

**Comment by rubensworks** [comment]
All dev builds can be found here: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/

1.12 is my main update branch though, I'm abandoning 1.11.2 and earlier. As I don't have enough time to maintain multiple versions at the same time, and as most people have transitioned to 1.12.1. Sorry :/
You're welcome to backport it to 1.11.2 yourself though.

**Comment by orionSquared** [comment]
Ah, I don't even know how to do that. Thanks tho :)

**Comment by rubensworks** [comment]
If I would find a big chunk of free time, I might backport it still, but no guarantees on that.

**Comment by orionSquared** [comment]
Don't feel obligated. If the community is moving from 1.11.2, then there's no reason I shouldn't do the same. :)
