### ISSUE TITLE
Item List blank item use crash

### ISSUE THREAD

**Issue by murapix** [CyclopsMC/IntegratedTunnels#56]
Minecraft: 1.12.1
Modpack: Radon 1.2.2
Integrated Tunnels: 1.12-1.3.2
Integrated Dynamics: 1.12-0.8.7

I was using the player simulator to place aquamarine into an Astral Sorcery Lightwell, but had set it up to pick between two values in an item list, depending on whether it was day or night. The first value was aquamarine, the second just left blank. However, upon becoming daytime, the interface attempted to use the blank item, and caused this crash.

https://www.hastebin.com/xadecifozu.bash

I assume this is simply because blank values in item lists are not initialized, and are therefore left as null instead of being initialized as an empty itemstack, which will cause a crash-loop as long as the player simulator is loaded.

**Comment by rubensworks** [comment]
Will be fixed with new Integrated Dynamics update.
