### ISSUE TITLE
[1.10.2]Importer bug

### ISSUE THREAD

**Issue by DSLM** [CyclopsMC/IntegratedTunnels#60]
When I use the grinder of ActuallyAdditions, I use importer to get the product. It work very will at the beginning, but after I played some day, it wouldn't work sometimes. I try to change the frequency and priory, but still not working. Then I change the Item Transfer Rate to 1, 63 or 65, and it will work so fast. When I change it to -1, it do something awesome:
the Grinder
![image](https://user-images.githubusercontent.com/12635058/31525036-73eb7e30-af8b-11e7-987f-3e77a7a4779b.png)
the chest
![image](https://user-images.githubusercontent.com/12635058/31525045-8445ca4c-af8b-11e7-98b0-89f931f41847.png)
And they can be taken out in hand.
Then I tried the grinder of enderIO, and it won't happen. Is that IT's problem or AA's problem?

version:

- ActuallyAdditions-1.10.2-r105

- CommonCapabilities-1.10.2-1.3.4

- CyclopsCore-1.9.4-0.10.9

- IntegratedDynamics-1.10.2-0.7.13

- IntegratedTunnels-1.10.2-1.2.5

- Forge 12.18.3.2488

**Comment by rubensworks** [comment]
Yeah, you shouldn't be able to change the rate to anything negative, this can result in unexpected behaviour in other mods.

**Comment by DSLM** [comment]
maybe you can add a limit?

**Comment by rubensworks** [comment]
Yes, that will be the best way to fix it.
