### ISSUE TITLE
Item Exporter/Inventory Reader set ups causing lag

### ISSUE THREAD

**Issue by Macrophage001** [CyclopsMC/IntegratedTunnels#61]
I'm making an inventory sorting system where I use inventory readers underneath actually additions storage crates and item exporters attached to the back, each containing a variable card that's been linked to the list attribute of their respective inventory reader. However once I start placing the variable cards inside the item exporter, the game starts to lag severely and gets worse the more variable cards I place inside their respective item exporters Here's a picture of the set up to get a better idea:

![2017-10-19_14 29 17](https://user-images.githubusercontent.com/331135/31787829-e4a2ffe6-b4da-11e7-9f79-d5e36ded9f24.png)

**Comment by rubensworks** [comment]
@Macrophage001 Can you try profiling your setup and send me the .nps file?

More information can be found here: https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by Macrophage001** [comment]
Here you go:

[lag_spike.zip](https://github.com/CyclopsMC/IntegratedTunnels/files/1400294/lag_spike.zip)

**Comment by rubensworks** [comment]
Thanks!
It looks like the main bottleneck seem to be the usage of list variables, which is understandable.
Will have a look if I can do some optimizations there.

In the meantime, you can reduce server load by reducing the frequency of some of your parts, as I assume you don't need them working every tick.

Note to self: optimize list proxies.

<img width="1033" alt="screen shot 2017-10-20 at 09 05 36" src="https://user-images.githubusercontent.com/440384/31799600-f62d1a6c-b575-11e7-8c4c-fc6c11cb3479.png">

**Comment by Macrophage001** [comment]
Ah ok. Thanks for the advice!

**Comment by rubensworks** [comment]
I've implemented a small optimization that should have a huge impact on item list performance.
Feel free to try out the latest Integrated Dynamics dev build to see if this helps in your case.
