### ISSUE TITLE
Link a card to energy input/output to display the value in a display

### ISSUE THREAD

**Issue by Thutmose** [CyclopsMC/IntegratedTunnels#65]
With the following setup, I can extract energy out of the voltorb, and charge the battery with it:
![image](https://user-images.githubusercontent.com/2363472/31954329-4cffeae6-b8b3-11e7-93d6-c3621fee28a9.png)

Is there any way to get the energy being imported to show on the display? the gui for the importer doesn't seem to have the slot to allow linking a card to the inputted value.

Ideally you should be able to make a variable which is the energy value the importer pulled that tick, then use that value for things, such as say turning on auxillary power supplies when the existing one hits a certain load.

**Comment by rubensworks** [comment]
Nice, Voltorb with an energy capability :-)

This can be done using the Delayer, which allows you to calculate the differential value of the energy level of the battery.

Many people however seem to be requiring such a mechanism, so perhaps I should start looking into a simplified form of the Delayer to calculate things like RF/t, or items/t more easily. I'll think about it.

**Comment by Thutmose** [comment]
Ahh, so I need to use a battery for this, is there any limit to what the battey can input/output? I want to have a setup where I have the voltorbs producing baseline power, then turn on a nuclear reactor when I need more, so ideally I will use this as a substation like thing to control my various power systems.

All electric types in pokecube have had energy capabilities since they were added as a thing :D, and this gave me a wonderful way to test that they actually worked with other mods

**Comment by rubensworks** [comment]
No, the batteries are intentionally made quite "dumb". I/O limitation can be achieved using the more advanced energy importer/exporter aspects.

For instance, you could read the energy inside the battery, get the history of that value using a Delayer, take the difference of the two latest values to get the increase in last tick, and if that value is too low, power on your other energy production systems.

**Comment by Thutmose** [comment]
ahh ok, I didn't even notice a delayer when I was looking through, I guess I should have looked a bit more carefully

**Comment by Thutmose** [comment]
how do I go about linking the variable card to the value in the battery?

I have tried crafting the card with it, tried various ways to access it, not sure how to go about linking the card to it.

**Comment by rubensworks** [comment]
That can be done using just Integrated Dynamics, not Tunnels.
You have to place a machine reader on the battery, and link a variable to the value of the target in the GUI.

**Comment by Thutmose** [comment]
ahh ok, will do that, thanks for the quick response

**Comment by Thutmose** [comment]
looking at this, I don't even need the delayer, I can just have it turn on additional power if the battery has a stored value below whatever full - drain is
