### ISSUE TITLE
Player simulation crash

### ISSUE THREAD

**Issue by darkshadow543** [CyclopsMC/IntegratedTunnels#70]
MC: 1.12.2
IT: 1.3.4
ID: 0.9.4
CC: 0.10.22
Forge: 14.23.0.2528
Crashlog: https://pastebin.com/8r2niKLi
I think it might have to do with loading.

**Comment by rubensworks** [comment]
Fake player seems to be null for some reason. This seems to be related to incorrect initialization indeed.

**Comment by homemmakako** [comment]
I just had the same problem. It might be useless, but here is a second [crash log](https://pastebin.com/ken7bJDu) 😝

**Comment by rubensworks** [comment]
@homemmakako Good thing you sent me that crashlog, because that was actually being caused by a completely different problem :-) Will be fixed in the next update.
