### ISSUE TITLE
Configurable limitations on transfer rate

### ISSUE THREAD

**Issue by DaComputerNerd717** [CyclopsMC/IntegratedTunnels#72]
Add a config option for an upper limit to the tunnel's transfer rates. One each for items, fluids, and energy. Could use -1 and down as an infinite transfer rate, and any positive/zero value as maximum transfer rate.

**Comment by rubensworks** [comment]
This is already possible in the config files. `fluidRateLimit` for instance is the maximum fluid rate, which is currently set to the maximum value. For energy, this has to be configured in Integrated Dynamics.
The max rate of item transfer is always once stacksize.
