### ISSUE TITLE
Add Player Simulation option to sneak

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedTunnels#73]
Some click actions could use an option to enable player sneaking.

**Comment by moonheart08** [comment]
Would pushing/holding buttons even be possible for a fake player? If so, that'd be nice too. (Some mod items have secondary abilities triggered by pushing keys)

**Comment by rubensworks** [comment]
@moonheart08 Certain hotkeys you mean? In theory that would be possible yes, but practically this would require a lot of hacking, so not something I plan on doing anytime soon.

**Comment by moonheart08** [comment]
Yea, certain hotkeys. Plus, it'd give me another excuse to use integrated tunnels more :p 
I can see why it'd be hacky, tho.

**Comment by rubensworks** [comment]
@moonheart08 Can you make a separate issue on this? It's an interesting idea, maybe I'll have some time in the distant future.
