### ISSUE TITLE
Importers/Exporters accepting anything when active

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedTunnels#75]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
When fluid importers are used with the boolean aspect, any kind of fluid can be pushed in it even if the boolean value is false.

Next to this, adding an aspect property to disable active importing/exporting would also be nice.

**Comment by rubensworks** [comment]
On second thought, this is not a bug, just not a feature.

**Comment by josephcsible** [comment]
I think this is actually a bug that should be fixed. Being false shouldn't be any different than being completely inactive. Related: #69. I'm not sure whether these parts (item importers/exporters do it too, not just fluids) should expose the network like this.

**Comment by rubensworks** [comment]
@josephcsible I'll make it a feature request then.

The difficulty lies in the fact that not only booleans, but also the more complex filter aspects should be checked. It is not impossible to do, it just takes some implementation effort.

> I'm not sure whether these parts (item importers/exporters do it too, not just fluids) should expose the network like this.

They should IMO. Some things (like IE's garden cloche) do not accept manual importing, they push things themselves. So for the user it is too confusing that IT importers can not be used in this case. But indeed, these things should adhere to the configured aspects, which they do not do at the moment.

**Comment by josephcsible** [comment]
> They should IMO.

Ehh, I'm not so sure. But in any case, they definitely need an option to turn it off, like we want to add to interfaces.

**Comment by rubensworks** [comment]
> they definitely need an option to turn it off

I can agree with that, but it should be enabled by default.

**Comment by josephcsible** [comment]
If this mod weren't released yet, I'd disagree, but for BC reasons, yes, it should. Anyway, once we set up that option, for consistency, we should make it always work if it's on, even without a variable card.

**Comment by KollinsPlays** [comment]
I think I am having the same issue, but I'm not sure. I have a generator that pushes energy and an Energy Importer set to only import if energy level is below a threshold. With no variable card in the Importer, it does not accept energy (I expected this) but with my programmed variable card in the Import Energy VC slot, it accepts energy the generator pushes whether or not the variable is true or false (not expected.) I tested with my programmed card, but confirmed a VC just set to boolean false will make it take in energy, but removing that card it stops taking energy.

**Comment by Jack-McKalling** [comment]
Besides the instructions of present variable cards, the transfer of fluid/item/energy also fully ignores certain settings on the Importer/Exporter, such as the Ticks/Operation value. If an energy importer on a battery is limited to transfer energy once every 500 ticks for example, using a lever on the battery to force it through the importer will transfer it once every tick instead.

**Comment by rubensworks** [comment]
Thanks for reporting!
