### ISSUE TITLE
Find typo in en_US.lang

### ISSUE THREAD

**Issue by yuanjie000** [CyclopsMC/IntegratedTunnels#76]
_Only keep the issue types that are applicable._

- :bug: Bug
> https://github.com/CyclopsMC/IntegratedTunnels/blob/571aebfe1fa55b8720dd0b138ca4307fac3ebd9f/src/main/resources/assets/integratedtunnels/lang/en_US.lang#L358

this is fluid text, but the content is about energy!

**Comment by rubensworks** [comment]
Whoops! Thanks for reporting!
