### ISSUE TITLE
Energy transfered to Actually Additions 

### ISSUE THREAD

**Issue by jinkhya** [CyclopsMC/IntegratedTunnels#77]
Hello,

Could you add some compatiblity with Actually Additions machines so that they get energy from the nerwork with the Energy Interfaces? That'd be awesome ! :)

Thanks in advance,
Jin

PS : Version is IntegratedTunnels-1.10.2-1.2.6
with forge 12.18.3.2422

**Comment by rubensworks** [comment]
That's already possible, as AA machines also accept Forge energy.

**Comment by jinkhya** [comment]
Then it doesn't work properly. I could transfer energy to EnderIO machines but not to the Atomic Reconstructor nor the display stands.

**Comment by josephcsible** [comment]
Integrated Tunnels doesn't automatically push or pull energy anywhere. Unless everything that you're connecting it to does, you need to use importers on your generators, interfaces on your batteries, and exporters on your machines (and activate the importers and exporters with variable cards). Are you doing this?

**Comment by jinkhya** [comment]
I have importers on my battery that is getting powered directly, then interfaces on machines. I can try using an exporter on my stands but I'm not sure why I'm getting power on EnderIO machines with interfaces then if I need exporters. I'll try that though.

**Comment by jinkhya** [comment]
same issue, I put energy exporter on alloy smelter and on display stand ; energy interface on a full battery. The alloy smelter is getting energy, the display stand isn't.

**Comment by rubensworks** [comment]
Sounds like an issue with AA then.
They are probably not supporting FE yet in their 1.10 versions.
I doubt they are still maintaining that version though.

Installing this mod might help: https://minecraft.curseforge.com/projects/energysynergy

**Comment by jinkhya** [comment]
Hello, yep it does solve the problem, thanks a lot !
take care.
