### ISSUE TITLE
Operator chrashes the game and prevents restarting.

### ISSUE THREAD

**Issue by Kaladum** [CyclopsMC/IntegratedTunnels#79]
#### Issue type:
- :bug: Bug
____
#### Short description:
Inserting an operator set to Item Damage to the predicate slot of the item im/exporter can crash the game and prevent loading the world.

#### Expected behaviour:
Recognize the operator and mark it as invalid.

#### Actual behaviour:
The bug occurs after you insert a variable card with the operator "Item Damage" in the slot for item predicate of an item im/exporter. The GUI shows the text "Item Damage" in green letters at the bottom for a moment. At this time the game has already crashed. Reloading the world after restarting MC crashes the game again. I have repaired my savegame by removing the item importer block with MC Edit.

Sorry the problem might be a bit strange but i can't find any tutorial for the predicate/operator functions of this mod. I was just messing around to learn something.

#### Steps to reproduce the problem:
1. Install FTB Presents Direwolf20 1.12(v1.1.0).
2. Open the logic programmer and select operator from the list.
3. Apply the operator item damage to a variable card.
4. Open the GUI of an item importer.
5. Put the variable card in the slot Import Items Predicate.
6. Game crash
7. Restart mc and load the game again to see the next crash.

#### Versions:
- This mod: IntegratedTunnels-1.12.2-1.3.5.jar
- CyclopsCore: CyclopsCore-1.12.2-0.10.23.jar
- Minecraft: 1.12
- Forge: forge-1.12.2-14.23.0.2531.jar 

#### Log file:
https://pastebin.com/JnvEenS3

**Comment by rubensworks** [comment]
That's strange, you should not even be able to insert that predicate.
I'll make sure to add a check to prevent that in the next update.

Don't the tutorials in the book help you?

**Comment by Kaladum** [comment]
Thx for your answer and the for fixing the bug in the next update. 

I somehow missed the Tutorials part of the book and looked at the page for the importer. I am sure i can figure it out with this informations.
