### ISSUE TITLE
Cable connecting issue

### ISSUE THREAD

**Issue by Daenara** [CyclopsMC/IntegratedTunnels#8]
I noticed that the cable doesn't connect right if you put the last piece in between in Integrated Tunnels interface and the cable. It works if you put a piece of cable on the interface first, then connect it. 

![1_cable_error](https://cloud.githubusercontent.com/assets/3619315/21605561/43fdc184-d1aa-11e6-8cde-f275860a2608.png)
![2_cable_connected](https://cloud.githubusercontent.com/assets/3619315/21605562/43fe4a8c-d1aa-11e6-98ee-1df2c41f5ce9.png)

It's not a big problem but I thought I should report it.

**Versions:** 
Minecraft 1.10.2
Forge 12.18.3.2185
Integrated Dynamics 0.6.5
Integrated Tunnels 1.0.2

Daenara

**Comment by rubensworks** [comment]
Thanks for reporting this!
Moved the issue to Integrated Dynamics: https://github.com/CyclopsMC/IntegratedDynamics/issues/102
