### ISSUE TITLE
Player Simulator "Click Item" still voiding items

### ISSUE THREAD

**Issue by awebneck** [CyclopsMC/IntegratedTunnels#81]
#### Issue type:

- :bug: Bug

____
#### Short description:

When using the Player Simulator "Click Item" aspect in 1.12-1.3.5, while the simulator does appear to consume the item from an attached inventory, no result is seen in the world and the item is voided. This does *not* happen with the "Click" (i.e. any item) aspect - everything works fine there. But when using a variable representing an item (and the variable is correct according to an attached display screen) in the "Click item" slot the item is consumed and voided.

#### Expected behaviour:

When presenting an item variable to the Player Simulator in the "Click Item" aspect variable slot, with the Player Simulator facing a vanilla item frame, and variable is verified correct and present, I expect the simulator to accurately click the item (configured for right-click, as default) into the frame.

#### Actual behaviour:

The Simulator does appear to recognize and consume the item, but the item is not placed into the frame and voided.

#### Steps to reproduce the problem:

1. Place the following items:
  - 1x chest
  - 3x logic cable
  - 1x item interface
  - 1x inventory reader
  - 1x display panel
  - 1x player simulator
  - 1x item frame
as shown here:
![2017-11-24_15 53 18](https://user-images.githubusercontent.com/153561/33224531-f45938b2-d12f-11e7-929a-7b54cdfb0e8c.png)
 
1. Create a constant boolean true variable, and place this into the player simulator "Click" (i.e. any item) aspect. Verify that this is configured to right-click.
1. Add any frameable item (This is reproducible for me across many different objects and many different target "clickable" blocks - not just item frames - but this is the simplest example I could come up with) to the chest, and observe that the player simulator correctly "right-clicks" and places the frameable item in the item frame, as expected.
1. Remove the constant boolean true variable from the player simulator.
1. Store the "Slot Item" (configured to slot 0) from the inventory reader in a new variable, and add this to the display screen to verify. Verify that when an item is placed into the chest's first slot, it correctly appears on the display screen.
1. Remove this variable from the display screen and place into the player simulator "Click Item" aspect.
1. Notice that while the item is consumed from the chest's slot 0, the item has failed to be placed into the item frame and appears to be voided.

____
#### Versions:

- This mod: 1.12.2-1.3.5
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2531

#### Log file:

Nothing relevant in log file as no crash or error occurs or is logged

**Comment by awebneck** [comment]
Should note that I did see issue #68, and verified that the version of the mod I'm using (1.12.2-1.3.5) includes the fix for that issue, at least according to the git tags. Issue persists.

**Comment by awebneck** [comment]
Should also add that this occurred initially in the new Direwolf20 1.12.2 FTB modpack.

**Comment by rubensworks** [comment]
Thanks for reporting! Will look into it.

**Comment by awebneck** [comment]
@rubensworks Dug into it a bit on my own - looks like this line in the CommonCapabilities library https://github.com/CyclopsMC/CommonCapabilitiesAPI/blob/6fb398ab7266e521bd1882226df8eb448e7cbf44/capability/itemhandler/DefaultSlotlessItemHandlerWrapper.java#L54 is actually changing the matchStack (as the matchStack is simply a reference back to the actual stack in the chest) - so by the time it tries to ensure they're the same thing the matchStack is actually different than the extractedStack, the match is failing, and the extracted stack - while still extracted from the source - is not getting pushed out to the target

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CommonCapabilitiesAPI">CyclopsMC/CommonCapabilitiesAPI</a></strong></div><div>CommonCapabilitiesAPI - The public API for CommonCapabilities</div></blockquote>

**Comment by awebneck** [comment]
PR https://github.com/CyclopsMC/IntegratedTunnels/pull/82 resolves it, though that solution may be a bit naive - you'd know better than I. :)

**Comment by rubensworks** [comment]
@awebneck Thanks a lot for looking into this, you just saved me some debugging time :-)
