### ISSUE TITLE
Item exporter property Item Slot crash

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedTunnels#89]
#### Issue type:

- :bug: Bug

____
#### Short description:
Item exporter crashes server while attempting to insert from a list of items into an inventory slot outside the valid range.

#### Expected behaviour:
Graceful denial of export?

#### Actual behaviour:
Server crash.

#### Steps to reproduce the problem:

0. Install FTB Presents Direwolf20 1.12(v1.2.0).
1. Attach Item exporter to machine (AE2 inscriber in my test)
2. Attach Item Interface to chest to provide exportable items
3. Connect with cables
4. Create variable: list of items to export.
5. Insert variable into Item exporter slot: Export Items
6. Set Export Items property Item Slot to a value outside the valid range (2 in my test)

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: IntegratedTunnels-1.12.2-1.3.5
- CyclopsCore: CyclopsCore-1.12.2-0.10.23
- Minecraft: minecraft_server.1.12.2
- Forge: FTBserver-1.12.2-14.23.1.2555-universal

#### Log file:

https://pastebin.com/3t0b8c1t

**Comment by rubensworks** [comment]
Indeed, that should not crash.

**Comment by josephcsible** [comment]
We should see if the crash happens with a vanilla chest or furnace in place of the AE2 inscriber. If it doesn't, then this is their bug, not ours.
