### ISSUE TITLE
[Curseforge] Possible Typo on Curseforge project page

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/IntegratedTunnels#91]
#### Issue type:

_Only keep the issue types that are applicable._

- :question: Question

On the Curseforge project page there is the phrase 'for extracting or ingesting energy'. Shouldn't that be 'for extracting or **inserting** energy'? As it is, both terms mean roughly the same thing (taking energy out), and it reads kind of weird.

**Comment by rubensworks** [comment]
It's the same thing, really. I use 'ingesting' more than 'inserting' in my day-to-day life, which is probably why I used it there. Also, it sounds a bit fancier, so I'll leave it as is :-)
