### ISSUE TITLE
Crash - Player Simulator - Morph

### ISSUE THREAD

**Issue by SirFlip** [CyclopsMC/IntegratedTunnels#92]
#### Issue type: Server Crash

_Only keep the issue types that are applicable._

- :bug: Bug
____
#### Short description: 
Crash when killed by Player Simulator
Also happens when mobs are killed

#### Expected behaviour: 
Player/mob dies no crash

#### Actual behaviour: 
Game crashes

#### Steps to reproduce the problem:

1. Get killed by Player Simulator

____
#### Versions:

- This mod: 1.3.5
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Morph: 1.12.2-7.1.1
- iChunUtil: 7.1.3

#### Log file:
https://gist.github.com/SirFlip/8ad0e572ebb81f24d1b7c31305962b08

Because I don't know where the bug is I also post it on Morphs Issue Tracker and link it here
iChun/Morph#907

**Comment by rubensworks** [comment]
Nothing we can do about this on our end unfortunately (as has been confirmed on the referenced issue).
