### ISSUE TITLE
Tunnel Proxy

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedTunnels#98]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request
____

A _Tunnel Proxy_ is a block that exists in item, fluid and energy form, and allows restrictions to be placed on each side.

When the gui is opened, is should show a variable slot input and output side (2 times 6). These slots take boolean, element (item, fluid, integer), element lists or predicate variables, and indicate the filter that should be applied when things are pushed through the proxy.

By default, when no variable is present, the side should allow everything (?)

Instead of restrictions per side, just consider doing a single restriction type on all sides. Where the restriction may optionally be disabled per side (makes the GUI simpler).

Related to #90

-----

Alternatively, a more flexible option would be to create a _Filtering Interface_ that exists in item/fluid/energy form. This would act just like a regular interface, but it takes a variable card that allows to define what is allowed to go through the interface (both in and out).

**Comment by antrobot1234** [comment]
is there any timeline on when this is planned on being added?

**Comment by rubensworks** [comment]
Thanks for the suggestion!
