### ISSUE TITLE
Game Crash: Operator ValueTypeOperator$ValueOperator cannot be cast to ValueTypeBoolean$ValueBoolean

### ISSUE THREAD

**Issue by cpw** [CyclopsMC/IntegratedTunnels#99]
#### Issue type:
- :bug: Bug
___
#### Short description:
Game crash, ClassCastException.

#### Expected behaviour:
Game doesn't crash

#### Actual behaviour:
Game crashes, with a class cast exception. World cannot be loaded anymore.

#### Steps to reproduce the problem:
1. Not sure. I was trying to create an Operator that would fulfill the ItemExportPredicate - basically, I was trying to create a predicate chain that performed stacksize % 2 == 0 (this is NOT easy to do, sadly) and I placed it into the item exporter as the predicate and the game crashed. Similar to #79.
The exact sequence isn't 100% clear - I think I had an apply on operator not equal, with a flipped apply of 2 to operator mod and operator item stack count. It's pretty complex. Could you retrieve it with a world save?
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-1.4.0
- CyclopsCore: 1.12.2-0.11.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2581 (sort of, I'm running a custom build to fix an annoying graphics issue, pending merge or rollback in Forge).

#### Log file:
Attached as https://gist.github.com/cpw/fa5d5ea436058e42ec8004a6e5a3d7f2

**Comment by rubensworks** [comment]
Thanks! Looks like a value type validation check that is missing.

Note to self: check if the mechanism that disables networks after crashes is still working.
